JacquesCarette/Drasil

code/Language/Drasil/HTML/Print.hs, code/stable/gamephys/Chipmunk_SRS.html, code/stable/glassbr/GlassBR_SRS.html, code/stable/nopcm/NoPCM_SRS.html, code/stable/ssp/SSP_SRS.html, code/stable/swhs/SWHS_SRS.html, code/stable/tiny/SRS.html
Hint to browsers that the charset is UTF-8 due to "Système International d'Unités".
=> Add meta charset tag to HTML output generation.

code/Language/Drasil/HTML/Print.hs, code/Language/Drasil/People.hs, code/stable/gamephys/Chipmunk_SRS.html, code/stable/gamephys/Chipmunk_SRS.tex, code/stable/glassbr/GlassBR_SRS.html, code/stable/glassbr/GlassBR_SRS.tex, code/stable/nopcm/NoPCM_SRS.html, code/stable/nopcm/NoPCM_SRS.tex, code/stable/ssp/SSP_SRS.html, code/stable/ssp/SSP_SRS.tex, code/stable/swhs/SWHS_SRS.html, code/stable/swhs/SWHS_SRS.tex, code/stable/tiny/SRS.html, code/stable/tiny/SRS.tex
Fixes a previous refactoring which removed spaces between names. 
[Commit 1019565](https://github.com/JacquesCarette/Drasil/commit/10195651cd0c2ee467ac69102c1de6c6065c7b3d) refactored _People_ to output _String_ instead of _Sentence_, however the +:+ combinator was replaced with ++. The former adds a space between two sentences if both are non-empty.  [Commit 4942a2a](https://github.com/JacquesCarette/Drasil/commit/4942a2a1b9d4ab642d4f4edf0c0c8fc6e9416b4c) is the commit where stable was updated with the erroneous name output. 
This bug is a shortcoming of the _diff_ command being used; _diff_ is called with argument _--ignore-all-space_ meaning [Commit 1019565](https://github.com/JacquesCarette/Drasil/commit/10195651cd0c2ee467ac69102c1de6c6065c7b3d) would have passed all tests despite not …
=> Fix missing spaces in names.

code/Language/Drasil/HTML/Print.hs, code/Language/Drasil/People.hs, code/stable/ssp/SSP_SRS.html
Followup to #515 
rendPersL now does not have knowledge of how to render a Person. 
This commit:
- Fixes leaking rendering of Person in HTML backend.
- Fixes an instance of a citation ending with '..'
=> Refactor rendPersL.

code/Language/Drasil.hs, code/Language/Drasil/Chunk/Code.hs, code/Language/Drasil/Chunk/Eq.hs, code/Language/Drasil/Chunk/ExprRelat.hs, code/Language/Drasil/Chunk/GenDefn.hs, code/Language/Drasil/Chunk/InstanceModel.hs, code/Language/Drasil/Chunk/Relation.hs, code/Language/Drasil/Classes.hs, code/Language/Drasil/CodeSpec.hs, code/Language/Drasil/HTML/Print.hs, code/Language/Drasil/Printing/Import.hs, code/drasil.cabal
Is there a reason why [this file](https://github.com/JacquesCarette/Drasil/blob/master/code/Language/Drasil/Chunk/ExprRelat.hs) is on its own?
Does it make sense for its contents to be in https://github.com/JacquesCarette/Drasil/blob/master/code/Language/Drasil/Classes.hs, so the data-type-files do not need to import Language.Drasil.Chunk.ExprRelat separately when they are instances of this class?
=> Moving contents of ExprRelat.hs to a more general file

code/Language/Drasil/HTML/Helpers.hs, code/stable/gamephys/Chipmunk_SRS.html, code/stable/glassbr/GlassBR_SRS.html, code/stable/nopcm/NoPCM_SRS.html, code/stable/ssp/SSP_SRS.html, code/stable/swhs/SWHS_SRS.html, code/stable/tiny/SRS.html
Changes `<a>` tag, which didn't include a hyperlink and was only used for the `id` attribute to a `<div>` tag. This was noticeable on macOS' QuickLook as the cursor became a "pointer" when moused over most of the document. 
**Note:** db82cff on branch gabe has already resolved conflicts caused as a result of changes from this branch, so that pull request will come after this one is merged.
=> Change section tags from <a> to <div> in HTML backend.

code/Language/Drasil/HTML/Helpers.hs, code/stable/gamephys/Chipmunk_SRS.css, code/stable/glassbr/GlassBR_SRS.css, code/stable/nopcm/NoPCM_SRS.css, code/stable/ssp/SSP_SRS.css, code/stable/swhs/SWHS_SRS.css, code/stable/tiny/SRS.css
This was noticeable in large tables (like the 3rd traceability matrix in Chipmunk). The left padding would be too large causing the 'x' s to look misaligned and "funny." The table row and column headers would typically overflow their cell and render text outside of it.
=> Change CSS table padding to prevent text from overflowing a table cell.

code/Data/Drasil/Concepts/Documentation.hs, code/Example/Drasil/GlassBR/IMods.hs, code/Example/Drasil/NoPCM/Body.hs, code/Example/Drasil/SSP/GenDefs.hs, code/Example/Drasil/SSP/TMods.hs, code/Example/Drasil/SSP/Unitals.hs, code/Example/Drasil/SWHS/Body.hs, code/Example/Drasil/SWHS/GenDefs.hs, code/Example/Drasil/Sections/SolutionCharacterSpec.hs, code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/Language/Drasil/NounPhrase.hs
I removed all warnings (redundancies, missing type declarations, etc.) when running `make` in the master branch. The following warnings persist:
1. In Goal.hs and AssumpChunk.hs, fields exist that aren't used in the file, but I'm sure that will be better implemented in the future and/or are used in other places in Drasil:
https://github.com/JacquesCarette/Drasil/blob/b6503677bf43a9f4ba41c2e0354fa3ae4fa919f4/code/Language/Drasil/Chunk/Goal.hs#L18-L26
https://github.com/JacquesCarette/Drasil/blob/b6503677bf43a9f4ba41c2e0354fa3ae4fa919f4/code/Language/Drasil/Chunk/AssumpChunk.hs#L16-L21
2. In Attribute.hs, it throws a "redundant pattern match" warning when I don't think it is:
https://github.com/JacquesCarette/Drasil/blob/b6503677bf43a9f4ba41c2e0354fa3ae4fa919f4/code/Language/Drasil/Chunk/Att …
=> Removed Warnings in Make

code/Language/Drasil/Chunk/Concept.hs, code/Language/Drasil/Chunk/Concept/Core.hs, code/Language/Drasil/Chunk/Constrained.hs, code/Language/Drasil/Chunk/DefinedQuantity.hs, code/Language/Drasil/Chunk/Eq.hs, code/Language/Drasil/Chunk/GenDefn.hs, code/Language/Drasil/Chunk/InstanceModel.hs, code/Language/Drasil/Chunk/Relation.hs, code/Language/Drasil/Chunk/Theory.hs, code/Language/Drasil/Chunk/UncertainQuantity.hs, code/Language/Drasil/Chunk/Unital.hs, code/Language/Drasil/Chunk/Unitary.hs, code/Language/Drasil/Chunk/UnitaryConcept.hs, code/Language/Drasil/ChunkDB.hs, code/Language/Drasil/Classes.hs, code/Language/Drasil/Unit.hs
This PR does two things (sorry), both as a result of comments on previous conceptchunk_uid commits.
1. Removes the associated type "DOM" as indicated by [a comment](https://github.com/JacquesCarette/Drasil/commit/6b737048cf59fa194ed4e175e6ac7c00168ea438#r29277062) on commit 6b73704 by @JacquesCarette.
2. Updates lookup function in ChunkDB to use `maybe` instead of pattern matching as suggested by @JacquesCarette in [this comment](https://github.com/JacquesCarette/Drasil/commit/d4261b644c38968c550d99f543e28effc47888e8#commitcomment-29277073) on commit d4261b6.
=> Remove DOM and Update Lookup Functions.

code/Data/Drasil/Concepts/Computation.hs, code/Data/Drasil/Concepts/Documentation.hs, code/Data/Drasil/Concepts/Education.hs
#569 -> Specified
Also added comments to Education.hs, as "undergraduate" and "high school" function as adjectives in "undergraduate degree" and "high school calculus".
=> Improved imports in Concepts/Computation.hs, Documentation.hs, and Education.hs

code/Language/Drasil/Label.hs, code/drasil.cabal
This is for issue #629.
In this PR, the data type `Label` is created and some `mkLabel` constructors as well (which corresponds to the 1st and 3rd points in #567 under Label):
"
- create abstract data type `Label` which has a `uid`, and an enumerated type (`reference address`, `meta-link`, `uri`) and is not "attached" to anything
...
- multiple `mkLabel` constructors should be created for label creation
".
@szymczdm @JacquesCarette Would the next step for these issues be to create the `isLabel` class or make several of the `refer` functions in this module?
Edit: After thinking about it, I think both tasks can be done in parallel... since nothing is implemented yet in the examples, it should be alright starting with either or...
=> Create Label ADT and some constructors

code/Language/Drasil/Chunk/Concept.hs, code/Language/Drasil/Chunk/Concept/Core.hs
This is the first of (probably) a few pull requests to enable/support referencing of `ConceptChunk` s as per #562 [comment 6](https://github.com/JacquesCarette/Drasil/issues/562#issuecomment-393544664), third bullet point. 
In an effort to not break everything, Maybe was added to the ShortName field's type for `ConceptChunk`. All existing constructors for `ConceptChunk` have been updated to "ignore" the short name. Which I believe makes sense as not all `ConceptChunk` s will be referenced. 
@JacquesCarette I misspoke earlier. All the constructors of `ConceptChunk` take an existing `NP` (or type which contains an `NP`) as input so we don't have the `String` mentioned when `ShortName` would be constructed. 
PS. I will send another PR adding Label related content once #643 has been merged.
=> Add ShortName to ConceptChunk.

code/Language/Drasil/Chunk/UncertainQuantity.hs
As @JacquesCarette mentioned in comments of PR #637, it would be beneficial to have the constructors for uncertainty to ensure that uncertainty is between 0 and 1, and throw an error otherwise.
Tested with values 0 and 5 threw the error (desired result).
=> Bw0And1 Creation

code/Language/Drasil/Reference.hs
This is the second of (probably) a few pull requests to enable/support referencing of `ConceptChunk` s as per #562 [comment 6](https://github.com/JacquesCarette/Drasil/issues/562#issuecomment-393544664), third bullet point. 
This commit adds the necessary infrastructure to `RefDB` to facilitate the use of `ConceptChunk` s. 
This commit does not include being able to insert `ConceptChunk` s into the database. Nor does it add `Referable` support.
=> Update infrastructure of References to support ConceptChunks.

code/Example/Drasil/GlassBR/Unitals.hs, code/stable/glassbr/GlassBR_SRS.html, code/stable/glassbr/GlassBR_SRS.tex
As per #675, GlassBR was updated in stable and generated to reflect changes in smiths/caseStudies@8f7bb39.
=> Updated GlassBR SRS (c)

code/Example/Drasil/DocumentLanguage.hs, code/Example/Drasil/SRS.hs, code/Example/Drasil/SSP/Body.hs, code/Example/Drasil/SSP/Changes.hs, code/drasil.cabal, code/stable/ssp/SSP_SRS.html, code/stable/ssp/SSP_SRS.tex
As mentioned in smiths/caseStudies#47, an unlikely changes section can be added to the SSP example.
This PR's end files reflect said change, however, similar to PR #681, the links to assumptions need to be checked as their generated addresses are not defined. (Tracking in #683.)
=> Added Unlikely Changes Section to SSP

code/Example/Drasil/SSP/Body.hs, code/stable/ssp/SSP_SRS.html, code/stable/ssp/SSP_SRS.tex
Small change propagating from smiths/caseStudies#98: add note for the force diagram picture about relabelling E to G.
=> SSP Image Symbol Update Note

code/Language/Drasil/TeX/Preamble.hs, code/stable/gamephys/Chipmunk_SRS.tex, code/stable/glassbr/GlassBR_SRS.tex, code/stable/nopcm/NoPCM_SRS.tex, code/stable/ssp/SSP_SRS.tex, code/stable/swhs/SWHS_SRS.tex, code/stable/tiny/SRS.tex
As discussed in #701, removing `Breqns` for now may be a good idea to get the pdfs to generate for the SWHS and SSP examples (along with removing some of the warnings coming up in the other examples).
=> commented out/removed Breqns

code/Language/Drasil/Document.hs
This PR is just turning `Section` into a record type as discussed #695, `Label` has not been added as that is occurring in a separate branch
=> Turned Section into a record type as discussed in issue #695

code/Example/Drasil/GlassBR/Assumptions.hs, code/Example/Drasil/GlassBR/References.hs, code/stable/glassbr/GlassBR_SRS.html, code/stable/glassbr/GlassBR_SRS.tex
As per #721, the names of the references were renamed according to the agreed-upon convention of AuthorYYYY.
=> Renamed Reference Names in GlassBR

code/drasil-code/Language/Drasil/Code/AST.hs
The import list was incorrect, @JacquesCarette Should I still avoid specifying the imports of `Language.Drasil`?
=> Corrected import of AST.hs

code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs
As per issue #569.
@JacquesCarette Hello Dr. Carette, I tried to explicitly import things from `AST.hs` in this file but there were a lot of things imported over from there so I've left it as is and will keep it un-checked in issue #569 so that I can come back to it.
=> Improved imports in LanguageRenderer.hs

code/drasil-code/drasil-code.cabal, code/drasil-data/drasil-data.cabal, code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/SWHS/Changes.hs, code/drasil-example/drasil-example.cabal, code/drasil-lang/drasil-lang.cabal, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
As it is I am unable to move likely or unlikely changes to a separate file, `Changes.hs`, due to them referencing assumptions which are defined in `Body.hs` due to them needing to reference `IMs`. Creating `Changes.hs` now would result in an import cycle, however, this can be fixed once `Label` is implemented. 
For now, I've defined unlikely changes so that, once able to, creating `Changes.hs` would only require moving them out of `Body.hs`.
=> Added Unlikely Changes to NoPCM

code/drasil-example/Drasil/GlassBR/DataDefs.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
- Changed "tolerable pressure" to "tolerable load" in notes as per #752
- Fixed spacing typo in stable of Unlikely Changes of SWHS
- not caught in .log because spacing is ignored
I'm not sure if this even needs a pull request, but I'd rather be safe than sorry.
=> *Small PR* Fixed Tolerable Load

code/drasil-lang/Language/Drasil/HTML/Print.hs, code/drasil-lang/Language/Drasil/Printing/AST.hs, code/drasil-lang/Language/Drasil/Printing/Import.hs, code/drasil-lang/Language/Drasil/Printing/LayoutObj.hs, code/drasil-lang/Language/Drasil/TeX/Print.hs
This PR is a part of the infrastructure needed for #562. Specifically this provides a replacement for `ALUR` at `LayoutObj` level. 
Currently, the replacement is unused.
=> Add Maybe Label to the items in LayoutObj's List constructor.

code/drasil-code/Language/Drasil/Chunk/Code.hs
As mentioned in the comments of commit 62c3725, the fix implemented for `DataDefinition` was sub-optimal.
=> [Small PR] qtoc is now constraint-based instead of type-based

code/drasil-data/Data/Drasil/Utils.hs, code/drasil-docLang/Drasil/DocumentLanguage/Definitions.hs, code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Document.hs, code/drasil-lang/Language/Drasil/Document/Extract.hs, code/drasil-lang/Language/Drasil/Printing/Import.hs, code/drasil-lang/drasil-lang.cabal
This PR is part of #562. It's a followup to #845 by adding support to `Contents`' `Enumeration` to make individual items referable. It "connects" the references in `Contents` to those in `LayoutObj`. Currently, nothing uses `Enumeration` references and all examples have been updated using the convenience functions `noRefs` and `noRefsLT` to maintain current behaviour.
=> Makes Elements in Contents' Enumerations Referable

code/drasil-lang/Language/Drasil/Chunk/Concept.hs
This PR is part of #562. It moves the domain argument to be the last in the `cic` constructor. 
This change is aimed to make using `ConceptInstance` more ergonomic by being able to `zipWith` over `[Concept -> ConceptInstance]`. The rational is a list of `ConceptInstance`s probably all belong to the same domain, so by being able to (easily) associate a domain to an entire list reduces inconsistencies, and helps avoid tedium while writing something like requirements or assumptions.
=> [Small] Change argument order for cic

code/drasil-example/Drasil/GlassBR/Unitals.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html
As per smiths/caseStudies#137, the input data constraints for AR and SD were made inclusive for consistency.
=> [Small PR] Made Input Data Constraints Inclusive 

code/drasil-docLang/Drasil/DocLang.hs, code/drasil-docLang/drasil-docLang.cabal, code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/drasil-example.cabal, code/drasil-printers/Language/Drasil/TeX/Print.hs, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html
This PR is part of #562. It introduces the first use of `ConceptInstance` into the examples. This PR only affects the functional requirements of NoPCM. The old requirements still exist for compatibility with SWHS. As noted, there is a small formatting change with the new requirements as highlighted in the extended commit message of f123c6b. Below is a comparison of the requirements formatting:
I have included @smiths as a reviewer due to this formatting change.
=> Use ConceptInstance for NoPCM Reqs

code/drasil-docLang/Drasil/DocLang.hs, code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-docLang/Drasil/Sections/Requirements.hs, code/drasil-docLang/drasil-docLang.cabal, code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/drasil-example.cabal, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/drasil-lang.cabal
This PR adds domains used in `ConceptInstance`s to the `ConceptMap` in `ChunkDB`. This PR is part of #562 specifically, [comment 19](
https://github.com/JacquesCarette/Drasil/issues/562#issuecomment-410323483).
The domains are not currently used from the database.
=> 562 Domains in ChunkDB

code/drasil-printers/Language/Drasil/TeX/Helpers.hs, code/drasil-printers/Language/Drasil/TeX/Print.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/nopcm/SRS/NoPCM_SRS.tex
This PR is a first step in #984, it introduces a (temporary) function `snref` which uses the `hyperref` package and macro to set the displayed text on references. It is used when the `RefType` of a `Ref` is `Blank` as that seems like the best way to transition from `RefType`.
Additionally, `hyperref` appears to not link to a specific `item`, but the previous section. This is the reason `\phantomsection` is added before labels in enumerations, so the reference points to the item specifically.
=> Add transitional framework for shortname use to TeX printer.

code/drasil-example/Drasil/SSP/Assumptions.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SSP/Changes.hs, code/drasil-example/Drasil/SSP/Requirements.hs, code/drasil-example/drasil-example.cabal, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This PR continues work on #985. Like the other example migrations, Assumption `ConceptInstance`s are present but unused at the moment.
=> Migrate SSP to ConceptInstance.

code/drasil-docLang/Drasil/DocumentLanguage.hs
Since the cases are using specific types, the old way of using constraints was changed.
=> Apply the specific types in DocumentLanguage.

code/drasil-example/Drasil/SSP/Assumptions.hs, code/drasil-example/Drasil/SSP/BasicExprs.hs, code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SSP/GenDefs.hs, code/drasil-example/Drasil/SSP/IMods.hs, code/drasil-example/Drasil/SSP/Labels.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
When tried to move references in assumptions, found that there are too many inconsistencies, especially many references were not correct in SSP.
After this PR, even though there are still some inconsistencies, but all the references related to Assumptions are correct and complete. Those references should be matching manual version. 
Also, fixed issue #449.
=> Improve Consistency of Manual version and Drasil

code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-docLang/Drasil/TraceTable.hs, code/drasil-docLang/drasil-docLang.cabal, code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/GlassBR/TMods.hs, code/drasil-example/Drasil/HGHC/HGHC.hs, code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/drasil-example/drasil-example.cabal, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/ChunkDB.hs, code/drasil-lang/drasil-lang.cabal
This PR does two things:
* Abstracts common operations for/involving `ChunkDB` to have one central implementation (more DRY if you will).
* Adds ordering to many of the tables in `ChunkDB`.
The ordering is implemented such that sorting the _values_ of the tables in ascending order should be the identity with the input list. (After slicing off the second element in the tuple).
Currently, nothing uses this ordering and this is "just" an infrastructure PR. The idea behind having an explicit ordering (the input list order) is it allows for control within individual example recipes and it provides a "user-facing" deterministic way in which tables can be transformed into lists (rather than the `Map` default of ascending order of keys –– `UID` –– which as I understand is supposed to be "just" …
=> Ordering for ChunkDB

code/drasil-docLang/Drasil/ExtractDocDesc.hs, code/drasil-docLang/drasil-docLang.cabal, code/drasil-example/drasil-example.cabal, code/drasil-gen/drasil-gen.cabal, code/drasil-lang/Language/Drasil/Document/Core.hs, code/drasil-lang/drasil-lang.cabal, code/drasil-printers/Language/Drasil/HTML/Print.hs, code/drasil-printers/Language/Drasil/Printing/Import.hs, code/drasil-printers/Language/Drasil/Printing/LayoutObj.hs, code/drasil-printers/Language/Drasil/TeX/Preamble.hs, code/drasil-printers/Language/Drasil/TeX/Print.hs, code/drasil-printers/drasil-printers.cabal
This PR builds on #1091 by removing the `Assumption` from `Document` in lang and `ALUR` (and friends) from printers. 
This PR is requesting to merge onto QDef-in-InstMod. 
The build failures are again from the build failures on base QDef-in-InstMod.
=> Removes Assumption from Backend

code/drasil-printers/Language/Drasil/TeX/Helpers.hs
This is a tiny PR which takes care of #1026.
Like the rest of the recent PRs involving ConceptInstance, this PR is requesting to merge onto QDef-in-InstMod. Similarly the CI failures are the same as those found in QDef-in-InstMod.
=> Remove *ref Functions from TeX Printer

code/drasil-data/Data/Drasil/Citations.hs, code/drasil-data/Data/Drasil/Concepts/Math.hs, code/drasil-data/Data/Drasil/Quantities/Math.hs, code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GamePhysics/Unitals.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SSP/Unitals.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This pull request:
- adds a DD to the SSP example for the interslice force ratio variation function
- changes pi_ to a `DefinedQuantityDict` so that it can be used in said DD
- fixes the small bug where spaces were removed from a citation which accidentally got merged before
=> SSP Interslice Force Ratio Variation Function DD

code/Makefile
Welcome to the first Drasil “Choose Your Own Adventure!”
It’s late, you’re building Drasil. You notice compile times are long when building from scratch. You open your favourite editor and load `Makefile`. What’s this? You notice the package building targets are chained after one another. Oh no! But from the cabal files, you know `drasil-data`, `drasil-printers`, and `drasil-code` only depend on `drasil-lang` and could all be built simultaneously. No time like the present to fix this! But where to go? Where to go?
The Stack docs: #1107
You know Makefiles (probably): This PR
You know Makefiles. You don’t need to rely on Stack to figure out dependencies for you. You can do that yourself! You quickly change the Makefile to pattern match on which module it is building and pull the …
=> Refactor Package Build Targets 

code/Makefile
Welcome to the first Drasil “Choose Your Own Adventure!”
It’s late, you’re building Drasil. You notice compile times are long when building from scratch. You open your favourite editor and load `Makefile`. What’s this? You notice the package building targets are chained after one another. Oh no! But from the cabal files, you know `drasil-data`, `drasil-printers`, and `drasil-code` only depend on `drasil-lang` and could all be built simultaneously. No time like the present to fix this! But where to go? Where to go?
The Stack docs: This PR
You know Makefiles (probably): #1106
You dive into the Stack docs looking around to see if there’s any way to build all dependencies of a package. After some searching. You find it! Turns out that’s always the case. You edit the Makefile and type `make` …
=> Refactor Package Targets Using Stack

code/Makefile
This is a small PR. It adds back the ability to build individual packages which was "a regression" from #1107. The primary `make` still uses only `build_example`. However commands like `make build_lang` will work now.
=> Add back the ability to compile individual drasil-* packages.

code/stable/ssp/SRS/SSP_SRS.tex
This PR fixes a "merge miss" between the last SSP merge (#1111) and the merge of Building TeX (#1114) where a new `dmath` was introduced to SSP and not changed to `displaymath`.
=> Fix Stable

code/drasil-printers/Language/Drasil/TeX/Helpers.hs, code/drasil-printers/Language/Drasil/TeX/Print.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/tiny/SRS/Tiny_SRS.tex
This is a tiny PR which fixes a few instances of TeX warning of "Underfull \hbox" and "Underfull \vbox".
One instance comes from `longtable` where it [expects a `\endfirsthead` or `\endhead` after the header](https://tex.stackexchange.com/questions/71096/underfull-vbox-in-each-longtable-can-it-be-fixed-or-must-it-be-ignored). I've included a screenshot below of a `longtable` in one of the examples and how it looks with a repeated header after a page break (a choice I have made which can be changed back –– I've included @smiths as a reviewer for this purpose).
The other comes from [forcing `\\` in a paragraph leaving "unexpected empty space".](https://tex.stackexchange.com/questions/334246/what-does-the-phrase-underfull-hbox-badness-10000-in-paragraph-actually-mea)
=> Fix a few underfull {h,v}boxs

code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/SSP/Body.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This PR updates the Purpose of Document section of SSP to match the manual version. Part of the section was moved to the Problem Description (again to match manual).
=> SSP Purpose of Document

code/drasil-example/Drasil/GamePhysics/DataDefs.hs, code/drasil-example/Drasil/GlassBR/DataDefs.hs, code/drasil-printers/Language/Drasil/TeX/Helpers.hs, code/drasil-printers/Language/Drasil/TeX/Print.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/swhs/SRS/SWHS_SRS.tex
This PR fixes two issues pointed out through compilation of TeX. 
1. Duplicate labels in Gamephys and GlassBR.
2. External (website) references had slightly incorrect syntax and thus did not render as a link.
=> Misc TeX (Related) Fixes

code/drasil-example/Drasil/GlassBR/Assumptions.hs, code/drasil-example/Drasil/GlassBR/Unitals.hs
Because LDF was defined as both a constant and a DD in GlassBR, the generated code included this line:
`(3 / 60) ** (7 / 16) = (3 / 60) ** (7 / 16)`
Which is wrong and caused an error. The line should instead be:
`inParams.LDF = (3 / 60) ** (7 / 16)`
After removing the "constant" definition of LDF, the generated code is correct.
=> Removed constant LDF to fix error in generated code

code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-docLang/Drasil/ExtractDocDesc.hs, code/drasil-docLang/Drasil/Sections/Introduction.hs, code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SSP/Defs.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This updates how the Characteristics of Intended Reader section is built, allowing for the inclusion of topics that "would be an asset" if understood. This allowed the section in SSP to match the manual version. The change was done in such a way that the text in other examples did not change, though in the future we likely want to make this consistent between examples (issue about this on its way).
=> SSP Characteristics of Intended Reader

code/drasil-data/Data/Drasil/Concepts/Physics.hs, code/drasil-docLang/Drasil/Sections/Introduction.hs, code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GamePhysics/Concepts.hs, code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SSP/Defs.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This updates the Scope of Requirements section of SSP to match the manual version. Also adds a "2D" CI to Data.Drasil since it is now used in multiple examples and is generic.
=> SSP Scope of Requirements

code/drasil-example/Drasil/GlassBR/ModuleDefs.hs
This PR removes the symbol collision discussed in #1137 so that the Interpolation module in the generated code for glassBR compiles.
=> Fix for glassBR generated Interpolation module

code/drasil-docLang/Drasil/Sections/GeneralSystDesc.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
This updates the small paragraph at the beginning of the General System Description section of the SRS to match manual for SSP. This paragraph is common between all examples, so the change affected all examples. I think this is good, however, because the new paragraph provides the same information but is more readable and grammatically correct.
=> General System Description intro text update

code/Makefile, code/drasil-printers/Language/Drasil/Make/Print.hs
This PR adds build targets to the Makefile to build the tex for all examples. As a part of this, I added a `TEXFLAGS` variable to the Makefiles generated by Drasil which the Drasil Makefile uses to ensure a build failure doesn't halt for user input. This PR does not enable building the LaTeX during Travis builds.
=> Add tex target to Makefile

code/drasil-code/Language/Drasil/Chunk/Code.hs
This tiny PR fixes a bug where code for physical constraints was being generated twice and code for software constraints was not being generated at all.
=> Code generation - Fixing duplicate constraints

.travis.yml, code/Makefile, code/drasil-example/Drasil/GamePhysics/DataDefs.hs, code/drasil-example/Drasil/GamePhysics/Unitals.hs, code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SSP/Goals.hs
This PR does a few things:
* Fixes existing warnings
* Exposes `GHCFLAGS` in the `Makefile`
* Enables `-Wall` when building. (No new warnings were exposed by this)
* Enables `-Werror` on Travis with `-Wall`
=> Fix Warnings

code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs
This PR corrects Python ternaries in the existing GOOL implementation as indicated by #1183.
In the process of the ternary fix, I noticed the logarithm functions used in Python were incorrect and corrected ln => `math.log` and log => `math.log10`.
=> Python CodeGen Fixes

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs
This PR addresses #1184. The issue is the conditional and value assigned were incorrectly swapped in the codegen.
=> Fix conditional parameterization.

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/CodeSpec.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html
This PR restores some imports that were missing in the generated GlassBR code. The problems were:
- The procedure being called in an `FProcCall` was not being recognized as a dependency for the module
- When functions are used in definitions as `Expr`, they weren't being recognized as dependencies because they were missing the "func_" prefix.
=> Fix for missing imports in GlassBR generated code

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/CodeSpec.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html
The fix from PR #1189 was not quite right. Specifically commit b4e47481ad5806ec54eb400ea8d55550f281c292 fixed function calls defined within an `Expr`, but I didn't realize it also broke function calls defined within a `Func`.
This PR undoes commit b4e47481ad5806ec54eb400ea8d55550f281c292 and implements a new fix, which works for both cases.
=> Fix to correctly use codevar or codefunc for all expr dependencies

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-example/Drasil/GlassBR/Unitals.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html
This PR fixes the issue where Python was outputting a different value for GlassBR than Java and the other languages. The problem was the following expression in Java:
`inParams.LDF = Math.pow(3 / 60, 7 / 16);`
3 and 7 are the constants `load_dur` and `sflawParamM`, which default to `Int`s. Then the expression above does integer division, so `inParams.LDF` gets assigned the value 1.
Defining these constants as doubles fixes the issue.
=> Fixing GlassBR codegen by making constants doubles

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs
The order in which my previous PR's got merged caused codefunc to be removed from an import list when it should not have been, which means master is currently building with errors. This fixes the issue.
=> Fix for master

code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SSP/Unitals.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This PR updates the first 3 DDs in SSP. These are the ones that had multiple equations in the manual version, so I have split them up into a DD per equation as per discussion in #1174.
=> SSP DDs 1-3

code/drasil-data/Data/Drasil/Concepts/Documentation.hs, code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-docLang/Drasil/ExtractDocDesc.hs, code/drasil-docLang/Drasil/Sections/Requirements.hs
This PR sets up the DocumentLanguage to render the non-functional requirements as a formatted list, similar to the list for functional requirements (discussed in #1223). I've kept all the old functions so nothing breaks. Once we migrate all examples to using this new constructor for non-functional requirements, we can remove the old functions.
This also adds the nonFuncReqDom which will be needed to create `ConceptInstance`s out of the non-functional requirements.
=> Non-Functional Requirements as formatted lists

code/drasil-build/Build/Drasil.hs, code/drasil-build/Build/Drasil/Make/AST.hs, code/drasil-build/Build/Drasil/Make/Print.hs, code/drasil-printers/Language/Drasil/Output/Formats.hs
This PR adds smart constructors and removes the knowledge-heavy targets like Phony and TeX from drasil-build.
=> Make drasil-build More Abstract.

code/drasil-build/Build/Drasil.hs, code/drasil-build/Build/Drasil/Make/AST.hs, code/drasil-build/Build/Drasil/Make/Print.hs, code/drasil-code/Language/Drasil/Code/Code.hs, code/drasil-code/Language/Drasil/Code/CodeGeneration.hs, code/drasil-code/Language/Drasil/Code/Imperative/AST.hs, code/drasil-code/Language/Drasil/Code/Imperative/Build/AST.hs, code/drasil-code/Language/Drasil/Code/Imperative/Build/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/GOOLRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/LuaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/ObjectiveCRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs, code/drasil-code/drasil-code.cabal, code/drasil-code/stack.yaml, code/drasil-printers/Language/Drasil/Output/Formats.hs
This PR adds support to drasil-code to create a `Makefile` for each language when code for that language is generated.
Currently it only exposes a `run` target which is useless (for most languages) without a build target. The build target will be added in the next pull request.
This PR builds on #1227.
=> Add Makefile (run Target) For Generated Code

code/Makefile, code/code_build.sh
This is a small PR which adds `<example>_code` targets to the (main Drasil) Makefile to invoke the Makefile generated with each language through codegen. 
This PR does not enable code compilation in CI. That PR will occur once generated code compilation is successful on the `ll_travis_code_building` branch.
=> Add CodeGen Makefile Targets

code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs
Languages were generating "log" and "ln" for log and ln when they should generate "log10" and "log", respectively. This fixes an error with compiling the generated code so that @Mornix can continue his work.
=> Fixing code generation for log and ln

.gitignore, code/Makefile, code/check_stack.sh
This PR adds a check when any target (except `clean`) using `stack` is invoked, which detects if `stack` exists and is of at least a certain version. 
The script aims to be generally "invisible". Once a system meets our minimum version, the "result" is stored in a hidden file as a way to avoid checking every time and only when our minimum version changes. Moreover, `stack` is not checked for `clean` because we are removing files and in the likely case where someone has just downloaded the repo and doesn't have `stack` then there would be no build artifacts to delete. Finally, `clean` removes the hidden file as a way to remain true to its name and remove build artifacts.
=> Check Stack Version

code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-docLang/Drasil/Sections/SolutionCharacterSpec.hs, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Document.hs
Taking the change of section'' to section from #1262 and giving it a separate branch and PR.
section'' calls section completely reusing the parameters making it equivalent and redundant to have a separate function.
=> Removing section'' and using section.

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs
This is a small PR which (should) close #1272. I have included @bmaclach and @samm82 as reviewers to ensure that it does indeed resolve the issue on Windows.
1. I tried to be "correct" and use the `System.FilePath` provided operator `</>` to join paths when generating code Makefiles. 
2. `System.FilePath` is smart enough to know it's being compiled/run on Windows and replaces `/` path separator used on Unix with the Windows-preferred `\`. 
3. `diff` doesn't care what operating system it is running on and is just comparing text in two files.
Even though `\` is the [preferred separator](http://hackage.haskell.org/package/filepath-1.4.2.1/docs/System-FilePath-Posix.html#v:pathSeparator) on Windows, it still [supports `/`](http://hackage.haskell.org/package/filepath-1.4.2.1/docs/System-FilePat …
=> Correct Makefile diffs on Windows

code/drasil-example/Drasil/GamePhysics/DesignDec/Arbiter.hs
Very minor.
Noticed "handler" was spelled "hanlder" in 3 instances.
You would think the v_hanlderB would have broken the code but it seems like these VarChunks are not used (they are only defined.)
=> PR - Fixing spelling in GamePhysics DesignDec/Arbiter

code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SSP/Unitals.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This PR fixes a mistake in the equations for the base hydrostatic force and surface hydrostatic force (they should be multiplied by the width of a slice rather than the length of the slice base/surface). After fixing this mistake, the `surfLngth` unital and `lengthLs` DD were no longer used, so I removed them.
=> SSP Fix DD Mistake

code/drasil-data/Data/Drasil/SentenceStructures.hs, code/drasil-docLang/Drasil/DocumentLanguage/Definitions.hs, code/drasil-example/Drasil/GlassBR/DataDefs.hs, code/drasil-example/Drasil/GlassBR/IMods.hs, code/drasil-example/Drasil/NoPCM/IMods.hs, code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SSP/GenDefs.hs, code/drasil-example/Drasil/SSP/IMods.hs, code/drasil-example/Drasil/SWHS/DataDefs.hs, code/drasil-example/Drasil/SWHS/GenDefs.hs, code/drasil-example/Drasil/SWHS/IMods.hs, code/drasil-lang/Language/Drasil/Chunk/DataDefinition.hs, code/drasil-lang/Language/Drasil/Chunk/GenDefn.hs, code/drasil-lang/Language/Drasil/Chunk/InstanceModel.hs, code/stable/gamephys/Website/Chipmunk_SRS.html
As part of #947, DDs, GD, and IMs now take `[Reference]` instead of `[Citation]`, since `Reference`s are a superset of `Citation`s. (TMs already used `[Reference]` since there is a TM in an example with a `Reference` that is an external link, not a `Citation`.)
=> Switched to [Reference] for Source Fields of Chunks

code/drasil-code/Language/Drasil/Code/Imperative/Build/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/ObjectiveCRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/Parsers/ConfigParser.hs
As per #1249, fixed the "Move brackets to avoid $" in `drasil-code`.
=> [Small PR] Moved brackets to avoid $ in drasil-code

code/drasil-data/Data/Drasil/Theories/Physics.hs, code/drasil-database/Database/Drasil/ChunkDB.hs, code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-docLang/Drasil/DocumentLanguage/Definitions.hs, code/drasil-docLang/Drasil/DocumentLanguage/RefHelpers.hs, code/drasil-docLang/Drasil/ExtractDocDesc.hs, code/drasil-docLang/Drasil/TraceTable.hs, code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GamePhysics/TMods.hs, code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/GlassBR/TMods.hs, code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SSP/TMods.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/drasil-example/Drasil/SWHS/TMods.hs, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Chunk/README.md, code/drasil-lang/Language/Drasil/Document/Core.hs, code/drasil-lang/drasil-lang.cabal, code/drasil-printers/Language/Drasil/HTML/Print.hs, code/drasil-theory/Theory/Drasil.hs, code/drasil-theory/Theory/Drasil/README.md, code/drasil-theory/Theory/Drasil/Theory.hs, code/drasil-theory/drasil-theory.cabal
As per #918, `Theory` was moved to the `drasil-theory` package.
_Closes #918_
=> Moved Theory to drasil-theory

code/drasil-printers/Language/Drasil/HTML/Helpers.hs, code/drasil-printers/Language/Drasil/HTML/Print.hs, code/drasil-printers/Language/Drasil/Printing/Import.hs, code/drasil-printers/Language/Drasil/TeX/Helpers.hs, code/drasil-printers/Language/Drasil/TeX/Preamble.hs, code/drasil-printers/Language/Drasil/TeX/Print.hs
As per #1249, fixed the "Move brackets to avoid $" in `drasil-printers`.
=> [Small PR] Moved brackets to avoid $ in drasil-printers

code/Makefile, code/drasil-code/Language/Drasil/Code/Imperative/Build/AST.hs, code/scripts/ci_functions.bash, code/scripts/code_build.sh, code/scripts/log_check.sh, code/scripts/tex_build.sh, code/stable/glassbr/src/cpp/Makefile, code/stable/nopcm/src/cpp/Makefile
This PR is a fix for #1367. It ensures variables in the `Makefile` and associated shell scripts properly use quotes to avoid delimiting lists on ` `. 
In shell scripts: generally quote anything that could have a space.
In `Makefile`: quote any variable which is not defined in the `Makefile` and comes from an "external" source (ex. `MAKE`, `SHELL`.) 
Strictly speaking I'm not certain `MAKE` is strictly necessary, however it is a path so it's safer to escape it now so it is unlikely to cause problems.
Additionally, `CC` and `CXX` are also paths created by `make` so I've rolled those changes into this PR as a precaution as well.
=> Quote Variables

code/scripts/code_build.sh
This is a small PR that corrects a regression in the `code_build.sh` script which caused the mechanism used to invoke the `Makefile` in each subdirectory of `src` to fail.
=> Fix scoping of cd call in code_build.

code/Makefile, code/scripts/check_binary.sh, code/scripts/check_stack.sh
This PR makes a few tweaks to graph gen related things.
It adds a check for `dot` being installed. (Baking the solution to #1386 into the build process). It also "expands" `graphmod` to `stack exec -- graphmod` as we know we have `stack` and it is more permissive than requiring `~/.local/bin` on `PATH`.
=> Graph Checks

code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/NoPCM/DataDesc.hs, code/drasil-example/Drasil/NoPCM/GenDefs.hs, code/drasil-example/Drasil/NoPCM/Goals.hs, code/drasil-example/Drasil/NoPCM/Main.hs
Based on #1267. Removing prefixes in NoPCM to make naming more generic.
=> PR - Remove prefixes from NoPCM

code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GamePhysics/Concepts.hs, code/drasil-example/Drasil/GamePhysics/DataDefs.hs, code/drasil-example/Drasil/GamePhysics/GDef.hs, code/drasil-example/Drasil/GamePhysics/Main.hs, code/drasil-example/Drasil/GamePhysics/References.hs, code/drasil-example/Drasil/GamePhysics/TMods.hs, code/drasil-example/Drasil/GamePhysics/Unitals.hs
Based on #1267. Removing prefixes in GamePhysics to make naming more generic.
=> PR - Remove prefixes from GamePhysics

code/drasil-example/Drasil/HGHC/HGHC.hs, code/drasil-example/Drasil/HGHC/HeatTransfer.hs
Based on #1267. Removing prefixes in Tiny / HGHC to make naming more generic.
=> PR - Remove prefixes from Tiny

code/drasil-example/Drasil/NoPCM/Body.hs
Removing duplicate entries of Gen Def descriptions as per #1418. 
This will close the issue.
=> Removing Gen Def descriptions from NoPCM Body, as they are in GenDefs

code/drasil-code/Language/Drasil/CodeSpec.hs, code/drasil-example/Drasil/NoPCM/DataDesc.hs, code/drasil-example/Drasil/SSP/DataDesc.hs, code/drasil-example/Drasil/SWHS/DataDesc.hs, code/stable/nopcm/src/cpp/InputFormat.cpp, code/stable/nopcm/src/cpp/InputFormat.hpp, code/stable/nopcm/src/csharp/Control.cs, code/stable/nopcm/src/csharp/InputFormat.cs, code/stable/nopcm/src/java/SWHS/Control.java, code/stable/nopcm/src/java/SWHS/InputFormat.java, code/stable/nopcm/src/python/Control.py, code/stable/nopcm/src/python/InputFormat.py
Fixes #1179. The way we are currently set up, the function in the input format module needs to be called "get_input" because we've hardcoded a call to that function in our generate code for the Control module (ideally, we would be able to read the function name from the module and call it, but that would require some design, since there is currently no way to differentiate the InputFormat module from the other modules). Some of the examples had accidentally called the function "get_inputs" instead, so this changes those to "get_input". 
This also removes a hack where the "get_input" function was hardcoded as an export of "InputFormat". That export is read automatically from the list of modules we pass in, so the hack is not needed.
=> Input format fixes

.travis.yml, code/Makefile
This PR changes Travis to use the existing `make code` target to build generated code. I've added an extension to the code building rule which checks for NoPCM and allows failed code to "pass" for that example as there are still a few outstanding issues there for that code gen. 
I've also setup a time-bomb in the sense that when NoPCM does compile, `make code` will fail with the message:
```
NoPCM surprisingly did not fail to compile!
Failing this build because you should check the Drasil makefile and alter the code as indicated by the comment for the currently invoked target.
```
and "fails" the build. This is to ensure that when NoPCM can and does compile that to merge those changes in the `Makefile` NoPCM suppression must be removed. 
Currently to indicate that there is non-standard …
=> Travis Code Building

code/drasil-printers/Language/Drasil/HTML/Helpers.hs
Just a small naming change to keep naming more consistent throughout project.
=> PR - Small PR to rename wrapAux and wrap_genAux

.travis.yml
Quick Travis fix for HLint. Hold HLint at version 2.1.22 until their transition from HSE to ghc-lib-parser is complete and they correctly enable/disable GHC extensions.
=> Hold HLint at v2.1.22

code/drasil-example/Drasil/SWHS/Unitals.hs, code/drasil-theory/Theory/Drasil.hs, code/drasil-theory/Theory/Drasil/DataDefinition.hs
This PR replaces the old `mkQuantDef` with a new one which preserves stage-dependent symbols (previously `mkQuantDef'`). This change was discussed in #1468.
=> mkQuantDef preserves stage-dependent symbols

code/drasil-printers/Language/Drasil/Printing/Import.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
This PR updates printing of doubles such that values between 0 and 0.001 (inclusive) get printed directly, without any scientific notation. This is as discussed in https://github.com/JacquesCarette/Drasil/pull/1496#discussion_r291226461 (printing of numbers between 0 and 1000 was already how we want it, so no changes there).
=> Clearer printing of doubles

code/.hlint.yaml, code/drasil-example/Drasil/GamePhysics/DataDefs.hs, code/drasil-example/Drasil/GlassBR/TMods.hs, code/drasil-example/Drasil/NoPCM/Assumptions.hs, code/drasil-example/Drasil/NoPCM/GenDefs.hs, code/drasil-example/Drasil/NoPCM/Requirements.hs, code/drasil-example/Drasil/SWHS/GenDefs.hs, code/drasil-example/Drasil/SWHS/IMods.hs, code/drasil-example/Drasil/SWHS/Requirements.hs, code/website/site.hs
Closes #1249.
Removed all leftover redundant bracket warnings.
`.hlint.yaml` updated.
=> PR - Correcting Final Hlint warnings

code/drasil-data/Data/Drasil/Concepts/Documentation.hs, code/drasil-data/drasil-data.cabal, code/drasil-database/Database/Drasil.hs, code/drasil-database/Database/Drasil/ChunkDB.hs, code/drasil-database/drasil-database.cabal, code/drasil-docLang/Drasil/DocLang.hs, code/drasil-docLang/Drasil/Sections/TraceabilityMandGs.hs, code/drasil-docLang/drasil-docLang.cabal, code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GamePhysics/DataDefs.hs, code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/drasil-example/drasil-example.cabal, code/drasil-utils/Utils/Drasil/Misc.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
This PR introduced category filtering to traceability's matrices. As a pleasant side-effect, traceability matrices are now more ordered and maintain the order they were inserted into the `ChunkDB` when displaying in the matrix. 
I also noticed that the generated traceability matrices were displaying transposed and correct that. 
Finally, the examples (which had manual traceability matrices) had three specific traceability matrices. I extracted the captured categories each matrix was conveying and added some convenience functions to generate those as well. This means the old (probably very incorrect) manual traceability matrices were removed since they were not a help to anyone. 
One note of mention: Correctly splitting tables (such that tables do not overflow the available width) is …
=> Traceability Matrix Enhancements

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/NewCSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/NewCppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/NewJavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/NewPythonRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/New.hs, code/drasil-code/Test/FileTests.hs, code/drasil-code/Test/HelloWorld.hs, code/drasil-code/Test/Helper.hs, code/drasil-code/Test/Observer.hs, code/drasil-code/Test/PatternTest.hs
Closes #1526.
Renaming `static` to `static_` and `dynamic` to `dynamic_` wherever they occur.
=> PR - Renaming static and dynamic

code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/NewCSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/NewCppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/NewJavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/NewPythonRenderer.hs
This PR updates all of our language renderers such that, if a file's main contents are empty, the file doesn't get generated. (Previously we would still generate a file with the "top" and "bottom" portions but nothing in between, i.e. just a file with imports, which was useless).
=> Don't generate useless files

code/scripts/deploy_stage.sh
Small PR to fix a bug that turned up on/with the website as the result of #1533. The deploy process doesn't clean the "examples" directory of the existing commit when updating contents so `Projectile_SRS.*` remains in the deploy branch. This PR addresses that.
=> Correct examples not being "clean" on continuous deploy.

code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/NewCSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/NewCppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/NewJavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/NewPythonRenderer.hs
My last PR about this succeeded in making modules empty if they had no functions/classes, but I realized an empty file would still be generated. This PR makes it so that empty files do not get generated.
=> Don't generate empty files when a module is empty

code/scripts/deploy_stage.sh
This PR fixes [folder names being prepended to example names when there is a space in a folder along `$PWD`](https://github.com/JacquesCarette/Drasil/issues/1527#issuecomment-502219286) in #1527.
=> Add Missing Quotes to deploy_stage.sh

code/scripts/deploy_stage.sh
This PR addresses a small issue which arose from Stack 2.1.1. 
The deploy process queries Stack on where to locate the generated Haddock documentation so it can be copied out. This can be done with `stack path` or more specifically `stack path --local-doc-root`. 
In Stack 1.9.3 this can be thought of a `const` function in Haskell (ex. `~/.stack-work/install/x86_64-osx/lts-12.25/8.4.4/doc`). Whereas 2.1.1 makes the paths dependent on the current package (i.e. the closest `stack.yaml` located from the current folder up to the root. Part of the path now includes a hash of some "stuff" (the stuff isn't exactly important, more that it's unique value per-package) creating something such as `~/.stack-work/install/x86_64-linux/1909af6e8860c20f547661cc4672abee7bf8cf3c34948432ed2c47f65e78f513/8.4.4/ …
=> Update `stack path` in deploy to work with Stack 2.1.1.

code/scripts/deploy_stage.sh
This should really resolve docs not showing in continuous deploy. The previous PR was correct to change the path, however, Stack 2.1.1, for some unknown reason (although verified that it is actually happening by digging through the source), has two docs paths. 
Running `stack haddock` with most arguments (or absence of) usually creates the documentation in `local-doc-root`, however, if `--no-haddock-deps` is specified, haddock builds the documentation in `local-install-root`/doc. I haven't dug far enough into the Stack source to pinpoint the exact reason, but if you run `stack path` locally with Stack 2.1.1, you should see the first three entry paths include one hash, while most of the rest contain another hash. The first three are constructs based on one configuration taking constructor …
=> Update DOC_DIR to check both possible doc paths.

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/CodeSpec.hs, code/stable/glassbr/src/cpp/Control.cpp, code/stable/glassbr/src/python/Control.py, code/stable/nopcm/src/cpp/Control.cpp, code/stable/nopcm/src/csharp/Control.cs, code/stable/nopcm/src/java/SWHS/Control.java, code/stable/nopcm/src/python/Control.py
For the get_input function, I could not do all of the improvements that I've done for the other functions because, unlike the others, get_input is defined explicitly in Drasil and then passed to the code generator. Eventually we will need to generate our input format reading just from the inputs and `Choices`, because sometimes we don't even want it to be a function (for example if the `Loose` input structure is chosen), but that will be a bigger change that will come later. For now, I've made get_input consistent with the others as far as I could, which allowed me to remove the old `fApp` function and replace it with the new one.
This PR is dependent on #1556. That PR should be merged first.
=> More code generation de-hardcoding and consistency improvements

code/drasil-printers/Language/Drasil/Printing/Import.hs, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
As per #1575, the `Dbl` portion of a `Perc` is now displayed properly.
=> [Small PR] Fixed display of Perc for Expr

code/drasil-code/Language/Drasil/Code/Imperative/Helpers.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs
As suggested by @JacquesCarette in #1581, this PR replaces the pair for types in GOOL with a new data structure.
=> Implemented TypeData instead of pair for types in GOOL

code/drasil-docLang/Drasil/DocLang.hs, code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-docLang/Drasil/DocumentLanguage/Labels.hs, code/drasil-docLang/Drasil/Sections/SpecificSystemDescription.hs, code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
In the same vein as #1600, the Physical System Description section is now automated in `docLang`.
=> Automate Physical System Description

code/scripts/deploy.bash
Ensure deploy folder doesn't exist before attempting repository clone.
=> Deploy Folder Removal Fix

code/drasil-lang/Language/Drasil/Symbol.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
This PR addresses some inconsistency when sorting (discovered making innocuous changes on a yet-unpushed branch) where sorting of symbols could change (in the bad way, not the stable sort way) when un-equal items in the input list were in a different order. 
This PR also slightly altered the behaviour of symbol sorting such that having symbols v<sub>i</sub>, v<sub>f</sub><sup>AB</sup>, and v<sub>f</sub> would be sorted as: 
v<sub>f</sub>, v<sub>f</sub><sup>AB</sup>, v<sub>i</sub> instead of the current
v<sub>f</sub>, v<sub>i</sub>, v<sub>f</sub><sup>AB</sup>
If this is an undesirable change, I can back it out.
This PR also spurred two issues involving Symbols: #1605 and #1606.
=> Symbol Sorting Fixes

code/drasil-docLang/Drasil/ExtractDocDesc.hs, code/drasil-docLang/drasil-docLang.cabal, code/stack.yaml
This PR adds the infrastructure for a multiplate of `DocDesc` in docLang. Currently, it is used for the `cigetDocDesc`, `egetDocDesc`, and `getDocDesc` docLang passes. 
The plate infrastructure (and few configurable plates — ie. `secConPlate` and `sentencePlate`) should ideally lower the effort required to add new passes and further increase consistency within docLang.
=> Introduce Multiplate for DocDesc

code/drasil-code/Language/Drasil/Code/Code.hs, code/drasil-code/Language/Drasil/Code/Imperative/Helpers.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/Symantics.hs, code/drasil-code/Test/FileTests.hs, code/drasil-code/Test/HelloWorld.hs, code/drasil-code/Test/Helper.hs, code/drasil-code/Test/Observer.hs, code/drasil-code/Test/PatternTest.hs
This PR addresses #496 by updating the data structure for `Value`s in GOOL to hold information about the value's type.
This change affords us many opportunities for clean-up (i.e. with functions that take a type as a parameter that now may not need to because they can extract the type from the value), most of which I haven't pursued for now, just because this PR is big enough as it is. This PR does just enough to get things to compile, and #1611 will remind me to go back and find places that can now be cleaned up.
=> GOOL Values hold type information

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/Symantics.hs, code/drasil-code/Test/FileTests.hs, code/drasil-code/Test/HelloWorld.hs, code/drasil-code/Test/Helper.hs, code/drasil-code/Test/Observer.hs, code/drasil-code/Test/PatternTest.hs
This PR updates the GOOL constructor for modules to not take a list of `Statement`s, which closes #1517.
=> Remove Statements from GOOL Modules

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs
Small PR that closes #1635 by reformatting the log messages for a function call in generated code.
=> Reworked log message for function call

code/drasil-example/Drasil/NoPCM/GenDefs.hs, code/drasil-example/Drasil/SWHS/GenDefs.hs
Closes #1409 and closes #1417.
Renaming of derivation sentences and equations in SWHS and NoPCM GenDefs. Old names were hardcoded and non-meaningful.
=> PR - More useful names in SWHS and NoPCM GenDefs

code/scripts/deploy_stage.sh
This is a small PR relating to a bad way to capture path information I suggested in #1653. The path I suggested works in a staged deploy, but a real deploy has the `deploy` folder as a git repo which is what `rev-parse` picks up. This corrects that oversight. 
This PR addresses the build failure of `master` which only failed due to the deploy failure and not a code failure. Subsequent commits to `master` will pass regardless of other (passing) merges, however deploys will fail until this PR is merged.
=> Deploy Fix

code/drasil-example/Drasil/GlassBR/Unitals.hs
This tiny PR closes #1682 by building the `constrained` list in GlassBR from the `inputDataConstraints` list. 
(Yay, a PR that doesn't depend on any others!)
=> Consistent constraint lists in GlassBR

code/drasil-docLang/Drasil/DocumentLanguage/TraceabilityMatrix.hs
This PR is a tiny tweak. It alters the behaviour of the traceability matrix to not take quite everything from `ChunkDB`. Only those which appear in the SRS itself. As you may notice, no stable changes. That's because we use everything in the `ChunkDB`. This is more an "in case" for the future if something is filtered to not be included in the SRS then it will also not show in the traceability matrix.
=> Traceability Matrix Showed Items Tweak

code/drasil-code/Language/Drasil/Code/Imperative/Helpers.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/stable/glassbr/src/cpp/InputConstraints.hpp, code/stable/glassbr/src/cpp/InputParameters.hpp, code/stable/glassbr/src/csharp/InputConstraints.cs, code/stable/glassbr/src/csharp/InputParameters.cs, code/stable/glassbr/src/java/GlassBR/InputConstraints.java, code/stable/glassbr/src/java/GlassBR/InputParameters.java, code/stable/glassbr/src/python/InputConstraints.py, code/stable/glassbr/src/python/InputParameters.py
This PR closes #1719 by generating strings for Doxygen descriptions that never reference anything if that thing is not present (i.e. derived values, constraints, inputs, outputs)
=> De-hardcode Doxygen Descriptions

code/drasil-example/Drasil/GamePhysics/References.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html
Closes #1722.
The cause of the HTML double period was due to a period appearing in the string in `References.hs`.
The HTML version probably adds a period after the title field, hence the double period.
The Latex seems to realize there is a period and not add another. But when a period is not present, Latex will render a new period outside of the quotations in the PDF. The original appeared within the quotations, which was inconsistent with the rest.
=> PR - Removing double period from GamePhysics References

code/drasil-code/Language/Drasil/Code/Imperative/Helpers.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-utils/Utils/Drasil.hs, code/drasil-utils/Utils/Drasil/English.hs
This is a small PR that moves the `stringList` function to Utils.Drasil.English based on feedback on #1725
=> Moved stringList helper function to utils

code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/Symantics.hs, code/drasil-code/Test/FileTests.hs
This PR closes #1688 by separating many of GOOL's functions into "Internal" classes that do not get exported from the drasil-code subpackage.
=> Separating out internal GOOL functions

code/drasil-code/Language/Drasil/Code/CodeGeneration.hs, code/drasil-code/Language/Drasil/Code/Imperative/Build/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Data.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/Symantics.hs, code/drasil-code/Test/Main.hs
This PR closes #1745, updating GOOL to construct file paths for the files it generates, and removing some checks for specific languages in our generator.
=> Construct file paths within GOOL

code/drasil-lang/Language/Drasil/Expr.hs
Small PR that adds comparison of completeness to equality checks for case expressions, as suggested by https://github.com/JacquesCarette/Drasil/pull/1741#commitcomment-34400136.
=> Compare completeness for case expressions

.gitignore
Minor update so that `.gitignore` ignores generated `.fls` and `.fdb_latexmk` files.
=> PR - Updating .gitignore

code/drasil-code/Language/Drasil/Code/Imperative/Build/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Data.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs
Now that GOOL constructs file paths (#1747), old code for getting file extensions and passing them around various functions was now obsolete and/or redundant. This PR cleans this code up so that file extensions are defined once in GOOL and thereafter read from file paths rather than passed as parameters.
=> Clean up code related to file extensions

code/drasil-code/Language/Drasil/Code.hs, code/drasil-code/Language/Drasil/Code/Imperative/Build/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Data.hs, code/drasil-code/Language/Drasil/Code/Imperative/Doxygen/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/Symantics.hs, code/drasil-code/Test/FileTests.hs, code/drasil-code/Test/HelloWorld.hs, code/drasil-code/Test/Main.hs, code/drasil-code/Test/PatternTest.hs
Auxiliary files like the doxygen config need to know the finalized list of code files in the `Package`. Previously the list passed in to the `package` function was not final -- the function filtered and sometimes modified the list. This led me to create the `packDox` function which builds the auxiliary doxygen config file at the same time as the package. It wouldn't be feasible to continue creating similar functions for every type of auxiliary file we generate, so this PR adds a `ProgramSym` typeclass where code files get finalized/bundled before getting passed to `package`, removing the need for specialized functions like `packDox`.
=> Add ProgramSym typeclass to GOOL

code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs
This small PR fixes a bug where inline if statements in GOOL weren't getting assigned a precedence in some cases, causing some necessary parentheses to get left out. It didn't affect any of our current examples but was caught by a test.
=> Fix missing parentheses with inline if statements

.travis.yml, code/Makefile, code/drasil-code/Language/Drasil/Code/Imperative/Doxygen/Import.hs, code/scripts/code_build.sh, code/scripts/deploy_stage.sh, code/stable/glassbr/src/cpp/doxConfig, code/stable/glassbr/src/csharp/doxConfig, code/stable/glassbr/src/java/doxConfig, code/stable/glassbr/src/python/doxConfig, code/stable/nopcm/src/cpp/doxConfig, code/stable/nopcm/src/csharp/doxConfig, code/stable/nopcm/src/java/doxConfig, code/stable/nopcm/src/python/doxConfig, code/stable/projectile/src/cpp/doxConfig, code/stable/projectile/src/csharp/doxConfig, code/stable/projectile/src/java/doxConfig, code/stable/projectile/src/python/doxConfig, code/website/site.hs
This PR improves some Doxygen stuff from a build perspective.
This PR addresses Doxygen 404ing on deploy's due to the full path (i.e. /home/travis/JacquesCarette/Drasil/...) and messing with the path when combined with a web URL.
This PR adds the Makefile target `doxygen` to build the doxygen of all examples. We also build the Doxygen in all CI builds now. 
Finally, I've modified the Doxygen config to make the Doxygen output less verbose (@bmaclach) as we compile a lot of Doxygen and I'm trying to keep the number of lines for a full build in Travis <10k to avoid truncation.
=> Doxygen Build Improvements

code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/PythonRenderer.hs, code/stable/glassbr/src/csharp/Interpolation.cs, code/stable/glassbr/src/python/Interpolation.py
This is a quick fix for try catch statements generated by GOOL to not assign the caught exception to a variable. This way compilers won't throw warnings when the variable isn't used, as discussed in #1675.
Now our examples run with no warnings 😄 
Note that Java requires the variable be assigned, but it doesn't throw a warning if it goes unused, so that should be okay.
=> Try catch fix to remove warnings

code/drasil-data/Data/Drasil/Concepts/Physics.hs, code/drasil-data/Data/Drasil/Quantities/Physics.hs
Added momentum in physics.hs. This will be required in some GDefs in other PRs coming soon.
Note: It will not be displayed in Table of Symbols (.html doc) yet, since it hasn't been used anywhere in GamePhysics SRS.
Please review changes in code.
=> Added momentum to physics.hs to be used later in GamePhysics

code/drasil-docLang/Drasil/Sections/Introduction.hs, code/stable/gamephysics/SRS/GamePhysics_SRS.tex, code/stable/gamephysics/Website/GamePhysics_SRS.html, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/projectile/SRS/Projectile_SRS.tex, code/stable/projectile/Website/Projectile_SRS.html, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
This updates the intro text that referred to "scope of the system" to instead refer to "scope of the requirements", closing #1892.
=> Consistently say "scope of the requirements"

code/drasil-data/Data/Drasil/Citations.hs, code/drasil-data/Data/Drasil/Concepts/Physics.hs, code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GamePhysics/References.hs, code/stable/gamephysics/SRS/GamePhysics_SRS.tex, code/stable/gamephysics/Website/GamePhysics_SRS.html
Files updated:
drasil-data/Data/Drasil/Citations.hs
drasil-data/Data/Drasil/Concepts/Physics.hs
drasil-example/Drasil/GamePhysics/Body.hs
drasil-example/Drasil/GamePhysics/References.hs
stable/gamephysics/SRS/GamePhysics_SRS.tex
stable/gamephysics/Website/GamePhysics_SRS.html
Damping is now listed in Terminologies and definition section, with the wiki source
=> Added damping to terminology and definition section

code/drasil-data/Data/Drasil/Concepts/Math.hs, code/drasil-data/Data/Drasil/Concepts/Physics.hs, code/drasil-data/Data/Drasil/Quantities/Physics.hs, code/stable/gamephysics/SRS/GamePhysics_SRS.tex, code/stable/gamephysics/Website/GamePhysics_SRS.html
Added Moment.hs in physics.hs
In this PR, I also added 'axis' in maths.hs as I noticed it's not defined anywhere in Drasil.
@bmaclach, you can use 'moment' after this PR is merged.
Torque = Moment?
=> Moment and axis added to Drasil

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs, code/drasil-gool/Test/HelloWorld.hs
Another small GOOL PR. Changes some functions that took a `Label` to instead take a full `Variable`. 
The reason for this is that some functions (like `forEach`) that took a `Label` instead of a full `Variable` were originally intended to save the user the trouble of defining the full `Variable`, but really they will need to define the full `Variable` anyway (for example, when the variable is used in the body of the `forEach`), so having to pass the `Label` is not any more efficient and actually makes things inconsistent because the user would have to remember where they need to use a full `Variable` and where to just use a `Label`.
=> Update functions to take variables instead of labels

code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs, code/drasil-gool/Test/PatternTest.hs
Small PR that renames some GOOL functions that were poorly named and removes a couple that were not used and served no purpose.
=> Renamed misleading GOOL functions and removed unused functions

code/drasil-code/Language/Drasil/Code/Imperative/FunctionCalls.hs, code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Logging.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-gool/GOOL/Drasil.hs, code/drasil-gool/GOOL/Drasil/Helpers.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs, code/drasil-gool/Test/FileTests.hs, code/drasil-gool/Test/HelloWorld.hs, code/drasil-gool/Test/Helper.hs, code/drasil-gool/Test/Observer.hs, code/drasil-gool/Test/PatternTest.hs
In this PR:
- Renaming more things. A lot of GOOL functions/types had "state" in the name which I never really understood before but I now think was a relic of GOOL's original focus on state machines, and so I am now giving better names to these things
- Updating functions for generating methods/functions to take a `Type` instead of a `MethodType`. The `MethodType` distinction is useful, but only internally, so there's no need to expose it and complicate the user-facing interface of GOOL.
=> More minor GOOL improvements

code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs
Tiny PR which removes a no longer needed parameter from `forEachDocD`, enabled because we now pass a full variable to `forEach` instead of just a label.
=> Minor simplification for forEachDocD

code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs
Another small PR improving GOOL by removing the `includeScope` function because it was complicating the code without actually being useful.
=> Remove includeScope

code/drasil-docLang/Drasil/Sections/Requirements.hs, code/drasil-docLang/Drasil/Sections/SpecificSystemDescription.hs, code/drasil-example/Drasil/GamePhysics/DataDefs.hs, code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/Projectile/IMods.hs, code/drasil-example/Drasil/SSP/TMods.hs, code/drasil-example/Drasil/SWHS/IMods.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-printers/Language/Drasil/Printing/Import.hs, code/drasil-printers/Language/Drasil/TeX/Print.hs, code/drasil-utils/Utils/Drasil/Misc.hs
This PR addresses some new warnings uncovered with the latest version of HLint, uncovered while running on CI. 
Most of these changes relate to using Bifunctors on Tuples and removing newly detected instances of extraneous brackets.
=> Correct HLint Suggestions

code/drasil-code/Language/Drasil/Code.hs, code/drasil-code/Language/Drasil/Code/Imperative/Doxygen/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/PythonRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/Symantics.hs, code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Language/Drasil/Code/Imperative/Generator.hs, code/drasil-code/Language/Drasil/Code/Imperative/State.hs, code/drasil-code/Language/Drasil/CodeSpec.hs, code/drasil-example/Drasil/GamePhysics/Main.hs, code/drasil-example/Drasil/GlassBR/Main.hs, code/drasil-example/Drasil/HGHC/Main.hs, code/drasil-example/Drasil/NoPCM/Main.hs, code/drasil-example/Drasil/Projectile/Main.hs, code/drasil-example/Drasil/SSP/Main.hs, code/drasil-example/Drasil/SWHS/Generate.hs
This PR closes #1871 by adding a `Choice` for the verbosity of Doxygen's output when building the PDFs. It is currently set to `QUIET` for all examples so our Travis logs don't get too big.
=> Choice for Doxygen output verbosity

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/CodeSpec.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs
I noticed some issues when the `Bundled` and `Combined` options were both chosen. This PR fixes some of the issues:
- Fixes dependency map to not have module dependent on itself (which was causing self-import statements)
- Separates `classVar` into `classVar` and `extClassVar` to correctly handle situation of accessing variable from class where the class is in the same module as the code for accessing
- Changes modules so classes come first, which was causing errors in C++
None of our current examples use this combination of choices, which is why I didn't notice these before (and why there are no changes to stable). There are still more problems with this choice combination, but I'm going to create a separate issue (Edit: #1952 created).
=> Fixes for Bundled + Combined choice combination

code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/stable/glassbr/src/java/GlassBR/Interpolation.java, code/stable/glassbr/src/java/GlassBR/ReadTable.java
This PR updates GOOL's java renderer to print lists simply by passing the list to Java's basic print function, contributing to #1940. The loop structure used previously is not actually needed in Java.
=> Improve list printing in Java

code/drasil-code/Language/Drasil/Code/Imperative/Comments.hs, code/drasil-code/Language/Drasil/Code/Imperative/Descriptions.hs, code/drasil-code/Language/Drasil/Code/Imperative/FunctionCalls.hs, code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Language/Drasil/Code/Imperative/Generator.hs, code/drasil-code/Language/Drasil/Code/Imperative/Helpers.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Logging.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-code/Language/Drasil/Code/Imperative/Parameters.hs, code/drasil-code/Language/Drasil/Code/Imperative/State.hs, code/drasil-gool/GOOL/Drasil.hs, code/drasil-gool/GOOL/Drasil/Data.hs, code/drasil-gool/GOOL/Drasil/Helpers.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/State.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs, code/drasil-gool/Test/FileTests.hs, code/drasil-gool/Test/HelloWorld.hs, code/drasil-gool/Test/Helper.hs, code/drasil-gool/Test/Main.hs, code/drasil-gool/Test/Observer.hs, code/drasil-gool/Test/PatternTest.hs
This PR splits `MethodState` off of `GOOLState`, where `MethodState` holds state that is local to `Method`s. We use `zoom` to lift `State GOOLState` type values to `State (GOOLState, MethodState)` type values, and also to lift `State (GOOLState, MethodState)` type values back into `State GOOLState` type values. Which means I had to build lenses going both ways, and to get from `State GOOLState` to `State (GOOLState, MethodState)` the lens is sort of backwards -- it "focuses in" on something even bigger than what it starts with, which sounds impossible, but works because when we need to lift "something" without `MethodState` into a computation with `MethodState` we can just initialize the `MethodState` for the "something" however we want, because it doesn't actually care what its …
=> Zoom into and out of MethodState

code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Language/Drasil/Code/Imperative/Generator.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-gool/GOOL/Drasil.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/State.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs, code/drasil-gool/Test/Helper.hs, code/drasil-gool/Test/Observer.hs
This PR splits some more state off of `GOOLState` into a new local state type, `FileState`. `GOOLState` now contains only fields that apply globally to the `Program`, all local state has been separated.
=> Add local FileState to GOOL

code/drasil-gool/GOOL/Drasil/Helpers.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs
This PR updates various functions to be in the `repr` context, avoiding the need for the renderers to have to lift the functions to work on their parameters, which should make the renderers more readable.
=> Update functions to reduce amount of lifting in GOOL's renderers

code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-gool/GOOL/Drasil/Helpers.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/State.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs
This PR makes GOOL `Parameter`s stateful, where during the state transition an error is thrown if multiple parameters for a given function are the same. This was previously handled by a `checkParams` function, but now that it is handled by State, it enabled some simplifications to the messy `intMethod` and `intFunc` function implementations in the renderers.
@JacquesCarette I discovered while working on this that if the source and header instances of a GOOL function just call other GOOL functions exactly the same way, our `Pair` instance for that function can just do those calls directly, instead of breaking down the pair, dispatching to the two instances, and then putting the results back together in a pair. For example, both instances of `docInOutFunc` are defined as `docInOutFunc n = …
=> Add State to Parameters in GOOL

code/drasil-code/Language/Drasil/Code/Imperative/ConceptMatch.hs, code/drasil-code/Language/Drasil/Code/Imperative/FunctionCalls.hs, code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Language/Drasil/Code/Imperative/Generator.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Logging.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-gool/GOOL/Drasil.hs, code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/Helpers.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/State.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs, code/drasil-gool/Test/FileTests.hs, code/drasil-gool/Test/HelloWorld.hs, code/drasil-gool/Test/Helper.hs, code/drasil-gool/Test/Main.hs, code/drasil-gool/Test/Observer.hs, code/drasil-gool/Test/PatternTest.hs, code/drasil-gool/drasil-gool.cabal
While implementing the automation of the generation of import statements, I discovered I needed an information collection pass for C++ so that we can determine which objects have a type that needs to be imported from another module.
This PR adds the infrastructure for an information collection pass in GOOL. Currently it just creates a map from module names to class names, but we can add to the `CodeInfo` interpretation to store more information as we need it. The pass is also written generically, so the collected information is available to all language renderers.
The actual implementation of automated import statements isn't here, that will be in the next PR.
=> Information collection pass in GOOL

code/drasil-theory/Theory/Drasil/DataDefinition.hs, code/stable/glassbr/src/cpp/InputParameters.hpp, code/stable/glassbr/src/csharp/InputParameters.cs, code/stable/glassbr/src/java/GlassBR/InputParameters.java
I noticed one of GlassBR's variables had type `double` when it was supposed to be `int`. Traced it back to `mkQuantDef`, which was overwriting all types to be `Real`.
=> mkQuantDef fix

code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/Helpers.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/State.hs
This does some small clean-up/simplifications in GOOL:
- Replacing the sequence of `get` then `put` for a `State` monad with `modify`, a built-in function that does `get` and `put`. 
- Replacing `stateFromData ... Semi` with `mkSt` and `stateFromData ... Empty` with `mkStNoEnd`
- Reformat C++ pair instance for better readability
- Use `<$>` and `<*>` for lifts when there are more than 3 parameters
=> GOOL Cleanup

code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-gool/GOOL/Drasil.hs, code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/State.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs, code/drasil-gool/Test/Observer.hs
This PR adds `ClassState` to GOOL, which stores the current class name. A whole bunch of functions required the class name to be passed as a parameter, but now it can just be read from the state.
=> GOOL Class state

code/drasil-code/Language/Drasil/Code/Imperative/Parsers/ConfigParser.hs
Fixes the HLint errors causing current builds to fail.
=> Use fmap instead of liftM, fixes HLint errors

code/Makefile
On windows machines, depending on settings, building will generate a lot of non-empty log files because of the additional carriage return at the end of lines.
=> Fix diff tool when used on machines that use CRLF line endings

code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/Data.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/State.hs, code/stable/glassbr/src/java/GlassBR/Calculations.java, code/stable/glassbr/src/java/GlassBR/Control.java, code/stable/glassbr/src/java/GlassBR/DerivedValues.java, code/stable/glassbr/src/java/GlassBR/InputConstraints.java, code/stable/glassbr/src/java/GlassBR/InputFormat.java, code/stable/glassbr/src/java/GlassBR/Interpolation.java, code/stable/glassbr/src/java/GlassBR/OutputFormat.java, code/stable/glassbr/src/java/GlassBR/ReadTable.java, code/stable/nopcm/src/java/SWHS/Control.java, code/stable/nopcm/src/java/SWHS/InputParameters.java, code/stable/nopcm/src/java/SWHS/OutputFormat.java, code/stable/projectile/src/java/Projectile/Calculations.java, code/stable/projectile/src/java/Projectile/Control.java, code/stable/projectile/src/java/Projectile/InputParameters.java, code/stable/projectile/src/java/Projectile/OutputFormat.java
This PR updates GOOL's Java renderer so that we no longer generate "throws Exception" for every single method. Instead we use state to keep track of which exceptions are thrown by a given function, and declare only those that we need.
This change was necessary for my work on ODE solvers to compile, which is why I'm doing it now.
=> Automate "throws Exception" in Java

code/drasil-code/Language/Drasil/Code/Imperative/ConceptMatch.hs, code/drasil-code/Language/Drasil/Code/Imperative/FunctionCalls.hs, code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Logging.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-gool/GOOL/Drasil.hs, code/drasil-gool/GOOL/Drasil/Helpers.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/State.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs, code/drasil-gool/Test/Observer.hs, code/drasil-gool/Test/PatternTest.hs, code/drasil-gool/Test/SimpleODE.hs
This PR updates GOOL's C++ renderer to use state to detect when there are statements in a constructor body that can be replaced with an initializer list. I first needed to add a new level of local state, `ValueState`. When a constructor includes an assignment where the left side is a state variable and the right side is an expression where any variable in the expression is a parameter of the constructor, then instead of printing out the statement normally we add it to the initializer list. With initializer lists built in to the renderer now, the C++ ODE implementation was simplified somewhat.
This PR closes #1991.
=> Initializer lists in GOOL

code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/CodeType.hs, code/drasil-gool/GOOL/Drasil/Data.hs, code/drasil-gool/GOOL/Drasil/Helpers.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs
This PR adds a `lambda` function to GOOL for generating anonymous functions, which simplifies `solveODE` for Python and C# somewhat.
=> Implement lambda functions in GOOL

code/drasil-example/Drasil/Projectile/Main.hs
This PR does the change requested in https://github.com/JacquesCarette/Drasil/pull/2015#commitcomment-37442740, using record syntax to more concisely define multiple `Choices` structures for Projectile.
=> Record syntax for building choices for projectile

code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs
This PR contributes to #2008. I know this is likely to require further changes, but wanted to get this in as a foundation for further discussion.
Specifically, it was discussed in the issue creating new GOOL classes to hold these new methods, and then not implementing those classes for languages that don't support named arguments, but I have not done that yet because we want Drasil's generator to be fully language-generic, and adding user-facing classes that may not be implemented by some languages would exclude those languages as possible instances of the generic `repr` in GOOL's generator.
=> Add GOOL methods for calling functions with named arguments

code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/CodeSpec.hs, code/drasil-code/Language/Drasil/Mod.hs, code/drasil-example/Drasil/GlassBR/ModuleDefs.hs, code/drasil-example/Drasil/GlassBR/Symbols.hs
This PR adds some new nodes to the `Mod` AST for classes, constructors, and accessing object fields, and added an imports parameter at the module level, all of which are needed for implementing external libraries.
This PR is not dependent on the others. Safe to merge!
=> Extend Mod for ExternalLibrary

code/drasil-code/Language/Drasil/Code/Code.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/ReadInput.hs, code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/CodeType.hs, code/drasil-gool/GOOL/Drasil/Helpers.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs
This PR changes GOOL to distinguish between floats and doubles, so GOOL is now ready to handle the implementation of a floats vs. doubles choice (#1863). For now, we just render everything as doubles, which is what we were doing before, so there are no changes to stable.
=> GOOL Doubles

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs
Some updates to GOOL needed for external libraries, like list- and array-typed literal values and making `listAccess` work on both lists and arrays. Also uses these new GOOL methods to implement the translator for `Matrix` `Expr`s in Drasil.
=> GOOL List/Array updates

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/State.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs
This small PR adds some GOOL methods for calling functions from external libraries (as opposed to the existing `extFuncApp` etc. which are for calling functions from external modules within the same program or package). These are needed for generating external library code.
#2038 should be merged first. The only new commit is 3e96d6c.
=> GOOL methods for calling library functions

code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs, code/drasil-gool/Test/HelloWorld.hs
We used `&~-` for GOOL's decrement operator because the more intuitive `&--` could not be used because `--` starts a comment in Haskell. However I've recently discovered this is not true. Haskell allows using `--` in an operator, so I changed the operator to use this better symbol.
=> Change decrement operator to use -- instead of ~-

code/drasil-code/Language/Drasil/Chunk/Code.hs, code/drasil-code/Language/Drasil/Chunk/CodeDefinition.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-code/Language/Drasil/Code/Imperative/Parameters.hs, code/drasil-code/Language/Drasil/CodeSpec.hs
Another small PR, removing constructors that are no longer needed now that `QuantityDict` is the underlying type for `CodeChunk`s.
=> Remove codevarC and codefuncC 

code/drasil-code/Language/Drasil/Code/Imperative/Comments.hs, code/drasil-code/Language/Drasil/Code/Imperative/FunctionCalls.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/CodeSpec.hs, code/drasil-code/Language/Drasil/Mod.hs, code/drasil-example/Drasil/GamePhysics/Body.hs
This PR cleans up `CodeSpec` by:
- removing the `rels` field, which was simply not used.
- removing the variable map and function map (`vMap` and `fMap`), which were used only once or twice and only seemed to over-complicate the code, without really having a benefit that I could see. I think they probably made sense when I started, but I've made so many changes to the generator since then that they no longer seem useful.
=> Clean unnecessary fields of CodeSpec

code/drasil-code/Language/Drasil/Code/Imperative/Descriptions.hs, code/drasil-code/Language/Drasil/Code/Imperative/Generator.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-code/Language/Drasil/CodeSpec.hs, code/drasil-code/Language/Drasil/Mod.hs, code/stable/glassbr/src/cpp/Makefile, code/stable/glassbr/src/cpp/doxConfig, code/stable/glassbr/src/csharp/Makefile, code/stable/glassbr/src/csharp/doxConfig, code/stable/glassbr/src/java/Makefile, code/stable/glassbr/src/java/doxConfig, code/stable/glassbr/src/python/Makefile, code/stable/glassbr/src/python/doxConfig, code/stable/projectile/Projectile_C_P_NoL_B_U_V_D/src/cpp/Makefile, code/stable/projectile/Projectile_C_P_NoL_B_U_V_D/src/cpp/doxConfig, code/stable/projectile/Projectile_C_P_NoL_B_U_V_D/src/csharp/Makefile, code/stable/projectile/Projectile_C_P_NoL_B_U_V_D/src/csharp/doxConfig, code/stable/projectile/Projectile_C_P_NoL_B_U_V_D/src/java/Makefile, code/stable/projectile/Projectile_C_P_NoL_B_U_V_D/src/java/doxConfig, code/stable/projectile/Projectile_C_P_NoL_B_U_V_D/src/python/Makefile, code/stable/projectile/Projectile_C_P_NoL_B_U_V_D/src/python/doxConfig, code/stable/projectile/Projectile_S_L_NoL_U_U_V_F/src/cpp/Makefile, code/stable/projectile/Projectile_S_L_NoL_U_U_V_F/src/cpp/doxConfig, code/stable/projectile/Projectile_S_L_NoL_U_U_V_F/src/csharp/Makefile, code/stable/projectile/Projectile_S_L_NoL_U_U_V_F/src/csharp/doxConfig, code/stable/projectile/Projectile_S_L_NoL_U_U_V_F/src/java/Makefile, code/stable/projectile/Projectile_S_L_NoL_U_U_V_F/src/java/doxConfig, code/stable/projectile/Projectile_S_L_NoL_U_U_V_F/src/python/Makefile, code/stable/projectile/Projectile_S_L_NoL_U_U_V_F/src/python/doxConfig
For some reason the Calculations module was generated by first defining a `Mod` containing various calculation functions, whereas most of our other modules do not have this intermediate `Mod` representation. I couldn't find a good reason why the Calculations module was treated differently, and in fact treating it this way makes things less flexible (it forces each calculation to be in its own function, so it wouldn't be possible to later have a fully unmodular choice where everything is all in one function). So I fixed this so that Calculations is treated like the other modules we generated, then removed the `FCD` node from `Func` altogether, because it is no longer used or needed.
I also fixed a minor bug where the class definition map and module export map weren't being completely …
=> Generator improvements

code/drasil-gool/GOOL/Drasil/AST.hs, code/drasil-gool/GOOL/Drasil/CodeAnalysis.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs
Based on code review meeting on April 3rd, removing `Doc` from the end of some functions. (and also changing on catch-all clause to not be a catch-all).
=> Remove doc

code/drasil-gool/GOOL/Drasil/Helpers.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/RendererClasses.hs
Closes #1942.
This PR removes the `KeywordSym` type class mostly by removing the methods it contained. A lot of the methods were only used once or not at all, so they made sense to remove. Others (like `endStatement`, for instance) were used many times but were so simple (just a concrete `Doc`) that putting them in a type class and having to wrap them in a `repr` made the code far more complicated than it needed to be, so I removed those too, and instead defined them as regular functions in `LanguageRenderer.hs`. Only the `implements` and `inherit` methods still made sense to keep, so I moved those to the `InternalClass` type class.
=> Remove KeywordSym

code/drasil-gool/GOOL/Drasil/State.hs
Addresses the comment on #2053, using `set` instead of `initialS {_state = s}` pattern.
=> Use set instead of record syntax

code/drasil-gool/GOOL/Drasil/ClassInterface.hs, code/drasil-gool/Test/Observer.hs, code/drasil-gool/Test/PatternTest.hs, code/drasil-gool/Test/SimpleODE.hs
@JacquesCarette I've taken a  half-measure here because I have questions.
Removing constraints from the GOOL class hierarchy like we talked about in today's code review meeting will have the consequence of needing to specify more constraints where the methods are used. For example, if `AssignStatement` is no longer a constraint in the GOOL class hierarchy, it would mean that throughout Drasil's generator, we would have to add the `AssignStatement repr` constraint to any function that does an assignment. Currently the only constraint we need is `ProgramSym repr`, which is essentially a catch-all constraint, but with this change the generator would become cluttered with constraints.
So the half-measure I've taken is to remove unnecessary constraints in the hierarchy, but then add them all …
=> Remove some constraints from GOOL class hierarchy

code/drasil-code/Language/Drasil/Code/Imperative/ConceptMatch.hs, code/drasil-code/Language/Drasil/Code/Imperative/FunctionCalls.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/ClassInterface.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Language/Drasil/Code/Imperative/Generator.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Logging.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-gool/GOOL/Drasil.hs, code/drasil-gool/GOOL/Drasil/ClassInterface.hs, code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/Helpers.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/RendererClasses.hs, code/drasil-gool/Test/FileTests.hs, code/drasil-gool/Test/HelloWorld.hs, code/drasil-gool/Test/Helper.hs, code/drasil-gool/Test/Main.hs, code/drasil-gool/Test/Observer.hs, code/drasil-gool/Test/PatternTest.hs, code/drasil-gool/Test/SimpleODE.hs
This PR abbreviates GOOL in various ways:
- Introducing type synonyms for repeated type patterns
- Shortening `repr` type variable to `r`
- Using `>>` instead of `_ <-`
Based on discussion from the April 14th GOOL code review meeting.
=> Abbreviations throughout GOOL

code/drasil-gool/GOOL/Drasil/CodeAnalysis.hs, code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/State.hs
CodeInfo had some Java-specific exception definitions. This PR adds an `ExceptionType` type to represent exceptions in a language-independent way, and a class for mapping an `ExceptionType` to the language specific `Exception`. The `CodeInfo` pass then uses `Exception` type so it is fully language-generic, and the Java renderer has an instance of the new class to translate that to concrete exception declarations in Java.
=> Make CodeInfo fully generic

code/drasil-code/Language/Drasil/Code.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Mod.hs, code/drasil-example/Drasil/GlassBR/ModuleDefs.hs, code/stable/glassbr/src/cpp/Interpolation.cpp, code/stable/glassbr/src/csharp/Interpolation.cs, code/stable/glassbr/src/java/GlassBR/Interpolation.java
The generator automatically generates any needed function declarations for modules defined with `FuncStmt`s, so it did not make sense to have a node in `FuncStmt` for declaration statements. This node was only being used in places where what was really intended was not just declaring a variable, but also assigning an empty list to it, so the `FDecDef` node is more appropriate to use in those cases. So I switched those to use `FDecDef`, and then removed `FDec`. 
While I was at it, I updated the generator to put the automatically-generated declaration statements for each function into their own block, resulting in some (expected) new-lines added to stable.
=> Remove FDec node of FuncStmt

code/drasil-code/Language/Drasil/Code/ExternalLibrary.hs, code/drasil-code/Language/Drasil/Code/Imperative/Descriptions.hs, code/drasil-code/Language/Drasil/Code/Imperative/FunctionCalls.hs, code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-code/Language/Drasil/Mod.hs
This PR improves the generator in 3 minor ways:
- Re-orders parameters to some functions to be more consistent with other functions
- Set the `currentClass` field of the `DrasilState` in the generic `mkClass` function, instead of having to set it in each generator for a specific class
- Use `Name`, `Description`, and `Import` type synonyms for `String` more consistently.
#2072 should be merged first. cc266cb is the first new commit.
=> Minor generator improvements

code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CommonPseudoOO.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/drasil-gool.cabal
This PR addresses the comments on #2084, renaming `SemiPolymorphic` to `CommonPseudoOO` and moving any functions it contained that were only used in one language to the language renderer.
=> CommonPseudoOO

code/drasil-gool/GOOL/Drasil/LanguageRenderer/CLike.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CommonPseudoOO.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/RendererClasses.hs
As discussed at the April 29th GOOL code review meeting, this PR passes over GOOL and uses do-notation instead of long, unreadable lines.
=> More do notation throughout GOOL

code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs
This PR introduces abbreviations for the helper functions for the pair instance in the C++ renderer, as discussed during the April 29th GOOL code review meeting.
=> Abbreviations for pair helpers

code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-code/Language/Drasil/Code/Imperative/Parameters.hs
While writing the additional comments about the bug fix, as requested by @JacquesCarette, I realized that even after my fix, the logic for the input constructor parameters was not perfect. In fixing it further, I also discovered and fixed another bug with parameters, where checking against the `currentClass` when determining parameters is not a good idea, because these same parameter-generating functions are used both for generating the functions and for generating calls to those functions, and the `currentClass` will be different in those two cases, potentially resulting in two different parameter lists for the same function. 
After this PR, these parameter-generating functions should be bug-free!
=> Even deeper bug fix, plus comments

code/drasil-code/Language/Drasil/CodeSpec.hs, code/drasil-example/Drasil/Projectile/Main.hs
Small PR that simplifies the user interface for the space match choice so they don't need to explicitly pass `spaceToCodeType`.
=> Remove SpaceMatch parameter from matchSpaces

code/drasil-code/Language/Drasil/Code/Imperative/Descriptions.hs, code/drasil-code/Language/Drasil/Code/Imperative/Generator.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs
This PR:
- Moves the logic for whether or not a main function should be generated to `genMainFunc`, instead of repeating the logic in multiple places where `genMainFunc` is called
- Moves the description of the unmodular module to Descriptions.hs, where it belongs.
=> Improvements to generation of main function

code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GamePhysics/References.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/drasil-example/Drasil/SWHS/References.hs, code/stable/gamephysics/SRS/GamePhysics_SRS.tex, code/stable/gamephysics/Website/GamePhysics_SRS.html, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
A little while ago I noticed a few of the examples (GamePhysics, SWHS, and, by extension, NoPCM) had the wrong references in the "Organization of Document" section. 
It looks like this has been the case for at least two years. It was a quick fix. I've included @smiths on this PR as stable has changed.
The "Organization of Document" section looks pretty standard (with some holes) between all the examples. Perhaps this is a good candidate for being moved into `drasil-docLang` (possibly with help from a multiple pass to extract the relevant sections), similar to #2116?
=> Correct references in "Organization of Document" section.

code/Makefile, code/scripts/deploy_stage.sh
I noticed that the section of the website that provides links to the generated artifacts for each example had a "GOOLTest" heading with no links, which must have been added when I incorporated my GOOL tests into the build. This PR updates the Makefile and deploy script so that only actual examples are shown on the website.
Though the empty "Template" is currently showing on the website, I didn't include it as an example, so it will be removed from the website after this PR. I assume this is what we want, but correct me if I'm wrong, and I will change it.
=> Only provide links to actual examples on website

code/drasil-gool/GOOL/Drasil/ClassInterface.hs, code/drasil-gool/GOOL/Drasil/RendererClasses.hs
This tiny PR just adds a missing GOOL constraint and removes an unnecessary one, which I noticed as I updated the dependency graph in my thesis.
=> Minor fixes to GOOL constraints

code/drasil-code/Language/Drasil/CodeSpec.hs
Small PR, just improves an error message in the code generator for when a path from inputs to outputs cannot be found. The new error message has line breaks so it is easier to read and is (in my opinion) more clear.
=> Improve error message for when output cannot be computed 

code/drasil-code/Language/Drasil/Choices.hs, code/drasil-code/Language/Drasil/Code.hs, code/drasil-code/Language/Drasil/Code/Imperative/Build/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/ConceptMatch.hs, code/drasil-code/Language/Drasil/Code/Imperative/Descriptions.hs, code/drasil-code/Language/Drasil/Code/Imperative/Doxygen/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/DrasilState.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/ClassInterface.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Language/Drasil/Code/Imperative/Generator.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Logging.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-code/Language/Drasil/Code/Imperative/Parameters.hs, code/drasil-code/Language/Drasil/Code/Imperative/SpaceMatch.hs, code/drasil-code/Language/Drasil/CodeSpec.hs, code/drasil-code/drasil-code.cabal
`Choices` and `CodeSpec` were defined in the same module. This PR moves `Choices` to its own module and documents it.
=> Move Choices to own module, add documentation

code/drasil-lang/Language/Drasil/Expr.hs
This PR adds some haddock documentation about the `Expr` `C` node. While I was at it, I also updated the existing comments on `Expr` to be in Haddock format.
=> Add haddock documentation to Expr

code/Makefile, code/website/stack.yaml, code/website/website.cabal
This PR is two small stack related changes related to 340638bad523d7c7c5e2335fd66569a9f1985c25. 
1. Match the resolver used for the deploy site, uses its own YAML as its auxiliary and not regularly compiled with the rest of the project, with that of the project. The benefit of this is the dependencies will be the same version throughout and we're not using two different versions of GHC.
2. Update the minimum Stack version required in the Makefile. This change is for consistency. I though I may be able to remove the `check_stack.sh` script with the `required-stack-version` YAML flag, but if someone is on <1.9.1 then our `stack` command will fail with an "unknown argument" error. Of course this is bad and why the `check_stack.sh` script was added in the first place and is truly our minimum …
=> Stack Updates

code/drasil-example/Drasil/SSP/Unitals.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
- contains all changed files related to updating the Shear Strength Symbol from tau to tau^f for SSP
- i.e. Unitals.hs, SSP_SRS.tex, SSP_SRS.html
- to address Issue #2156 Item 1
=> Update SSP Shear Strength Symbol

code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SSP/GenDefs.hs, code/drasil-example/Drasil/SSP/TMods.hs, code/drasil-example/Drasil/SSP/Unitals.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
- contains all changed files related to updating the Stress Data Definition to NormStress + Implementing the new TangStress Data Definition
- implementation of new TangStress Data Definition also necessitated creation of:
- new symbol F_t for SSP
- QDefinition TangStressQD
- Expr TangStressEqn
- Unital Chunk TangStress
- updated all references of totStress to totNormStress (changes related to Item 2)
- changed files: DataDefs.hs, TMods.hs, Unitals.hs, SSP_SRS.tex, SSP_SRS.html
- contributes to #2156 (addresses Issue Item 3, includes changes related to Item 2)
=> Update Stress to NormStress + Implement TangStress + Update Dependencies

code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/Macros.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/stable/gooltest/cpp/HelloWorld/HelloWorld.cpp, code/stable/gooltest/csharp/HelloWorld/HelloWorld.cs, code/stable/gooltest/java/HelloWorld/HelloWorld/HelloWorld.java, code/stable/gooltest/python/HelloWorld/HelloWorld.py
Closes #2147 
Quick synopsis of the modules if need be:
Language Renderer implements: subAssign which returns Doc
Language Polymorphic implements subAssign which uses previous subAssign, variable, value and terminator to return a MSStatement
Macros: was another subdivision of old solution (no longer needed)
Finally each language implements its own version of &-= by importing from Language Polymorphic.
=> Issue 2147

README.md
Implemented the following proposed changes (contributes somewhat to #2136):
- add linked and descriptive Table of Contents section
- update Quick Start section with pointers for Stack Install/Upgrade and File Directory commands
- add warning for time taken to complete entire Drasil examples build process/Haddock documentation Finding/Building
- update Summary of Folder Structure and File Contents section
=> Update Quick Start Guide

code/drasil-example/Drasil/SSP/GenDefs.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
- contains all changed files related to updating referencing for the general definition ResShr
- updated referencing for GD ResShr to include DD TangStress
- changed files: GenDefs.hs, SSP_SRS.tex, SSP_SRS.html
- closes #2156 (addresses Issue Item 4, the last Item of this Issue)
=> Update GD ResShr Referencing

code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-gool/GOOL/Drasil/ClassInterface.hs, code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs
- contains all changed files related to removing the `Label` parameter from GOOL's state variable constructors
- implemented changes to remove `Label` parameter from GOOL's state variable constructors `stateVarDef` and `constVar`
- changed files (seven):
- drasil-code: Modules.hs
- drasil-gool: ClassInterface.hs, CodeInfo.hs, CSharpRenderer.hs, CppRenderer.hs, JavaRenderer.hs, PythonRenderer.hs
- closes #2144 (addresses all items/changes requested in this Issue)
=> Remove Label Parameter from GOOL's State Variable Constructors

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs
This small PR re-factors the `value` function in the generator to be more readable, based on feedback from @JacquesCarette.
=> Refactor value function in generator to be more readable

code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CLike.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/stable/gooltest/cpp/HelloWorld/HelloWorld.cpp, code/stable/gooltest/csharp/HelloWorld/HelloWorld.cs, code/stable/gooltest/java/HelloWorld/HelloWorld/HelloWorld.java, code/stable/gooltest/python/HelloWorld/HelloWorld.py
- contains all changed files related to updating GOOL's `&--` operator to use the decrement operator (`--`) in generated code (and the `-=` operator in Python)
- implemented changes to updating GOOL's `&--` operator to use the decrement operator (`--`) in generated code (and `-=` operator in Python)
- to implement the above changes, two new functions, `decrement` (in LanguageRenderer.hs) and `decrement1` (in CLike.hs) were created
- references to the function `decrement1` (from Macros.hs) were removed and replaced with:
- the function `decrement1` (from CLike.hs) in the C++, C# and Java Language Renderers
- a partial application of the `&-=` GOOL operator implementation in the Python Language Renderer
- changed files (ten):
- drasil-gool: LanguageRenderer.hs, CLike.hs, CSharpRenderer.hs, …
=> Update GOOL's &-- Operator Implementation + HelloWorld Stable Files

.gitattributes
Related to #2183. If I understand correctly, marking files as linguist-vendored in the .gitattributes file will make them ignored for GitHub's language statistics, so this repo will go back to being a Haskell project.
=> Update gitattributes to ignore files from external libraries in our repo

code/website/site.hs
This should fix #2201. The function that determines the text for the links on the site to each language needed a case for Swift.
=> Add language name on site for Swift

code/drasil-example/Drasil/GamePhysics/IMods.hs, code/stable/gamephysics/SRS/GamePhysics_SRS.tex, code/stable/gamephysics/Website/GamePhysics_SRS.html
Closes #2241.  There is a typo in the original text that uses 2d instead of 2D.  At some point we should probably introduce a symbolic constant for 2D, so that 2D is always used, instead of relying on the person coding in the example to use the proper case.  (I suppose if someone wanted to, they could always make an "error" like this by using a string, instead of using the symbolic constant.
=> Fixes #2241 (2d is corrected to 2D)

code/drasil-code/Language/Drasil/Chunk/CodeDefinition.hs, code/drasil-code/Language/Drasil/Code.hs, code/drasil-code/Language/Drasil/Code/ExternalLibrary.hs, code/drasil-code/Language/Drasil/Code/ExternalLibraryCall.hs, code/drasil-code/Language/Drasil/Data/ODEInfo.hs, code/drasil-data/Data/Drasil/ExternalLibraries/ODELibraries.hs, code/drasil-example/Drasil/NoPCM/Body.hs
Added a new ODE package for Python called `scipyODELSodaPkg` that calls the [`odeint` ](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.odeint.html) method of Scipy. The [odeint ](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.odeint.html) method solves a system of ODE using the Lsoda solver.
Following is a summary of the changes. 
- ./drasil-data/Data/Drasil/ExternalLibraries/ODELibraries.hs - Contains the definition of the new ODE package.
- ./drasil-code/Language/Drasil/Data/ODEInfo.hs - Modified the `ODEInfo `and `ODEOptions `types, and added a new constructor `initValFstOrd` to hold `y'(0)`.
- . /drasil-code/Language/Drasil/Chunk/CodeDefinition.hs - Updated the `odeDef` function to include `initValFstOrd`.
- …
=> New ODE package for Python, ScipyODELsoda, that can solve second order ODEs

code/drasil-utils/stack.yaml
Following suit in 333bbbf02fba4c925a603ca60e2ebfc2e64293c1
=> Remove drasil-theory from drasil-utils' stack.yaml

code/drasil-docLang/Drasil/DocumentLanguage/Definitions.hs
`elem` has been in Prelude as early as [`base-4.0.0.0`](https://hackage.haskell.org/package/base-4.0.0.0/docs/Prelude.html#v%3Aelem) so it seems that this won't break GHC compatibility with 8.* ([GHC 6.10.1](https://wiki.haskell.org/Base_package) is earliest to ship with `base-4.0.0.0`)
=> Remove unneeded import of elem (already in Prelude)

code/drasil-example/Drasil/PDController/Main.hs
Result of #2357 causing an issue. All other examples set encoding to utf8 first in their respective `main` functions, but pdController was missing it.
=> Set locale encoding to utf8 by default in pdController example

.github/workflows/Drasil.yaml
Closes #2366 
+ Adds a button in the "Actions" menu for manually running workflows.
+ When `[workflow-trigger]` is in a pushed commit message, the build workflow will run on it.
+ Cancels workflows that are running on the same branch with a different SHA.
When commits don't have the trigger text, they will still be considered to have passed checks. We can probably figure out a way to make this look like it's failed instead. Do you have any preference for this @JacquesCarette ?
=> Adding manually triggered builds + cancelling previous runs

code/drasil-example/drasil-example.cabal
I'm not too sure what happened, but it was giving errors in the `make` command!
A simple regeneration of the `drasil-example` cabal file is sufficient to fix it luckily. Maybe we'll need to write some documentation about using this build system as well later?
=> regenerate drasil-example cabal file

code/drasil-printers/Language/Drasil/Printing/Import.hs
As early as [base 4.6.0.0](https://hackage.haskell.org/package/base-4.6.0.0/docs/Prelude.html#v:fst) (GHC 7.6.1) contained `fst` and `snd`, so we can remove the import causing the warning without worrying about causing compatibility issues for GHC 8.*.
=> redundant import: fst, snd

code/drasil-data/Data/Drasil/Quantities/Physics.hs, code/drasil-example/Drasil/DblPendulum/DataDefs.hs, code/drasil-example/Drasil/DblPendulum/GenDefs.hs, code/drasil-example/Drasil/DblPendulum/Unitals.hs, code/stable/dblpendulum/SRS/DblPendulum_SRS.tex, code/stable/dblpendulum/Website/DblPendulum_SRS.html
I apologize in advance for the large PR. After discussing issue #2391 some more, Dr. Smith gave me the link to the derivations of the velocity and acceleration equations, so most of the changes are just implementing those. `xPos` and `yPos` were also added to the list of symbols (which closes issue #2411)
=> Adding velocity and acceleration derivations in pendulum

.github/workflows/Drasil.yaml, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs
Relies on #2430 (so as not to fail the build)
=> Re-enable errors on warnings in GitHub Actions Workflows/Builds

code/drasil-example/Drasil/PDController/Assumptions.hs, code/drasil-example/Drasil/PDController/Body.hs, code/drasil-example/Drasil/PDController/Changes.hs, code/drasil-example/Drasil/PDController/DataDefs.hs, code/drasil-example/Drasil/PDController/GenDefs.hs, code/drasil-example/Drasil/PDController/GenSysDesc.hs, code/drasil-example/Drasil/PDController/IModel.hs, code/drasil-example/Drasil/PDController/IntroSection.hs, code/drasil-example/Drasil/PDController/Requirements.hs, code/drasil-example/Drasil/PDController/SpSysDesc.hs, code/drasil-example/Drasil/PDController/TModel.hs, code/stable/pdController/SRS/PDController_SRS.tex, code/stable/pdController/Website/PDController_SRS.html
Removed unneeded whitespaces and used commas over `+:+` and `<>` operators.
Closes issue #2450
=> Removed Whitespaces in PDController

code/drasil-docLang/Drasil/DocLang/SRS.hs, code/drasil-utils/Utils/Drasil.hs, code/drasil-utils/Utils/Drasil/Sentence.hs
Moved forTT function to Utils.Drasil.Sentence.
Closes #2457 
PR #2464 will likely not be able to merge automatically with this, but I think this one should still be merged to master first as the other one is much bigger.
=> Moving forTT functions

code/drasil-utils/Utils/Drasil.hs, code/drasil-utils/Utils/Drasil/Concepts.hs, code/drasil-utils/Utils/Drasil/Phrase.hs
Added inThe operator for NamedIdeas and NPs. This should help #2397 and contributes to #2399
=> Added inThe operator at a higher level

code/drasil-data/Data/Drasil/Concepts/Documentation.hs, code/drasil-data/Data/Drasil/Concepts/Math.hs, code/drasil-data/Data/Drasil/Concepts/Physics.hs, code/drasil-data/Data/Drasil/Concepts/Thermodynamics.hs, code/drasil-utils/Utils/Drasil.hs, code/drasil-utils/Utils/Drasil/Misc.hs
Moved `fterms` to `Utils.Drasil.Misc`, used `fterms` more in `Data.Drasil.Concepts.Math`.
Closes #2483.
=> Moving fterms to Utils

code/Makefile
From the [manual page](https://man7.org/linux/man-pages/man1/rm.1.html) of `rm`,
>       -f, --force
>             ignore nonexistent files and arguments, never prompt
Adding `-f` will just make it ignore errors, always seeing the command through. For what we're doing here, I think it's appropriate, causes less errors in the logs (that I don't think we care about).
=> Stop `make clean` from returning an error code when it doesn't delete everything

code/drasil-lang/Language/Drasil/Chunk/Citation.hs, code/drasil-lang/Language/Drasil/Chunk/CommonIdea.hs, code/drasil-lang/Language/Drasil/Chunk/Concept.hs, code/drasil-lang/Language/Drasil/Chunk/Concept/Core.hs, code/drasil-lang/Language/Drasil/Chunk/Constrained.hs, code/drasil-lang/Language/Drasil/Chunk/DefinedQuantity.hs, code/drasil-lang/Language/Drasil/Chunk/Eq.hs, code/drasil-lang/Language/Drasil/Chunk/NamedArgument.hs, code/drasil-lang/Language/Drasil/Chunk/NamedIdea.hs, code/drasil-lang/Language/Drasil/Chunk/Quantity.hs, code/drasil-lang/Language/Drasil/Chunk/Relation.hs, code/drasil-lang/Language/Drasil/Chunk/UncertainQuantity.hs, code/drasil-lang/Language/Drasil/Chunk/UnitDefn.hs, code/drasil-lang/Language/Drasil/Chunk/Unital.hs, code/drasil-lang/Language/Drasil/Chunk/Unitary.hs, code/drasil-lang/Language/Drasil/Chunk/UnitaryConcept.hs, code/drasil-lang/Language/Drasil/Classes/Core.hs, code/drasil-lang/Language/Drasil/NounPhrase.hs
Documented all files in `Chunk` folder under `drasil-lang`. Mostly focused on instances and datatypes, but mainly a second go at the documentation for all of `Chunk` now that I understand more of the functions. Also some style changes.
Contributes #2477.
=> Lang Documentation

code/drasil-example/Drasil/Projectile/DataDefs.hs, code/drasil-printers/Language/Drasil/Plain/Print.hs, code/drasil-printers/Language/Drasil/TeX/Print.hs, code/stable/projectile/SRS/Projectile_SRS.tex, code/stable/projectile/Website/Projectile_SRS.html
Builds on #2495 
Just a suggestion, I think the standard way to have vector norms in LaTeX is `\|` wrapped around a vector, so this changes ours from `||`:
to:
=> Alternative style for printing vector magnitude?

code/drasil-example/Drasil/DblPendulum/Requirements.hs, code/drasil-example/Drasil/GlassBR/Assumptions.hs, code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/GlassBR/Changes.hs, code/drasil-example/Drasil/GlassBR/IMods.hs, code/drasil-example/Drasil/GlassBR/Requirements.hs, code/drasil-example/Drasil/GlassBR/Unitals.hs, code/drasil-utils/Utils/Drasil/Concepts.hs
Adding concept-level combinators to GlassBR example, introduced some new combinators to Utils.Drasil.Concepts used in the GlassBR example (this will likely have some merge conflicts with the GamePhys PR, but it should quick to fix when it's ready).
=> Adding concept-level combinators to GlassBR example

.github/workflows/Build.yaml, .github/workflows/Test.yaml
Contributes to #2326 
Adding in caching to the build deployment will speed it up quite a bit (see https://github.com/balacij/Drasil/actions/runs/879639653 vs subsequent run https://github.com/balacij/Drasil/actions/runs/879785183). Unfortunately, this speed up will only work when there's a cache hit, meaning only when the previous run was successful.
These changes also force a `make clean` before building the software suite to make sure that we never inherit issues from previous builds.
=> Caching in deployment build + force `make clean` before rebuilding suite

code/drasil-example/Drasil/Projectile/Assumptions.hs, code/drasil-example/Drasil/Projectile/Body.hs, code/drasil-example/Drasil/Projectile/Concepts.hs, code/drasil-example/Drasil/Projectile/GenDefs.hs, code/drasil-example/Drasil/Projectile/IMods.hs, code/drasil-example/Drasil/Projectile/Requirements.hs, code/drasil-utils/Utils/Drasil/Concepts.hs
For some reason, in line 108 of `code/drasil-example/Drasil/Projectile/Body.hs`, using the `combineNINI` combinator breaks the capitalization (where `atStartNP` and `titleizeNP` both don't work). But I think I should investigate that later.
Also, I know that you mentioned that fixing up examples and adding combinators to the existing infrastructure should have different PRs, but this was only a small change (adding a `toThe` combinator) and stable remained the same. Either way, they were incorporated in separate commits.
=> Adding more concept combinators to projectile

code/drasil-example/Drasil/SSP/Assumptions.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SSP/Changes.hs, code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SSP/Defs.hs, code/drasil-example/Drasil/SSP/GenDefs.hs, code/drasil-example/Drasil/SSP/Goals.hs, code/drasil-example/Drasil/SSP/IMods.hs, code/drasil-example/Drasil/SSP/Requirements.hs, code/drasil-example/Drasil/SSP/TMods.hs, code/drasil-example/Drasil/SSP/Unitals.hs, code/drasil-utils/Utils/Drasil.hs, code/drasil-utils/Utils/Drasil/Concepts.hs, code/drasil-utils/Utils/Drasil/Misc.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
Also added a `definedIn'''` reference combinator as the same form was used quite a bit. Changed a misplaced period in stable as well. This should be the last of the examples that need to use the new combinators.
=> Added concept-level combinators to SSP

code/stack.yaml
Closes #2530 
Removes the flag that disabled Haddock "hyperlinked source code" creation.
Demo: https://balacij.github.io/Drasil/docs/full/drasil-build-0.1.1.0/Build-Drasil.html
It just creates a lot of extra LOC that drasil-bot will be committing. It will likely also increase the size of our project. If space becomes a concern, we can erase the `gh-pages` branch from here and host it in another repository. Alternatively, we can host the docs with something else.
=> Enable hyperlinking source in Haddock

code/drasil-docLang/Drasil/DocLang.hs, code/drasil-docLang/Drasil/ExtractDocDesc.hs
closes Issue #2541 
contributes to Issue #1602
=> deleting outdated constructor: `ciGetDocDesc`

code/scripts/DataTableGen.hs
Fixed errors in calculating lengths of a row causing too many html cells in a row.
Contributes (closes?) #2221 and #2231
=> Data Table Row Length Fix

code/Makefile
Just slightly decomposing the `make clean` target so that we can avoid running `stack clean` when it's not necessary.
=> Add 'clean_artifacts/cleanArtifacts' target

code/drasil-example/Drasil/SSP/TMods.hs, code/drasil-theory/Theory/Drasil.hs, code/drasil-theory/Theory/Drasil/ConstraintSet.hs, code/drasil-theory/Theory/Drasil/GenDefn.hs, code/drasil-theory/Theory/Drasil/InstanceModel.hs, code/drasil-theory/Theory/Drasil/ModelKinds.hs, code/drasil-theory/Theory/Drasil/MultiDefn.hs, code/drasil-theory/drasil-theory.cabal, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
Closes #2581 
One notable thing is that it divides the constraints for the `equilibrium` TM into 3 separate equations:
So, from ->
we get ->
=> Create EquationalConstraints Model + convert SSP's TM `equilibrium` into EquationalConstraints model

code/drasil-example/Drasil/GlassBR/Body.hs
These particular QDefinitions for GlassBR are not needed since they're obtained from the IMs. However, from past discussion, I think that we're not supposed to be creating generable code using the TMs.
I came across this while checking the QDef-In-InstMod branch while trying to port over the last few changes back slowly. After this, I think we will need to get a well-placed "getEqModQdsFromIM/GDs" somewhere to get the definitions of the IMs and GDs into the realm of generable code.
=> Remove QDs from TMs added to GlassBR's SystemInformation

.github/workflows/Build.yaml, .github/workflows/Test.yaml, .gitignore, code/Makefile
* Added `.hlint*` to the .gitignore
* Wrapped string fields in double quotes in the makefile
* Add 2 new make targets -- `hlint` and `hot_hlint` for using hlint, respectively, via a local installation or via hot download
=> Add a `hlint` + `hot_hlint` Makefile target

code/drasil-example/Drasil/DblPendulum/Body.hs, code/stable/dblpendulum/SRS/DblPendulum_SRS.tex, code/stable/dblpendulum/Website/DblPendulum_SRS.html
- The Pendulum is capitalized in the last word of the first paragraph.
- I created additional three tickets to add three new sections.
close #2615
=> capitalized pendulum in the introduction

code/Makefile, code/drasil-lang/Language/Drasil/Sentence/Extract.hs, code/drasil-printers/Language/Drasil/Printing/Import/Helpers.hs, code/drasil-website/Drasil/Website/CaseStudy.hs, code/drasil-website/Drasil/Website/Example.hs, code/scripts/SourceCodeReaderTypes.hs
Closes #2660 
The prefixed `-` of the hlint runs suppressed the errors.
The actions run _should_ fail. We can fix them in this ticket as well, but I want to see it fail first to make sure.
=> Make `make hlint` and `make hot_hlint` return the error codes (no suppression with -)

code/drasil-data/Data/Drasil/Theories/Physics.hs, code/drasil-example/Drasil/DblPendulum/GenDefs.hs, code/drasil-example/Drasil/DblPendulum/IMods.hs, code/drasil-example/Drasil/GamePhysics/GenDefs.hs, code/drasil-example/Drasil/GamePhysics/IMods.hs, code/drasil-example/Drasil/GamePhysics/TMods.hs, code/drasil-example/Drasil/GlassBR/IMods.hs, code/drasil-example/Drasil/GlassBR/TMods.hs, code/drasil-example/Drasil/NoPCM/GenDefs.hs, code/drasil-example/Drasil/NoPCM/IMods.hs, code/drasil-example/Drasil/PDController/GenDefs.hs, code/drasil-example/Drasil/PDController/IModel.hs, code/drasil-example/Drasil/PDController/TModel.hs, code/drasil-example/Drasil/Projectile/GenDefs.hs, code/drasil-example/Drasil/Projectile/IMods.hs, code/drasil-example/Drasil/SSP/GenDefs.hs, code/drasil-example/Drasil/SSP/IMods.hs, code/drasil-example/Drasil/SSP/TMods.hs, code/drasil-example/Drasil/SWHS/GenDefs.hs, code/drasil-example/Drasil/SWHS/IMods.hs, code/drasil-example/Drasil/SWHS/TMods.hs, code/drasil-theory/Theory/Drasil.hs, code/drasil-theory/Theory/Drasil/GenDefn.hs, code/drasil-theory/Theory/Drasil/InstanceModel.hs, code/drasil-theory/Theory/Drasil/ModelKinds.hs, code/drasil-theory/Theory/Drasil/Theory.hs
+ Create `ModelKind` as a 3-tuple, around `ModelKinds`
+ Create smart constructors for each model kind, remove exposure of `ModelKinds` completely
+ Clean up IM/GD/TM, pushing the overridable UID/NP to the new `ModelKind`
=> Make ModelKind an ADT containing the original ModelKinds

code/drasil-example/Drasil/DblPendulum/Body.hs, code/stable/dblpendulum/SRS/DblPendulum_SRS.tex, code/stable/dblpendulum/Website/DblPendulum_SRS.html
In the scope, there are two periods at the end of the sentence. Removed one extra period.
close #2616
=> Remove the extra period on the scope - Double Pendulum 

code/drasil-docLang/Drasil/DocLang.hs, code/drasil-docLang/Drasil/DocumentLanguage/Labels.hs, code/drasil-docLang/drasil-docLang.cabal, code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Document.hs, code/drasil-lang/Language/Drasil/Reference.hs
Contributes to #1216
This is going to break stable, but i'm pushing the changes so you can also see why.
I deleted the makeLstRef function but it's used in defining other functions which are used in the Examples. These functions were defined in a Label.hs file under doc-lang. I tried to delete the file just to see what things it would affect in turn.
I'm thinking now that i don't touch these functions? or do you think there might be something else to do here?
=> Deleting makeLst functions

.github/workflows/Build.yaml, .github/workflows/Test.yaml, code/shell.nix
Closes #2702 
Unfortunately, installing fonts is considered a side-effect on systems, and, as such, is only allowed in the NixOS `configuration.nix` (or if users use `home-manager`, it's allowed through that too). So, this script will install the base requirements for a CLI user to develop Drasil and work with the generated artifacts.
(I also have a small change where I reorder a NOISY=yes parameter in both of the CI files.)
=> Add basic nix shell script

code/scripts/make_docs.sh
CI _should_ fail due to actual Haddock errors.
Contributes to #2762
=> `make docs` should fail when the haddock docs fail to build

code/drasil-lang/Language/Drasil/Chunk/Eq.hs
Contributes #2679, #2677 
Might interfere with #2735, #2705 
I know #2677 wants to move away from the `Maybe UnitDefn` in `DefinedQuantityDict` but I think this reliance on the `dqd` constructors is okay:
- While there are a lot of `QDefinition` function constructors, most of them set the unit definition to `Nothing` anyway
- The ones that do have a `UnitDefn` have very few calls in the examples.
However, both `mkQuantDef` and `mkQuantDef'` are used a lot. They are both projector functions and they still hold units. Would we then want `QDefinition` to use a `UnitalChunk` instead of a `DefinedQuantityDict`?
=> Switching QDefinition to use DefinedQuantityDict

code/drasil-lang/Language/Drasil/Chunk/CommonIdea.hs
Contributes #2679, #2677
This change shouldn't interfere with anything.
For reference, I generated the type analysis for drasil lang and its starting to look much more like a hierarchy now (specifically the types starting from NamedChunk rather than UID). I will attach the picture below with the unrelated types whited out:
=> Making CI use NamedChunk instead of direct fields

code/drasil-data/Data/Drasil/Concepts/Physics.hs, code/drasil-lang/Language/Drasil/NounPhrase.hs
Contributes #2759 
Found that the `positionVec` UID had an extra whitespace while exploring the logs.
Also used concept-level combinators instead of `nounPhraseSent`.
=> Various fixes in Data/Drasil/Concepts/Physics

CITATION.cff
Closes #2794 
Regarding the authors list, @JacquesCarette & @smiths, on the Zenodo page, the following are listed as authors:
* Dan Szymczak
* bmaclach
* Jacques Carette
* Maryyam
* Sam Crawford
* Daniel Scime
* AKM11
* palmerst
* Spencer Smith
* oluowoj
* elwazana
* Mornix
* muhammadaliog3
* Devi Prasad Reddy Guttapati
* Nathaniel Hu
* Jingwei
* Luthfi Mawarid
* Joseph Seger
* Aida
* Naveen Ganesh Muralidharan
* Azer-X
* Daniel Genkin
* Rohan Jain
By any chance, do we have any named organization we all belong to (e.g., ~ "Drasil Research Group") that we would prefer to put as the preferred citation author?
Also, should we ask individually what everyone wants to put for their personal information? There's [a lot of information](https://github.com/citation-file-format/citation-file-format/b …
=> Add basic CITATION.cff file

.github/workflows/Build.yaml, code/Makefile
Contributes to #2789 
Removes dot and circo SVG conversions from tests, leaving them only performed for full deployments.
=> Only build dot & circo graphs for deployments, when required

code/Makefile
=> Avoid installing binaries on host computer on default `make`, create `install` and `X_install` targets to replace

code/Makefile
Contributes to #2152 
I added a small message regarding it on https://github.com/JacquesCarette/Drasil/wiki/Makefile and https://github.com/JacquesCarette/Drasil/wiki/Workflow . Unfortunately, I can't hyperlink to them directly, so please use CTRL+F and search for `pr_ready`.
=> Add `make pr_ready` target to quickly check if a branch is ready for PR creation

code/drasil-code/lib/Data/Drasil/ExternalLibraries/ODELibraries.hs, code/drasil-code/lib/Language/Drasil/Chunk/NamedArgument.hs, code/drasil-code/lib/Language/Drasil/Chunk/README.md, code/drasil-code/lib/Language/Drasil/Code.hs, code/drasil-code/lib/Language/Drasil/Code/ExtLibImport.hs, code/drasil-code/lib/Language/Drasil/Code/ExternalLibrary.hs, code/drasil-code/lib/Language/Drasil/Code/ExternalLibraryCall.hs, code/drasil-code/package.yaml, code/drasil-lang/lib/Language/Drasil.hs, code/drasil-lang/lib/Language/Drasil/Chunk/README.md
Contributes to #2885 
NamedArgument is only used in `drasil-code` at the moment, and is described as a tool for "generating code".
=> Move `NamedArgument` to `drasil-code`

code/drasil-code/test/HelloWorld.hs
=> Disable single HLint false-positive: 'Evaluation' on `const`

code/Makefile, code/datafiles/dblpendulum/cpp, code/datafiles/dblpendulum/csharp, code/datafiles/dblpendulum/java
This will fix the broken documentation links of the double pendulum on the website. The way we fixed it seems odd to me because we have to make the change in the makefile. Is it possible to move it to the Haskell level?
related #3011
=> Trigger doxygen to generate documentation for dblpendulum

code/hie.yaml
HLS broke for me with their latest update, but I was able to fix it by adding this "hie.yaml" file. It is generated by [`implicit-hie`](https://hackage.haskell.org/package/implicit-hie).
@peter-michalski I remember you mentioning that you always had problems with HLS. Do you want to check if this branch makes it work for you? You will need to do a `make code` first, and then open VSCode. If VSCode fails to load, running `haskell-language-server` manually in the `code/` directory might help us understand what's broken with yours.
=> Add hie.yaml to fix "multi-cradle" issues for Haskell Language Server

code/drasil-example/gamephysics/lib/Drasil/GamePhysics/DataDefs.hs, code/stable/gamephysics/SRS/HTML/GamePhysics_SRS.html, code/stable/gamephysics/SRS/PDF/GamePhysics_SRS.tex
Definition of kEnergy was missing a norm call. Was found through type checking. Fixes #3161.
=> Fix #3161 (kEnergy in GamePhysics)

code/drasil-printers/lib/Language/Drasil/TeX/Monad.hs, code/drasil-printers/lib/Language/Drasil/TeX/Print.hs
Closes #3230 
I'm not quite sure I'm happy with this resolution yet. The 'code' part of the solution isn't difficult now that it's understood. The only questionable component is: what should `<>` (and hence `mappend`) be doing?
For now, I've defaulted to `mappend` to `<>` as per current recommendations by the Haskell community, as `mappend` will eventually be removed. Then, I replaced usage of `mconcat` (which relied on the old `mappend` definition) with a copy of the old definition.
So, now the question goes to: was this the right solution?
=> Resolve conflicting instances for Semigroup & Monoid for `PrintLaTeX Doc`

.github/dependabot.yml
Closes #3227 
Creates a Dependabot script that GitHub reads to automatically search for updates to our GitHub Actions script. It uses the [Example](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions) script GitHub provides to submit PRs on a weekly basis.
While I don't imagine there being an issue with the PR, it's probably best to wait for a PR (or some sort of feedback that it works) from dependabot on my fork before merging into the main repo. So, creating a PR so that we don't forget, but leaving it as a "draft" so that we know it's not yet tested.
We just need to manually enable the Dependabot > Dependabot Version updates under the repo settings. This is what it …
=> Add dependabot weekly GH Actions update script

code/drasil-example/pdcontroller/lib/Drasil/PDController/Body.hs, code/drasil-example/pdcontroller/lib/Drasil/PDController/Concepts.hs
Closes #3364. Note that `pdControllerApp` is used to be consistent with the UID.
=> Rename pidControllerSystem to pdControllerApp

code/drasil-data/lib/Data/Drasil/Citations.hs, code/stable/dblpendulum/SRS/HTML/DblPendulum_SRS.html, code/stable/dblpendulum/SRS/JSON/DblPendulum_SRS.ipynb, code/stable/dblpendulum/SRS/PDF/DblPendulum_SRS.tex, code/stable/gamephysics/SRS/HTML/GamePhysics_SRS.html, code/stable/gamephysics/SRS/JSON/GamePhysics_SRS.ipynb, code/stable/gamephysics/SRS/PDF/GamePhysics_SRS.tex, code/stable/glassbr/SRS/HTML/GlassBR_SRS.html, code/stable/glassbr/SRS/JSON/GlassBR_SRS.ipynb, code/stable/glassbr/SRS/PDF/GlassBR_SRS.tex, code/stable/nopcm/SRS/HTML/NoPCM_SRS.html, code/stable/nopcm/SRS/JSON/NoPCM_SRS.ipynb, code/stable/nopcm/SRS/PDF/NoPCM_SRS.tex, code/stable/sglpendulum/SRS/HTML/SglPendulum_SRS.html, code/stable/sglpendulum/SRS/JSON/SglPendulum_SRS.ipynb, code/stable/sglpendulum/SRS/PDF/SglPendulum_SRS.tex, code/stable/ssp/SRS/HTML/SSP_SRS.html, code/stable/ssp/SRS/JSON/SSP_SRS.ipynb, code/stable/ssp/SRS/PDF/SSP_SRS.tex, code/stable/swhs/SRS/HTML/SWHS_SRS.html, code/stable/swhs/SRS/JSON/SWHS_SRS.ipynb, code/stable/swhs/SRS/PDF/SWHS_SRS.tex
Fixed Koothoor2013 reference in Citations.hs which had incorrectly stated the title of the thesis as "A document drive approach to certifying scientific computing software." This has now been fixed to include the correct title for the reference.
=> Updated Citations.hs to properly reflect the title of Koothoor2013 thesis

code/drasil-theory/lib/Theory/Drasil/DataDefinition.hs
Closes #3338 
The fix only applies to `DataDefinition`-defined function-typed variables (for which our current examples has none, but BeamBending does have one).
=> DataDefinition express instance: inherit from QDefinition

code/drasil-build/stack.yaml, code/drasil-code/stack.yaml, code/drasil-data/stack.yaml, code/drasil-database/stack.yaml, code/drasil-docLang/stack.yaml, code/drasil-example/dblpendulum/stack.yaml, code/drasil-example/gamephysics/stack.yaml, code/drasil-example/glassbr/stack.yaml, code/drasil-example/hghc/stack.yaml, code/drasil-example/nopcm/stack.yaml, code/drasil-example/pdcontroller/stack.yaml, code/drasil-example/projectile/stack.yaml, code/drasil-example/sglpendulum/stack.yaml, code/drasil-example/ssp/stack.yaml, code/drasil-example/swhs/stack.yaml, code/drasil-example/template/stack.yaml, code/drasil-gen/stack.yaml, code/drasil-gool/stack.yaml, code/drasil-lang/stack.yaml, code/drasil-metadata/stack.yaml, code/drasil-printers/stack.yaml, code/drasil-sysinfo/stack.yaml, code/drasil-theory/stack.yaml, code/drasil-utils/stack.yaml, code/drasil-website/stack.yaml, code/stack.yaml
Bumping from GHC 9.2.5 to 9.2.7 with the updated Stackage lists.
=> Update Stack minor version

.github/CODEOWNERS
As per comments on #3394, yaml files will only be "owned" by @JacquesCarette and @balacij. 😅 @balacij, you only mentioned package.yaml and stack.yaml files in #3394; I also noticed .hlint.yaml files in our repo. Do you want to be assigned ownership of those too? (That is currently what I have here, but this can easily be changed.)
This is a follow-up to #3312 and #3348
=> Assign ownership of yaml files to @JacquesCarette and @balacij

code/Makefile, code/stable/glassbr/src/cpp/designLog.txt, code/stable/glassbr/src/csharp/designLog.txt, code/stable/glassbr/src/java/designLog.txt, code/stable/glassbr/src/python/designLog.txt, code/stable/glassbr/src/swift/designLog.txt, code/stable/nopcm/src/cpp/designLog.txt, code/stable/nopcm/src/csharp/designLog.txt, code/stable/nopcm/src/java/designLog.txt, code/stable/nopcm/src/python/designLog.txt, code/stable/pdcontroller/src/cpp/designLog.txt, code/stable/pdcontroller/src/csharp/designLog.txt, code/stable/pdcontroller/src/java/designLog.txt, code/stable/pdcontroller/src/python/designLog.txt
Closes #3411 
This should avoid future issues related to #3411 as `.txt` files will now be diff'd against `stable/`.
=> Add '*.txt' files back into diff checking

code/drasil-printers/lib/Language/Drasil/Printing/Helpers.hs, code/stable/ssp/SRS/HTML/SSP_SRS.html, code/stable/ssp/SRS/JSON/SSP_SRS.ipynb, code/stable/swhs/SRS/HTML/SWHS_SRS.html, code/stable/swhs/SRS/JSON/SWHS_SRS.ipynb
Contributes to #3357 for part 2 of the issue. Changes made to Helpers.hs in `drasil-printers` and stable to fix the suffixes of edition numbers.
=> 3357 Issues with display of references - Suffix

code/drasil-printers/lib/Language/Drasil/Printing/Helpers.hs
While making #3459, I came across [this Stack Exchange post](https://codegolf.stackexchange.com/questions/4707/outputting-ordinal-numbers-1st-2nd-3rd) that pointed out that the pattern 11, 12, and 13 using "th" repeats every 100 (e.g., 11th, 112th, 498713th).
This PR implements this based on the work done in #3421
=> Update `sufxer` to deal with mod 100

code/drasil-printers/lib/Language/Drasil/TeX/Print.hs, code/stable/dblpendulum/SRS/PDF/DblPendulum_SRS.tex, code/stable/gamephysics/SRS/PDF/GamePhysics_SRS.tex, code/stable/glassbr/SRS/PDF/GlassBR_SRS.tex, code/stable/hghc/SRS/PDF/HGHC_SRS.tex, code/stable/nopcm/SRS/PDF/NoPCM_SRS.tex, code/stable/pdcontroller/SRS/PDF/PDController_SRS.tex, code/stable/projectile/SRS/PDF/Projectile_SRS.tex, code/stable/sglpendulum/SRS/PDF/SglPendulum_SRS.tex, code/stable/ssp/SRS/PDF/SSP_SRS.tex, code/stable/swhs/SRS/PDF/SWHS_SRS.tex
Closes #3458.
I have checked locally that this can be merged independently of #3460 (I ran `git merge --no-commit fix-tabu` followed by `make pr_ready`).
=> Remove excess line breaks from LaTeX tables

.github/workflows/Build.yaml
This PR adds a step in the GitHub workflow to generate C++, Java, etc. from the GOOL examples under `drasil-code/test` and compile them to check for compile errors.
=> Add GOOL examples to CI

code/drasil-code/test/NameGenTest.hs, code/drasil-code/test/VectorTest.hs
Closes #3510. Changes made to `VectorTest.hs` and `NameGenTest.hs`
=> 3510 Fixes New Tests Failing on CI

code/drasil-example/hghc/lib/Drasil/HGHC/HeatTransfer.hs, code/drasil-example/nopcm/lib/Drasil/NoPCM/Definitions.hs, code/drasil-example/swhs/lib/Drasil/SWHS/Body.hs, code/drasil-example/swhs/lib/Drasil/SWHS/Concepts.hs
Closes #3542.
A possibly controversial change is the change from `capSent (swhsPCM ^. defn)` to `capSent $ pluralNP $ progName ^. term, S "incorporating", phrase phsChgMtrl` (this is inside the list of `Setence`s passed to `foldlSent`) in `introStartSWHS`.
In the original code, `swhsPCM` is a `CommonConcept` whose term is "solar water heating systems incorporating PCM" and whose definition is "solar water heating systems incorporating phase change material" (the definition expands "PCM" to "phase change material"). This is not really a definition but rather a hack to get multiple levels of abbreviation, and since this "definition" is only used in one place, I don't think we are worse off if we just construct it in the spot where it is used, especially with respect to our goal of removing …
=> Change `hghc`, `srsSWHS`, and `swhsPCM` to `CI`s

code/Makefile
Closes #3560. It seems that in addition to `stack build`, `stack exec` also requires the `--profile` flag (the `--profile` flag is equivalent to `--executable-profiling --library-profiling`). But `--profile` needs to be passed to `stack exec` before the `--`, so I've moved the `$(EXECARGS)` to before the `--` since the RTS flags that used to be passed after `--` can also be passed before `--`.
=> Fix `make debug`

.github/workflows/Build.yaml, .github/workflows/Lint.yaml
Contributes to #2789 
Decreases build time by only running HLint when absolutely necessary (i.e., when a file in one of the `code/drasil-*` paths are edited) and concurrently alongside the "build & test" workflow.
Tested with #3553.
=> Move HLint script to a separate workflow file

code/Makefile, code/scripts/ClassInstDepGen.hs, code/scripts/TypeDepGen.hs
Closes #3369 by adding direct traceability to the requirements of the scripts. I'm only adding it to the ones that are actual "scripts" and intended to be runnable. Adding the shebang to the local shared modules `SourceCodeReader...hs` wouldn't make sense since it is not intended to be run.
=> Add Stack-based shebangs to some of the `scripts/**.hs` files

code/drasil-lang/lib/Language/Drasil.hs, code/drasil-lang/lib/Language/Drasil/Chunk/CodeVar.hs, code/drasil-lang/lib/Language/Drasil/CodeExpr/Class.hs
Closes #3470 and allows us to load Drasil into `ghci` again.
@hrzhuang if you could confirm it runs on your machine as well, I'd appreciate it!
=> Rename `drasil-lang`s ...CodeBase to ...CodeVar

code/drasil-printers/lib/Language/Drasil/HTML/CSS.hs, code/stable/dblpend/SRS/HTML/DblPend_SRS.css, code/stable/gamephysics/SRS/HTML/GamePhysics_SRS.css, code/stable/glassbr/SRS/HTML/GlassBR_SRS.css, code/stable/hghc/SRS/HTML/HGHC_SRS.css, code/stable/pdcontroller/SRS/HTML/PDController_SRS.css, code/stable/projectile/SRS/HTML/Projectile_SRS.css, code/stable/sglpend/SRS/HTML/SglPend_SRS.css, code/stable/ssp/SRS/HTML/SSP_SRS.css, code/stable/swhs/SRS/HTML/SWHS_SRS.css, code/stable/swhsnopcm/SRS/HTML/SWHSNoPCM_SRS.css, code/stable/template/SRS/HTML/Template_SRS.css
Closes #3576. It turns out we have CSS rules for spacing between the tables, but it's only applied to DD and TM tables. This PR extends it to GD and IM tables.
=> Apply CSS to GD and IM tables

code/drasil-theory/lib/Theory/Drasil/DataDefinition.hs, code/drasil-theory/lib/Theory/Drasil/InstanceModel.hs
=> Implement `DefinesQuantity` for `InstanceModel` and `DataDefinition`

code/Makefile, code/drasil-website/lib/Drasil/Website/Body.hs, code/scripts/deploy_stage.sh
`make deploy_lite` seems to be largely broken, but with this, it's a bit less broken. 
Creating a PR because @harmanpreet-sagar was running into issues, and this is a decent POC to make it somewhat workable.
When running `make deploy`, there seems to be a dependency on `graphmod` which refers to a bad "dblpendulum" reference! So, it looks like there's some other issues too.
=> Work on clearing up some issues with the deploy stage target

code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/SwiftRenderer.hs, code/stable/dblpend/src/python/InputParameters.py, code/stable/glassbr/src/python/DerivedValues.py, code/stable/glassbr/src/python/InputConstraints.py, code/stable/glassbr/src/python/Interpolation.py, code/stable/pdcontroller/src/python/InputParameters.py, code/stable/projectile/projectile_c_p_nol_b_u_v_d/src/python/Calculations.py, code/stable/projectile/projectile_c_p_nol_b_u_v_d/src/python/InputParameters.py, code/stable/projectile/projectile_s_l_nol_u_u_v_f/src/python/Calculations.py, code/stable/projectile/projectile_s_l_nol_u_u_v_f/src/python/InputConstraints.py, code/stable/projectile/projectile_u_p_l_b_b_c_d/src/python/Projectile.py, code/stable/projectile/projectile_u_p_l_b_wi_v_f/src/python/Projectile.py, code/stable/projectile/projectile_u_p_nol_u_wi_v_d/src/python/Projectile.py, code/stable/swhsnopcm/src/python/InputParameters.py
Contributes to #3221. Removes spaces before the colon in Python files, making it more PEP8 compliant. Changes have been made to `drasil-gool` and stable.
=> Remove space before colon in Python files

.gitignore, code/Makefile, code/scripts/deploy_stage.sh, code/shell.nix, code/stack.yaml
Closes #3646 
Builds on #3657
I'm leaving this as a draft because I want to make sure folder links are plugged in properly. The structure of the `gh-pages` branch is very confusing, we might need to re-evaluate that at some point.
To test this branch:
1. `make clean`,
2. `make deploy`,
3. get a coffee while waiting for (2) to finish -- it takes a crazy amount of time building the PDFs (which it shouldn't even be needing to do!),
4. open `deploy/HTML/index.html` in your local web browser,
5. look at the "HTML" and "PDF" links related to each example, and make sure they don't lead to 404s
=> Fix website deploy script by copying files to expected areas

.gitignore, code/drasil-code/lib/Language/Drasil/Code/Imperative/Doxygen/Import.hs, code/drasil-printers/lib/Language/Drasil/Markdown/CreateMd.hs, code/drasil-utils/lib/Utils/Drasil.hs, code/drasil-utils/lib/Utils/Drasil/Document.hs, code/drasil-utils/package.yaml, code/shell.nix, code/stack.yaml
Builds on #3657 
1. Move very specific things out of `drasil-utils`, such as external
resources.
2. Move generic things related to `Doc`s into `drasil-utils`.
3. Remove `Utils.Drasil.Document` from the list of exposed modules.
=> Clean drasil utils

code/drasil-website/lib/Drasil/Website/Body.hs, code/stable-website/index.html
Bug: Our image was removed from the website with #3662 getting merged in (but I don't think #3662 is the culprit).
It _looks_ like 26aab9ddff29d4b1aa8bd6001e7404effe78a85e introduced a small bug that only surfaced now (I have no idea why) with #3662 getting merged in. Since the locally constructed website doesn't have the same file structure as the one we have up on GitHub (specifically, the local one has `*.html` files nested in an `HTML` folder), it looks like the commit fixed the image displaying on the website locally but broke it on the remote/public website.
=> Website: Prefer showing the public Drasil image over the local

code/drasil-example/README.md
@balacij @smiths Hi Jason and Dr.Smith,
Because the `drasil-example` folder stores all regenerated examples, I think this is the right position to add the mentioned "back" citation. After checking inside folders, I did not find any README files. So the only correct place is in this README file.
Jason, There is one thing I did not find: Where is the Naveen's PD controller github address? I tried to search it before, but I did not find what I expected.
#3562
=> Add citation to original (manual) works from each case study #3562 (Attempt 1)

.gitignore
[`direnv`](https://direnv.net/) is a tool for automatically loading environment variables from a `.envrc` file. I use it to load up the nix shell script. I also use it in general now to load virtual environments for any programming project. Just adding the 'direnv build' folder to our `.gitignore`, so that I don't accidentally commit it.
=> Add `.direnv` to `.gitignore`

code/drasil-data/lib/Data/Drasil/Concepts/Physics.hs, code/stable/projectile/SRS/HTML/Projectile_SRS.html, code/stable/projectile/SRS/JSON/Projectile_SRS.ipynb, code/stable/projectile/SRS/PDF/Projectile_SRS.tex
Fixed the typo "occuring" to "occurring" in the definition of rectilinear in the SRS of the projectile example. Also updated stable with the typo fix.
Closes #3731
=> Issue #3731: Fixed typo in the SRS of the Projectile example

.gitignore, code/Makefile, code/hie.yaml, code/stack.yaml
Contributes to #3700 by writing HIE information necessary for both `stan` and `weeder`
=> Write hie info

code/drasil-docLang/lib/Drasil/DocLang.hs, code/drasil-docLang/lib/Drasil/Sections/Requirements.hs, code/drasil-docLang/package.yaml, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Requirements.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/Requirements.hs, code/drasil-example/pdcontroller/lib/Drasil/PDController/Requirements.hs, code/drasil-example/projectile/lib/Drasil/Projectile/Requirements.hs, code/drasil-example/ssp/lib/Drasil/SSP/Requirements.hs, code/drasil-example/swhs/lib/Drasil/SWHS/Requirements.hs, code/stable/gamephysics/SRS/HTML/GamePhysics_SRS.html, code/stable/gamephysics/SRS/JSON/GamePhysics_SRS.ipynb, code/stable/gamephysics/SRS/PDF/GamePhysics_SRS.tex, code/stable/glassbr/SRS/HTML/GlassBR_SRS.html, code/stable/glassbr/SRS/JSON/GlassBR_SRS.ipynb, code/stable/glassbr/SRS/PDF/GlassBR_SRS.tex, code/stable/pdcontroller/SRS/HTML/PDController_SRS.html, code/stable/pdcontroller/SRS/JSON/PDController_SRS.ipynb, code/stable/pdcontroller/SRS/PDF/PDController_SRS.tex, code/stable/projectile/SRS/HTML/Projectile_SRS.html, code/stable/projectile/SRS/JSON/Projectile_SRS.ipynb, code/stable/projectile/SRS/PDF/Projectile_SRS.tex, code/stable/ssp/SRS/HTML/SSP_SRS.html, code/stable/ssp/SRS/JSON/SSP_SRS.ipynb, code/stable/ssp/SRS/PDF/SSP_SRS.tex, code/stable/swhs/SRS/HTML/SWHS_SRS.html, code/stable/swhs/SRS/JSON/SWHS_SRS.ipynb, code/stable/swhs/SRS/PDF/SWHS_SRS.tex, code/stable/swhsnopcm/SRS/HTML/SWHSNoPCM_SRS.html, code/stable/swhsnopcm/SRS/JSON/SWHSNoPCM_SRS.ipynb, code/stable/swhsnopcm/SRS/PDF/SWHSNoPCM_SRS.tex
Updated the NFR for maintainability to the following description:
> If a likely change is made to the finished software, it will take 10% of the original development time, assuming the same development resources are available.
Change applied to the following examples:
- [GamePhysics](https://jacquescarette.github.io/Drasil/examples/gamephysics/SRS/srs/GamePhysics_SRS.html#Sec:NFRs)
- [GlassBR](https://jacquescarette.github.io/Drasil/examples/glassbr/SRS/srs/GlassBR_SRS.html#Sec:NFRs)
- [NoPCM](https://jacquescarette.github.io/Drasil/examples/nopcm/SRS/srs/NoPCM_SRS.html#Sec:NFRs)
- [PDController](https://jacquescarette.github.io/Drasil/examples/pdcontroller/SRS/srs/PDController_SRS.html#Sec:NFRs)
- [Projectile](https://jacquescarette.github.io/Drasil/examples/projectile/SRS/srs/Projectile_ …
=> Updated NFR for maintainability to refer to code, not SRS: #3288

code/drasil-printers/lib/Language/Drasil/TeX/Monad.hs
Fixes #3759. In some files like Monad.hs we should add 'infix[l|r]' declaration to the operator with explicit precedence rather than giving the operator the default of 9.
=> Added good precedence to Monad.hs

.github/workflows/Build.yaml
`haskell/actions/setup` is deprecated, but there is a maintained fork: `haskell-actions/setup`
=> Update Haskell installation script in GH Workflow

code/drasil-docLang/lib/Drasil/Sections/TraceabilityMandGs.hs, code/drasil-gool/lib/GOOL/Drasil/State.hs, code/drasil-lang/lib/Language/Drasil/Sentence/Fold.hs, code/drasil-lang/lib/Language/Drasil/UnitLang.hs, code/drasil-printers/lib/Language/Drasil/Debug/Print.hs, code/drasil-printers/lib/Language/Drasil/TeX/Print.hs
In large Haskell projects, using `foldl'` can help improve performance and reduce memory usage, making your code more efficient.  In large data structures, using `foldl` can lead to space leaks and stack overflows because it builds up thunks that represent the unevaluated computations of each step. `foldl'` avoids this problem by immediately evaluating the accumulator at each step, which can significantly reduce memory usage for large data structures.
=> STAN-0202 foldl' #3710

code/drasil-website/lib/Drasil/Website/Example.hs, code/stable-website/index.html
Added links to the source code for each generated example on the website. Also updated the stable website to reflect those changes.
NOTE: I followed the existing code to add the new references. However, a problem, which @balacij pointed out, is that each chunk is being created twice. This may require a redesign of the code.
Closes #3668
=> Website: add links to the source code for each generated example #3668

code/Makefile
Contributes to #3557 
Removes an unused target. If we later want to add haddock-docs per package, we can, but leaving boilerplate around is unnecessary. I'm not so convinced that this target is needed.
=> Makefile: Remove an unused "document" package target.

code/Makefile
Contributes to #3557 
Contributes to #3710 
With this, `make projectile_debug` works out of the box, and we won't need to do any `Makefile` hacking for #3710.
=> Makefile: Permit per-example debugging

code/drasil-code/lib/Language/Drasil/Code/Imperative/DrasilState.hs, code/drasil-gool/lib/GOOL/Drasil/ClassInterface.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/CLike.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/SwiftRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/RendererClasses.hs
I noticed that the `listSizeFunc` and `listAppendFunc` methods of the `InternalListFunc` typeclass don't take the list as their parameter.  This is likely because in the OO renderers, these functions are used for everything after the dot (e.g. `l.size()`).  For the Python renderer this already requires a bit of a hack for `listSizeFunc`, as `len` is a function rather than a method in Python.  As we are adding procedural languages this will come up much more often, so I would like to avoid that hack.
These changes will make things much simpler and cleaner as we implement lists in procedural renderers.  This will also help with #3746.
=> Fixed type signatures in `InternalListFunc` typeclass

code/drasil-code/lib/Language/Drasil/Code/Imperative/DrasilState.hs, code/drasil-gool/lib/GOOL/Drasil/ClassInterface.hs, code/drasil-gool/lib/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/CLike.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/CommonPseudoOO.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/Macros.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/SwiftRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/RendererClasses.hs
I added functions to the `List` type class for converting between integers and indices, the idea being that integers are always 0-indexed, but indices match the language's semantics.  I then integrated these functions into the default functions supplied by `LanguagePolymorphic.hs`, `CommonPseudoOO.hs`, and `Macros.hs`.  This makes it very easy for most if not all of list indexing to automatically switch for a language just by changing which function it uses for `intToIndex` and `indexToInt`.  Most languages have one or two functions that they implement on their own, which I did not update to use these new functions, but anything that is shared between languages supports them.
I know in the [issue](https://github.com/JacquesCarette/Drasil/issues/3746#issuecomment-2127853787) …
=> Add support for 1-indexed languages

code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/CommonPseudoOO.hs
Using the new features we added in #3820, I enabled GOOL to add or subtract the `1` 'internally' when adjusting list indices for 1-indexed languages, if the index to be adjusted is a `litInt`.
I didn't have a chance to test it with Julia, but I did a test where I made the Java renderer 1-indexed, and the results looked correct.
=> Added constant-folding to list indexing for 1-indexed languages

code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs
For the `buildClass`, `extraClass`, and `implementingClass` functions, if multiple constructors are given to the Python renderer, it will throw an error.
Closes #3765
=> Added check for multiple constructors to Python

code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/CommonPseudoOO.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/stable/gooltest/cpp/PatternTest/PatternTest.cpp, code/stable/gooltest/csharp/PatternTest/PatternTest.cs, code/stable/gooltest/java/PatternTest/PatternTest/PatternTest.java, code/stable/gooltest/python/PatternTest/PatternTest.py, code/stable/gooltest/swift/PatternTest/main.swift
Both `listAccess` and `listSet` are implemented as a method call in the implementations used by all targets.  I thought this  was weird, as they are only actually method calls for Java and C++.  I changed the implementation to create a value without worrying what kind of call it is.
Another option would be to split these functions up into functions that use methods and functions that don't.  I opted to keep them together, as `listAccess` in particular is large enough that I'd rather not duplicate it, when this way does essentially the same thing.
P.S. I also updated `stable/gooltest`, as I must have forgotten to do so for the last commit.
=> Removed method calls from `listAccess` and `listSet`

code/Makefile
This is really a follow-up to #3803 .
In #3803 we switched to using the Stackage-provided HLint version instead of the latest version of HLint for our CI. However, for our local testing via `make pr_ready`, we neglected to update.
@TRISHI-L This PR should resolve your issue with `make pr_ready` mentioned in #3852. Can you please verify?
=> `make pr_ready`: switch reliance on `hot_hlint` to `hlint`

.github/workflows/Build.yaml, code/drasil-website/lib/Drasil/Website/Example.hs, code/scripts/prepare_deployment.sh, code/stable-website/index.html
Closes #3704 
- Changed the conditions for when the TeX examples are compiled.
1. On a pull request if there is a change in a TeX file within Stable.
2. On a push to `main` (deployment environment).
- Separated the different SRS formats into their respective directories. Previously, all SRS artifacts were copied to `SRS/srs` directory within the `gh-pages` branch. Instead I separated it into `SRS/HTML` and `SRS/PDF`.
- Updated the website with these link changes.
- Added `-j` flag when calling the `make` target to compile the TeX files.
- The `-j` flag allows the parallel execution of jobs. This allows several TeX files to compile concurrently leading to faster times for the overall workfow.
- [**No `-j` Flag**](https://github.com/BilalM04/Drasil/actions/runs/10048556021/job/27772779560): …
=> Fixed PDF deployment

.github/workflows/Build.yaml, code/drasil-printers/lib/Language/Drasil/Format.hs, code/drasil-website/lib/Drasil/Website/Example.hs, code/scripts/prepare_deployment.sh, code/stable-website/index.html
Closes #3857 
Working example on my [forked website](https://bilalm04.github.io/Drasil/).
Workflow Changes:
- Install mdBook using Rust and Cargo.
- Run the `make mdbook_build` target to build the mdBook examples (only on deployment).
- Update deployment script to copy over the built mdBook examples.
Website Changes:
- Generated links to the mdBook examples.
- Modified the existing function to get the SRS file paths to utilize `Format` rather than plain `String`s.
=> Hosting mdBook examples on website

code/drasil-printers/lib/Language/Drasil/Markdown/Helpers.hs, code/drasil-printers/lib/Language/Drasil/Markdown/Print.hs, code/stable/dblpend/SRS/mdBook/src/SecPhysSyst.md, code/stable/dblpend/SRS/mdBook/src/SecSysContext.md, code/stable/dblpend/SRS/mdBook/src/SecTraceMatrices.md, code/stable/gamephysics/SRS/mdBook/src/SecSysContext.md, code/stable/gamephysics/SRS/mdBook/src/SecTraceMatrices.md, code/stable/glassbr/SRS/mdBook/src/SecAppendix.md, code/stable/glassbr/SRS/mdBook/src/SecPhysSyst.md, code/stable/glassbr/SRS/mdBook/src/SecSysContext.md, code/stable/glassbr/SRS/mdBook/src/SecTraceMatrices.md, code/stable/pdcontroller/SRS/mdBook/src/SecPhysSyst.md, code/stable/pdcontroller/SRS/mdBook/src/SecSysContext.md, code/stable/pdcontroller/SRS/mdBook/src/SecTraceMatrices.md, code/stable/projectile/SRS/mdBook/src/SecPhysSyst.md, code/stable/projectile/SRS/mdBook/src/SecSysContext.md, code/stable/projectile/SRS/mdBook/src/SecTraceMatrices.md, code/stable/sglpend/SRS/mdBook/src/SecPhysSyst.md, code/stable/sglpend/SRS/mdBook/src/SecSysContext.md, code/stable/sglpend/SRS/mdBook/src/SecTraceMatrices.md, code/stable/ssp/SRS/mdBook/src/SecPhysSyst.md, code/stable/ssp/SRS/mdBook/src/SecSysContext.md, code/stable/ssp/SRS/mdBook/src/SecTraceMatrices.md, code/stable/swhs/SRS/mdBook/src/SecPhysSyst.md, code/stable/swhs/SRS/mdBook/src/SecSysContext.md, code/stable/swhs/SRS/mdBook/src/SecTraceMatrices.md, code/stable/swhsnopcm/SRS/mdBook/src/SecPhysSyst.md, code/stable/swhsnopcm/SRS/mdBook/src/SecSysContext.md, code/stable/swhsnopcm/SRS/mdBook/src/SecTraceMatrices.md
I noticed that figures in mdBook are not automatically centered. While images that span the full width seem centered, smaller images often appear misaligned. For example, in [sglpend](https://jacquescarette.github.io/Drasil/examples/sglpend/SRS/mdBook/book/SecPhysSyst.html) and [gamephysics](https://jacquescarette.github.io/Drasil/examples/gamephysics/SRS/mdBook/book/SecSysContext.html).
In this PR, I've centered the images by adding an additional attribute in the div tag that wraps the images and captions.
=> Centered figures in mdBook

code/drasil-example/ssp/lib/Drasil/SSP/GenDefs.hs, code/drasil-lang/lib/Language/Drasil.hs, code/drasil-lang/lib/Language/Drasil/Chunk/Relation.hs, code/drasil-lang/lib/Language/Drasil/UID.hs, code/drasil-theory/lib/Theory/Drasil/DataDefinition.hs, code/drasil-theory/lib/Theory/Drasil/ModelKinds.hs
As discussed in https://github.com/JacquesCarette/Drasil/issues/3524 , the `uid` field was previously implemented as a `Lens`, which allowed for modification. However, after switching `uid` to a `Getter`, the `uid` field became read-only, which affected functions that relied on setting the `uid` value, such as `addRelToCC`.
- Removed `addRelToCC` Function: The `addRelToCC` function, which previously allowed modification of the `uid` field using the `set` function, has been removed due to its incompatibility with the read-only `Getter` implementation.
- Direct RelationConcept Creation: Modified the `mobShr` definition to create RelationConcept directly with appropriate properties using functions like `makeRC` instead of relying on the removed `addRelToCC` function.
=> Make the `HasUID` lens read-only

wiki/Debugging-in-Drasil.md
While reviewing the [section in the wiki](https://github.com/JacquesCarette/Drasil/wiki/Debugging-in-Drasil#solution), I noticed two minor formatting issues. Specifically, the second and fourth points are not properly segmented.
=> Fixed unsegmented points in wiki section

code/Makefile
This ensures that the generated code for GOOL tests matches that in `stable/gooltest`.  `codegenTest` is already in our CI from the looks of it, so this should prevent the cases we've had where `build/gooltest` doesn't match `stable/gooltest`.
Next steps:
- We should add `codegenTest_gen` to `make pr_ready`.
- We probably don't want to add `codegenTest` to `make pr_ready`, as it requires that the local machine has the compilers installed for all compiled targets.
- We still don't have an automatic way of stabilize the `build/gooltest` folder.  We need to add a `make codegenTest_stabilize` option.
Closes #3678 
Contributes to #3387
=> Modified the `codegenTest` target to check `diff` with `stable`

code/stack.yaml
I realized that the `.hie` files aren't in ghc 9.6.6 (they are still in ghc 9.2.8). You need to use `stack upgrade` before using STAN so the `.hie` files are made in ghc 9.6.6. In order for STAN to work on the new version I also had to add `extensions` to `allow-newer-deps` for STAN to work.
=> small update for STAN

code/drasil-code/lib/Language/Drasil/Code/Imperative/GenerateGOOL.hs
Apparently I missed this earlier.  It looks like this is one last function in `drasil-code` that can be safely shared between the GOOL and GProc renderers.  It doesn't loosen any threads unfortunately, but it's something at least.
=> Removed `fCallProc`

code/drasil-printers/lib/Language/Drasil/TeX/Helpers.hs, code/drasil-printers/lib/Language/Drasil/TeX/Monad.hs, code/drasil-printers/lib/Language/Drasil/TeX/Preamble.hs, code/drasil-printers/lib/Language/Drasil/TeX/Print.hs, code/stable/dblpend/SRS/PDF/DblPend_SRS.tex, code/stable/gamephysics/SRS/PDF/GamePhysics_SRS.tex, code/stable/glassbr/SRS/PDF/GlassBR_SRS.tex, code/stable/hghc/SRS/PDF/HGHC_SRS.tex, code/stable/pdcontroller/SRS/PDF/PDController_SRS.tex, code/stable/projectile/SRS/PDF/Projectile_SRS.tex, code/stable/sglpend/SRS/PDF/SglPend_SRS.tex, code/stable/ssp/SRS/PDF/SSP_SRS.tex, code/stable/swhs/SRS/PDF/SWHS_SRS.tex, code/stable/swhsnopcm/SRS/PDF/SWHSNoPCM_SRS.tex
Contributes to #718 
- Detailed description in https://github.com/JacquesCarette/Drasil/issues/718#issuecomment-2263312386.
- Adjusts block equations within definition tables to 80% of the page width if they overflow.
- Adjusts standard block equations to the full page width if they overflow.
To save you the trouble of compiling, here is a precompiled example of [SSP_SRS.pdf](https://github.com/user-attachments/files/16512476/SSP_SRS.pdf) for your reference.
=> Resize long expressions in LaTeX to prevent overflow

code/Makefile
- I moved the `diff` check added in #3909 from `codegenTest_gen` to `codegenTest_diff`.  This is more consistent with other `make` rules, and is needed for `codegenTest_stabilize`.
- I added `codegenTest_diff` to `make all`.  This means it will be run whenever `make` and `make pr_ready` are run, and ensures that the GOOL tests are checked when we run the main Drasil tests.
- I created `codegenTest_stabilize`.  This allows us to easily update `stable/gooltest` when we need to.
Contributes to #3387
=> Added better support for GOOL tests in Makefile

code/drasil-code/lib/Language/Drasil/Chunk/CodeBase.hs, code/drasil-code/lib/Language/Drasil/Code/Imperative/Build/Import.hs, code/drasil-code/lib/Language/Drasil/Code/Imperative/DrasilState.hs, code/drasil-code/lib/Language/Drasil/CodeSpec.hs, code/drasil-docLang/lib/Drasil/DocumentLanguage.hs, code/drasil-docLang/lib/Drasil/DocumentLanguage/TraceabilityMatrix.hs, code/drasil-gool/lib/Drasil/GOOL/State.hs, code/drasil-lang/lib/Language/Drasil/CodeExpr/Extract.hs, code/drasil-lang/lib/Language/Drasil/Expr/Extract.hs, code/drasil-lang/lib/Language/Drasil/ModelExpr/Extract.hs, code/drasil-lang/lib/Language/Drasil/Sentence/Extract.hs, code/drasil-printers/lib/Language/Drasil/Debug/Print.hs, code/drasil-utils/lib/Utils/Drasil/Lists.hs, code/scripts/ClassInstDepGen.hs, code/scripts/SourceCodeReaderT.hs
This is a continuation of #3761. I changed any `nub`s that were used on things that are `Ord` to `nubOrd`. This is becuase `nub` has O(n^2) and `nubOrd` has O(n\log(n)).
=> change some `nub` to `nubOrd`

code/drasil-gool/lib/Drasil/GOOL/LanguageRenderer/CommonPseudoOO.hs, code/drasil-gool/lib/Drasil/GOOL/LanguageRenderer/JuliaRenderer.hs, code/stable/gooltest/julia/FileTests/FileTests.jl, code/stable/gooltest/julia/HelloWorld/HelloWorld.jl, code/stable/gooltest/julia/NameGenTest/NameGenTest.jl
There were two problems I discovered while implementing ODEs in Julia:
- Importing external libraries didn't work correctly.
- The types of empty lists was `Any` instead of its specific type.
- Julia automatically assigns `[]` the type `Array{Any}`, which is problematic if you need its type to be `Array{Float64}`, for example.  I fixed it to add the type if the list is empty.  For example, an empty list of doubles is now represented as `Float64[]`.  This is in line with how the Julia REPL prints lists, and removes the potential of type errors.
This PR fixes those two issues.
Note on the `listDec` from `CommonPseudoOO.hs`: I'm not exactly sure why this only affects Julia, but previously it was giving lists the wrong level of type nesting (e.g. `List<List<Integer>>` instead of …
=> Made fixes to the Julia renderer

code/drasil-printers/lib/Language/Drasil/TeX/Helpers.hs, code/drasil-printers/lib/Language/Drasil/TeX/Preamble.hs, code/drasil-printers/lib/Language/Drasil/TeX/Print.hs, code/stable/dblpend/SRS/PDF/DblPend_SRS.tex, code/stable/gamephysics/SRS/PDF/GamePhysics_SRS.tex, code/stable/glassbr/SRS/PDF/GlassBR_SRS.tex, code/stable/hghc/SRS/PDF/HGHC_SRS.tex, code/stable/pdcontroller/SRS/PDF/PDController_SRS.tex, code/stable/projectile/SRS/PDF/Projectile_SRS.tex, code/stable/sglpend/SRS/PDF/SglPend_SRS.tex, code/stable/ssp/SRS/PDF/SSP_SRS.tex, code/stable/swhs/SRS/PDF/SWHS_SRS.tex, code/stable/swhsnopcm/SRS/PDF/SWHSNoPCM_SRS.tex
Contributes to #718
Builds on #3910
In #3910, I used the `resizebox` package to resize the block equations; however, I have switched to the `adjustbox` package as I found it to be better overall.
- No need for a scale parameter.
- `adjustbox` is "smarter" and can automatically determine when scaling is necessary. 
- This resulted in the removal of the `if` conditions in the custom LaTeX command.
- We also don't need `lo'` and the `InDef` and `OutDef` params as the package automatically handles the scaling factor.
- `adjustbox` can resize an expression directly; no need for a `savebox`. 
Rendered PDF remains the same as #3910. Switching to the `adjustbox` package cleaned up both the generated TeX code and the written Drasil code.
=> Switched LaTeX package from `resizebox` to `adjustbox` for resizing expressions

code/drasil-gool/lib/Drasil/GOOL/LanguageRenderer/JuliaRenderer.hs
I split up a few functions, added some comments, etc.
Notes:
- I noticed that the `getUsing` function and things relating to it are only used by the C++ renderer, so I removed them from the Julia renderer.
- I removed the `TODO: think about splitting up CodeType` comment.  I'm not sure if that is the way we should go, and if it is then it should be an issue, not a comment.
- I removed the block comment describing Julia's abstract types.  I do still think that adding sub-types to GOOL would be a neat project, but there's no reason for that comment to be there.
- I created the `jlGlobalDec` function that `jlAssign`, `jlSubAssign`, and `jlIncrement` all use.
- I removed spaces at the end of lines and evened out the spacing in one or two places.
=> Cleaned up a bit of the Julia renderer

code/drasil-gool/lib/Drasil/GOOL/LanguageRenderer/CppRenderer.hs, code/drasil-gool/lib/Drasil/GOOL/State.hs
I removed `iterators` from `MethodState` since as said in #3919 the changes that I made to the Cpp render `forEach` loop makes the iterators field in `MethodState` unnecessary.
Closes #3919
=> removed `iterators` from `MethodState`

code/drasil-code/test/HelloWorld.hs, code/stable/gooltest/cpp/HelloWorld/HelloWorld.cpp, code/stable/gooltest/csharp/HelloWorld/HelloWorld.cs, code/stable/gooltest/java/HelloWorld/HelloWorld/HelloWorld.java, code/stable/gooltest/julia/HelloWorld/HelloWorld.jl, code/stable/gooltest/python/HelloWorld/HelloWorld.py, code/stable/gooltest/swift/HelloWorld/main.swift
This ensures that sets are being tested.
It also shows that sets are not implemented properly in Julia, as `HelloWorld.jl` crashes when  run.  I will create a separate issue for this.
=> Added basic set tests to `HelloWorld.hs`

code/stable/gooltest/julia/HelloWorld/HelloWorld.jl
Closes #3966 
The issue is related to the need for manual stabilization of the Julia code, especially concerning the GOOL tests.
=> Fix Build Failure

.github/workflows/Lint.yaml
and it is broken -- `libtinfo5` is not found anymore on Ubuntu LTS 24.04.
We can probably simplify this further (see https://github.com/haskell-actions/hlint-setup ), but that can be a subsequent PR.
=> We don't need the hack anymore

code/drasil-data/lib/Data/Drasil/Concepts/Physics.hs
Contributes to #3710
Contributes to #2873
For both, by removing a self-reference that would cause issue for enabling `StrictData`.
Notes:
1. The solution itself is not clean. What I actually want to encode is something more like: `S "the" ++ phrase change ++ S "in" ++ phrase velocity ++ S "of a" ++ phrase rigidBody` (pseudocode) -- i.e., something that references both "change" and "velocity".
2. I'm struggling to quickly encode (1) because I'm having trouble understanding how the `Sentence` and `NounPhrase` system works.
3. Writing a ticket about (2) is more work than writing the demo code, pushing a PR, and receiving feedback.
@samm82 IIRC, you have some experience with this system. Do you have any suggestions for how I can improve this?
=> Remove chgInVelocity's self-reference.

code/Makefile
Contributes to #3710 
Contributes to #2873
The macros weren't expanding for some reason. They worked perfectly fine on my Linux laptop the last time I tried, but they don't currently work on my Mac. So, I tightened up the code related to marking the debugging flags.
This contributes to those aforementioned tickets because debugging `<<loop>>`s begs GHC's time and allocation profiling report (`.prof` files).
=> Fix `make debug`.

code/drasil-build/package.yaml, code/drasil-codeLang/package.yaml, code/drasil-data/package.yaml, code/drasil-docLang/package.yaml, code/drasil-example/dblpend/package.yaml, code/drasil-example/gamephysics/package.yaml, code/drasil-example/glassbr/package.yaml, code/drasil-example/hghc/package.yaml, code/drasil-example/pdcontroller/package.yaml, code/drasil-example/projectile/package.yaml, code/drasil-example/sglpend/package.yaml, code/drasil-example/sglpend/stack.yaml, code/drasil-example/ssp/package.yaml, code/drasil-example/swhs/package.yaml, code/drasil-example/swhsnopcm/package.yaml, code/drasil-example/template/package.yaml, code/drasil-gen/package.yaml, code/drasil-metadata/package.yaml, code/drasil-printers/package.yaml, code/drasil-sysinfo/package.yaml, code/drasil-theory/package.yaml, code/drasil-utils/package.yaml, code/drasil-website/package.yaml
Contributes to #3710, where non-strict data is a very common warning noted by `stan`.
Contributes to #2873, where we need `StrictData` to build maps of chunks with 'sane checks on insertion'.
I also manually set the language specification to `Haskell2010`. That's the default that `hpack` uses, but I think that being explicit is good here. Aside: I'm also okay with upgrading this to `GHC2021` or the more recent 2024 spec.
=> Enable StrictData wherever our tests don't fail

code/drasil-example/glassbr/lib/Drasil/GlassBR/Unitals.hs, code/stable/glassbr/SRS/HTML/GlassBR_SRS.html, code/stable/glassbr/SRS/Jupyter/GlassBR_SRS.ipynb, code/stable/glassbr/SRS/PDF/GlassBR_SRS.tex, code/stable/glassbr/SRS/mdBook/src/SecTermDefs.md
Contributes to #3710 
Contributes #2873
This is following discussion of #4006. Considering there's a DataDefinition that explains that $SD$ is defined by $SD_x, SD_y, SD_z$, I _think_ it's safe to make this PR, but let me know if there's a better solution!
=> Remove reference loop in standoffdistance/GlassBR.

code/drasil-code/package.yaml, code/drasil-database/package.yaml, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Body.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/Body.hs, code/drasil-example/ssp/lib/Drasil/SSP/Body.hs, code/drasil-example/swhs/lib/Drasil/SWHS/Body.hs, code/drasil-example/swhsnopcm/lib/Drasil/SWHSNoPCM/Body.hs, code/drasil-gen/lib/Language/Drasil/Dump.hs, code/drasil-lang/lib/Language/Drasil.hs, code/drasil-lang/lib/Language/Drasil/Document.hs
Contributes to #3710 and #2873
Builds on #4003, #4007, and #4012
* Enables `StrictData` for `drasil-code` and `drasil-database`. The former was made possible by #4012 but I was hesitant to enable it until we've enabled SD in -database too. The latter is possible by the next point.
* All ChunkDB 'section tables' are automatically filled in our code generation step. For some examples, it was manually filled too. That manual code had a mutual definition chain between the system information and a chunkdb.
=> Enable `StrictData` in `-code` and `-database`, and gut out `section` pre-filling in some ChunkDBs

code/drasil-database/lib/Database/Drasil.hs, code/drasil-database/lib/Database/Drasil/ChunkDB.hs, code/drasil-database/lib/Database/Drasil/Dump.hs, code/drasil-docLang/lib/Drasil/DocumentLanguage.hs, code/drasil-docLang/lib/Drasil/DocumentLanguage/Definitions.hs, code/drasil-docLang/lib/Drasil/DocumentLanguage/TraceabilityGraph.hs, code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Body.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/Body.hs, code/drasil-example/hghc/lib/Drasil/HGHC/Body.hs, code/drasil-example/pdcontroller/lib/Drasil/PDController/Body.hs, code/drasil-example/projectile/lib/Drasil/Projectile/Body.hs, code/drasil-example/projectile/lib/Drasil/Projectile/Lesson/Body.hs, code/drasil-example/sglpend/lib/Drasil/SglPend/Body.hs, code/drasil-example/ssp/lib/Drasil/SSP/Body.hs, code/drasil-example/swhs/lib/Drasil/SWHS/Body.hs, code/drasil-example/swhsnopcm/lib/Drasil/SWHSNoPCM/Body.hs, code/drasil-example/template/lib/Drasil/Template/Body.hs, code/drasil-gen/lib/Language/Drasil/Dump.hs, code/drasil-lang/lib/Language/Drasil.hs, code/drasil-lang/lib/Language/Drasil/Document.hs, code/drasil-printers/lib/Language/Drasil/Debug/Print.hs, code/drasil-website/lib/Drasil/Website/Body.hs
Contributes to #2873 
Builds on #4003, #4007, #4012, and #4014. However, he only commit necessary to audit is ~~84fb89b7b0cb4dab11cf0079c66b6e08a721ec3a~~ af38c6aedcb82474a3f6f16861ebe4e520222331, assuming you're okay with the changes on the PRs this PR builds on. Why does this PR build on these PRs? Because I removed all use `SectionTable` field filling in #4014, which is dependent on the others.
Is this a step back or is this a step forward? I tend towards the latter, for two reasons:
1. I don't think that a `Section` is something we want in the ChunkDB. It is display knowledge, and all discussion of it should be restricted to 'printer'-related code.
2. With us making significant progress towards enabling `StrictData` everywhere, our next issue to focus on with #2873 is the UID …
=> Remove unused `SectionTable` from ChunkDB.

code/drasil-database/lib/Database/Drasil/ChunkDB.hs, code/drasil-database/lib/Database/Drasil/Dump.hs, code/drasil-docLang/lib/Drasil/DocumentLanguage.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Body.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/GenDefs.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/References.hs, code/drasil-example/ssp/lib/Drasil/SSP/Body.hs, code/drasil-example/swhs/lib/Drasil/SWHS/Body.hs, code/drasil-example/swhs/lib/Drasil/SWHS/DataDefs.hs, code/drasil-example/swhs/lib/Drasil/SWHS/GenDefs.hs, code/drasil-example/swhs/lib/Drasil/SWHS/IMods.hs, code/drasil-example/swhs/lib/Drasil/SWHS/References.hs, code/drasil-example/swhs/lib/Drasil/SWHS/TMods.hs, code/drasil-example/swhsnopcm/lib/Drasil/SWHSNoPCM/Body.hs, code/drasil-example/swhsnopcm/lib/Drasil/SWHSNoPCM/IMods.hs, code/drasil-example/swhsnopcm/lib/Drasil/SWHSNoPCM/References.hs
Contributes to #2873 
This is a bit of a silly PR, and it might not even be the correct way to go about things. The title sounds big and mighty, but it's really not doing much.
This PR:
* Reorders the tables in the `ChunkDB`, sorting by `Chunk` vs `Not a Chunk`.
* Removes automatic extraction of `Reference`s from `Sentence`s rendered in the SRS.
* Removes `Reference`s from being considered as part of "knowledge maps" we dump in `Dump.hs`, hence excluding `Reference`s when calculating conflicting `UID`s.
The goal of this PR is to remove as many UID conflicts of `Reference`s with other chunks as possible. This PR does that by silently ignoring them, kicking the rock of actually fixing this down the road.
The demotion of `Reference` to "not a chunk" is more of a semantic change. As I …
=> Demote references table to 'not a chunk table' in `ChunkDB`

code/drasil-database/lib/Database/Drasil.hs, code/drasil-database/lib/Database/Drasil/ChunkDB.hs, code/drasil-database/lib/Database/Drasil/Dump.hs, code/drasil-docLang/lib/Drasil/DocumentLanguage.hs, code/drasil-docLang/lib/Drasil/DocumentLanguage/Definitions.hs, code/drasil-docLang/lib/Drasil/DocumentLanguage/TraceabilityGraph.hs, code/drasil-printers/lib/Language/Drasil/Markdown/Config.hs
Contributes to #2873
This is similar to #4022. I will annotate the PR.
Here is an excerpt from `DblPend`'s output debug information, and unfortunately, this information is largely unused as a 'chunk'.
```
LabelledContent:
----------------------------------------------------------------------------------------------------
UID                           Short Name                    Content Type
----------------------------------------------------------------------------------------------------
aR                            aspectRatio                   Definition or Model
demandq                       calofDemand                   Definition or Model
eqTNTChar                     eqTNTW                        Definition or Model
glassTypeFac                  gTF …
```
=> Demote 'LabelledContent' to 'not a chunk' until they're dealt with properly

code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Body.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/Body.hs, code/drasil-example/hghc/lib/Drasil/HGHC/Body.hs, code/drasil-example/pdcontroller/lib/Drasil/PDController/Body.hs, code/drasil-example/projectile/lib/Drasil/Projectile/Body.hs, code/drasil-example/projectile/lib/Drasil/Projectile/Lesson/Body.hs, code/drasil-example/sglpend/lib/Drasil/SglPend/Body.hs, code/drasil-example/ssp/lib/Drasil/SSP/Body.hs, code/drasil-example/swhs/lib/Drasil/SWHS/Body.hs, code/drasil-example/swhsnopcm/lib/Drasil/SWHSNoPCM/Body.hs, code/drasil-example/template/lib/Drasil/Template/Body.hs, code/drasil-gen/lib/Language/Drasil/TypeCheck.hs, code/drasil-sysinfo/lib/SysInfo/Drasil/SystemInformation.hs, code/drasil-website/lib/Drasil/Website/Body.hs
It's not used, and it's not clear how it should be used.
=> Remove unused _concepts field in SystemInformation

code/drasil-database/lib/Database/Drasil/Dump.hs
Contributes to #2873
This PR corrects the record for which things we have duplicate `UID`s for. Previously we were dumping the wrong `concepts` table! We were dumping the concept instances and concept chunks from the same concept instances table.
Taking `gamephysics` as an example, the new `problematic_seeds.json` file contains items of the following form:
```json
{
"M_T": [
"symbols",
"concepts"
],
...
"theory:accj": [
"instanceModels",
"concepts"
],
...
}
```
=> Fix chunk dump bug

code/drasil-printers/lib/Language/Drasil/HTML/CSS.hs, code/drasil-printers/lib/Language/Drasil/HTML/Helpers.hs, code/drasil-printers/lib/Language/Drasil/HTML/Print.hs, code/stable-website/index.css, code/stable/dblpend/SRS/HTML/DblPend_SRS.css, code/stable/dblpend/SRS/HTML/DblPend_SRS.html, code/stable/gamephysics/SRS/HTML/GamePhysics_SRS.css, code/stable/gamephysics/SRS/HTML/GamePhysics_SRS.html, code/stable/glassbr/SRS/HTML/GlassBR_SRS.css, code/stable/glassbr/SRS/HTML/GlassBR_SRS.html, code/stable/hghc/SRS/HTML/HGHC_SRS.css, code/stable/pdcontroller/SRS/HTML/PDController_SRS.css, code/stable/pdcontroller/SRS/HTML/PDController_SRS.html, code/stable/projectile/SRS/HTML/Projectile_SRS.css, code/stable/projectile/SRS/HTML/Projectile_SRS.html, code/stable/sglpend/SRS/HTML/SglPend_SRS.css, code/stable/sglpend/SRS/HTML/SglPend_SRS.html, code/stable/ssp/SRS/HTML/SSP_SRS.css, code/stable/ssp/SRS/HTML/SSP_SRS.html, code/stable/swhs/SRS/HTML/SWHS_SRS.css, code/stable/swhs/SRS/HTML/SWHS_SRS.html, code/stable/swhsnopcm/SRS/HTML/SWHSNoPCM_SRS.css, code/stable/swhsnopcm/SRS/HTML/SWHSNoPCM_SRS.html, code/stable/template/SRS/HTML/Template_SRS.css, code/stable/template/SRS/HTML/Template_SRS.html
Contributes to #4046 
Not 100% sure this is what was meant when the bibliography labels should be text, let me know if anything should be changed.
Screenshot of output:
=> Bibliography labels match links

code/drasil-printers/lib/Language/Drasil/HTML/Helpers.hs, code/drasil-printers/lib/Language/Drasil/HTML/Print.hs, code/stable/dblpend/SRS/HTML/DblPend_SRS.html, code/stable/gamephysics/SRS/HTML/GamePhysics_SRS.html, code/stable/glassbr/SRS/HTML/GlassBR_SRS.html, code/stable/pdcontroller/SRS/HTML/PDController_SRS.html, code/stable/projectile/SRS/HTML/Projectile_SRS.html, code/stable/sglpend/SRS/HTML/SglPend_SRS.html, code/stable/ssp/SRS/HTML/SSP_SRS.html, code/stable/swhs/SRS/HTML/SWHS_SRS.html, code/stable/swhsnopcm/SRS/HTML/SWHSNoPCM_SRS.html, code/stable/template/SRS/HTML/Template_SRS.html
Closes #4046 (based on [this comment](https://github.com/JacquesCarette/Drasil/pull/4056#discussion_r2083239546))
Visually the output is the same, however I cleaned up the code a bit. Instead of having a new function `descWrap` I just generalized `refwrap` to work with different tags rather than just div to avoid repeating ourselves as much.
Also, instead of having `reference-label` attached to the list items, I realized it was not actually needed and just reverted to the old ids to fix the hyperlinks.
=> Fix bibliography hyperlinks

code/drasil-example/glassbr/lib/Drasil/GlassBR/Body.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/Symbols.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/Unitals.hs
Closes #4064 
I am currently in the process of placing individual changes that contribute to #4036 in separate PRs, this fixes some duplicates related to `inputs` and `inputDataConstraints` having duplicate UIDs.
=> Fix input UID duplicates being added to GlassBR ChunkDB

code/drasil-example/glassbr/lib/Drasil/GlassBR/Body.hs
Contributes to #4036 
Also kind of helps with #4095 since it now has the `progName` equivalent in the `symbMap`, which is what most of the other examples do.
=> Remove `con` from GlassBR `symbMap` and add `glassBR` individually, matching the structure of other examples

code/Makefile
Previously, it only worked correctly for the 'debug' target, not the 'X_debug' targets. By splitting the environment variables into a separate PHONY target, we can make sure that the environment variables are setup for both.
=> Makefile: Fix how [_]debug target sets up the debugging variables

code/Makefile
Contributes to JacquesCarette/Drasil#3557
=> Makefile: Ignore 'make debug'-related junk when running diffs

code/drasil-example/dblpend/package.yaml, code/drasil-example/gamephysics/package.yaml, code/drasil-example/glassbr/package.yaml, code/drasil-example/hghc/package.yaml, code/drasil-example/pdcontroller/package.yaml, code/drasil-example/projectile/package.yaml, code/drasil-example/sglpend/package.yaml, code/drasil-example/ssp/package.yaml, code/drasil-example/swhs/package.yaml, code/drasil-example/swhsnopcm/package.yaml, code/drasil-example/template/package.yaml, code/drasil-website/package.yaml
Contributes to #4130
This will allow HLS to show more redundant* warnings in editor.
=> Enable -Wall and -Wredundant-constraints by package.yaml config.

code/drasil-example/glassbr/lib/Drasil/GlassBR/Symbols.hs
Contributes to #4130 -- This should also be the last warning for #4131's CI to pass.
This was an unused import warning.
=> Clear up another GlassBR warning.

code/drasil-example/glassbr/lib/Drasil/GlassBR/Body.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/Symbols.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/Unitals.hs
Contributes to #4036 
Implements #4108 without using the hack (fixes around 80% of the remaining duplicates, a bit more work to this PR will be added)
=> Exclude terms also found in `thisSymbols`

code/Makefile
Closes #4130
The CI _should_ fail if I did this right.
=> Ensure `-Wall` is is still enabled when stackArgs is passed in to Makefile.

code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Body.hs, code/drasil-example/sglpend/lib/Drasil/SglPend/Body.hs, code/drasil-example/ssp/lib/Drasil/SSP/Body.hs, code/drasil-example/swhs/lib/Drasil/SWHS/Body.hs
Contributes to #4126 
~~Builds on https://github.com/JacquesCarette/Drasil/pull/4139~~
What's odd to me about this is that only these examples had their theories registered in the `ChunkDB`! Whatever is going on here needs further investigation (at least before we merge this PR).
(I'm only marking this PR as "ready for review" to get the CI to run.)
=> Avoid registering IdeaDicts extracted from theories in the ChunkDB.

code/drasil-database/lib/Database/Drasil/ChunkDB.hs
Contributes to #4126 
This hack was previously there because our data definitions have unique UIDs, unlike the majority of our chunks at the moment. So extracting `IdeaDict`s was necessary for the `termResolve` function to find an `IdeaDict`.
This change is possible because https://github.com/JacquesCarette/Drasil/commit/ac3ec2db97a96d39107849c89f7118715bcffecf makes the use of the "term map" really about "getting terms" rather than `IdeaDict`s.
=> Remove hack for automatically extracting IdeaDicts from DataDefinitions.

code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Body.hs
I noticed that when `acronyms` was removed in #4147 and replaced by `twoD` and `threeD` (since they were the only acronyms not duplicated), there actually already exists a list with these `CI`s which could be added instead, such as how it is added in projectile also.
=> Use physicCon' instead of twoD and threeD

code/drasil-example/pdcontroller/lib/Drasil/PDController/Body.hs
=> PDController: Remove duplicate `UnitDefn`-related Terms

code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Body.hs
This removes most `QuantityDict` v `IdeaDict`-related duplicate `UID`s but not all. The rest need to be investigated more delicately.
=> GamePhysics: Remove undeniably duplicate `QuantityDict`-related `IdeaDict`s

code/drasil-example/glassbr/lib/Drasil/GlassBR/Body.hs
This removes most `QuantityDict` v `IdeaDict`-related duplicate `UID`s but not all. The rest need to be investigated more delicately.
=> GlassBR: Remove undeniably duplicate `QuantityDict`-related `IdeaDict`s

code/drasil-example/hghc/lib/Drasil/HGHC/Body.hs
For HGHC, this removes all the problematic cross-table `UID` conflicts!
=> HGHC: Remove undeniably duplicate `QuantityDict`-related  `IdeaDict`s

code/drasil-example/pdcontroller/lib/Drasil/PDController/Body.hs
This removes most, but not all, `UID` conflicts between the `QuantityDict`s table and the `IdeaDict`s table.
=> PDController: Remove undeniably duplicate `QuantityDict`-related `IdeaDict`s

code/drasil-example/ssp/lib/Drasil/SSP/Body.hs
Unfortunately, this only removes about 60 conflicts. There are still ~150 more in SSP!
=> SSP: Remove undeniably duplicate `QuantityDict`-related `IdeaDict`s

code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Body.hs
=> GamePhysics: Move weakly used `ConceptChunk`s (only used for their `IdeaDict`s) to `ConceptChunk`s table.

code/drasil-example/ssp/lib/Drasil/SSP/Body.hs
=> SSP: Move weakly used `ConceptChunk`s (only used for their `IdeaDict`s) to `ConceptChunk`s table.

code/drasil-example/swhs/lib/Drasil/SWHS/Body.hs
=> SWHS: Move weakly used `ConceptChunk`s (only used for their `IdeaDict`s) to `ConceptChunk`s table.

code/drasil-example/swhsnopcm/lib/Drasil/SWHSNoPCM/Body.hs
=> SWHSNoPCM: Move weakly used `ConceptChunk`s (only used for their `IdeaDict`s) to `ConceptChunk`s table.

code/drasil-example/template/lib/Drasil/Template/Body.hs
=> Template: Move weakly used `ConceptChunk`s (only used for their `IdeaDict`s) to `ConceptChunk`s table.

code/drasil-example/hghc/lib/Drasil/HGHC/Body.hs
=> HGHC: Move weakly used `ConceptChunk`s (only used for their `IdeaDict`s) to `ConceptChunk`s table.

code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs
The issue with this PR is that it breaks `make debug`'s ability to write the chunk content tables. Why? Because some `ConceptChunk`s contain references to `Reference`s that don't exist until the SRS code generator starts doing work. #4196 avoids this issue by not rendering the definition `Sentence`s.
=> DblPend: Move weakly used ConceptChunks (only used for their `IdeaDict`s) to ConceptChunks table.

code/drasil-data/lib/Data/Drasil/Quantities/Physics.hs
=> `frequency` is added twice in `physicscon`, remove duplicate

code/drasil-example/projectile/lib/Drasil/Projectile/Body.hs
Contributes to #4126 
The chunk `outputMessage` is already added in the `unitalQuants` list, and is not needed in the `unitalIdeas` list. `unitalIdeas` had this chunk as its only entry, so it can be removed as well.
=> Projectile: `outputMessage` chunk is already added in symbol table, unecessary in term table

code/drasil-lang/lib/Language/Drasil.hs, code/drasil-lang/lib/Language/Drasil/Chunk/Quantity.hs
Cleans up an unused QuantityDict constructor working towards removing QuantityDict entirely.
=> Remove unused `codeVC` QuantityDict constructor

code/drasil-example/dblpend/lib/Drasil/DblPend/GenDefs.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/TMods.hs, code/drasil-example/sglpend/lib/Drasil/SglPend/GenDefs.hs, code/drasil-lang/lib/Language/Drasil/Chunk/Concept.hs, code/drasil-theory/lib/Theory/Drasil/MultiDefn.hs
Contributes to #4284 
`mkQuant'` originally took an abbreviation, and all of our ConceptChunk constructors that I have been using to build DefinedQuantityDicts did not have the ability to take an abbreviation. This fixes that issue.
=> Capture abbreviations in ConceptChunk constructors

code/drasil-example/projectile/package.yaml
As per the title, just removing a duplicate dependency entry.
=> Projectile: Remove duplicate `drasil-system` dependency.

code/drasil-example/ssp/lib/Drasil/SSP/Body.hs
Contributes to #2873 
As simple as it gets: the symbols are all added to the symbol table already.
=> SSP: Remove duplicate added DQDs (inter-map).

code/drasil-example/projectile/lib/Drasil/Projectile/Concepts.hs, code/drasil-example/projectile/lib/Drasil/Projectile/Lesson/Body.hs
Contributes to #2873 and #4320 
With this PR, there should be absolutely no across-table UID conflicts, excluding LabelledContent and Reference, which require some more involved work.
=> Lesson Plan: Remove duplicate across-table UID-conflicting chunks.

code/drasil-example/pdcontroller/lib/Drasil/PDController/Unitals.hs
First of many PRs that will eventually eradicate `nounPhraseSent`. Start with the easy ones, such as this.
=> Fix pdcontroller uses of bad `nounPhraseSent` combinator

code/drasil-example/ssp/lib/Drasil/SSP/Body.hs, code/drasil-example/ssp/lib/Drasil/SSP/Defs.hs, code/stable/ssp/SRS/HTML/SSP_SRS.html, code/stable/ssp/SRS/Jupyter/SSP_SRS.ipynb, code/stable/ssp/SRS/PDF/SSP_SRS.tex, code/stable/ssp/SRS/mdBook/src/SecTAbbAcc.md
=> SSP: Remove unused 3D acronym from table of abb/accs.
