code/Example/Drasil/DocumentLanguage.hs
=> Fix the intro of IM section for SSD.

code/Example/Drasil/GlassBR/Body.hs, code/Language/Drasil/Chunk/Attribute/Core.hs
=> Remove Uses

code/Language/Drasil/Chunk/Attribute/Core.hs
=> Removed Rationale

code/Language/Drasil/HTML/Print.hs, code/stable/gamephys/Chipmunk_SRS.html, code/stable/glassbr/GlassBR_SRS.html, code/stable/nopcm/NoPCM_SRS.html, code/stable/ssp/SSP_SRS.html, code/stable/swhs/SWHS_SRS.html, code/stable/tiny/SRS.html
Reorders the HTML preamble to be more standards compliant and update the doctype to HTML5 (which looks cleaner too!)
=> Html preamble changes

code/Data/Drasil/Utils.hs, code/Example/Drasil/GlassBR/DataDefs.hs, code/Example/Drasil/GlassBR/IMods.hs, code/Example/Drasil/HGHC/HeatTransfer.hs, code/Example/Drasil/SWHS/DataDefs.hs, code/Language/Drasil.hs, code/Language/Drasil/Chunk/Attribute.hs, code/Language/Drasil/Chunk/Attribute/Core.hs, code/Language/Drasil/Chunk/Attribute/References.hs, code/Language/Drasil/Chunk/DefinedQuantity.hs, code/Language/Drasil/Chunk/Eq.hs, code/Language/Drasil/Chunk/GenDefn.hs, code/Language/Drasil/Chunk/InstanceModel.hs, code/Language/Drasil/Chunk/Theory.hs, code/Language/Drasil/Classes.hs, code/drasil.cabal
@szymczdm @JacquesCarette Is this the correct way to go about this adding `SourceRef` from #537? I left `Attributes` in the data definitions just as a placeholder until we're ready to fully remove it, and I have the constructors pass in empty lists for now, again, as placeholders until we remove `Attributes`. Then `References` will be passed in instead.
=> Adding SourceRef

code/Example/Drasil/SSP/BasicExprs.hs, code/Example/Drasil/SSP/DataDefs.hs, code/Example/Drasil/SSP/GenDefs.hs, code/Example/Drasil/SSP/IMods.hs, code/drasil.cabal
This came from conversation #540
=> Transferred re-usable `Expr` functions into BasicExprs.hs 

code/Language/Drasil/Chunk/Eq.hs, code/Language/Drasil/Chunk/GenDefn.hs, code/Language/Drasil/Chunk/InstanceModel.hs, code/Language/Drasil/Chunk/Theory.hs
Base branch was already broken. Created this branch to work on issue #549 (i.e. break off original branch into smaller branch in an attempt to shrink the size of the current PR).
=> Implementing changes for Issue #549

code/Example/Drasil/SWHS/Body.hs
=> Improved imports in SWHS/Body.hs

code/Example/Drasil/Sections/SolutionCharacterSpec.hs, code/Language/Drasil.hs, code/Language/Drasil/Chunk/AssumpChunk.hs, code/Language/Drasil/Chunk/Change.hs, code/Language/Drasil/Chunk/Citation.hs, code/Language/Drasil/Chunk/Code.hs, code/Language/Drasil/Chunk/CommonIdea.hs, code/Language/Drasil/Chunk/Goal.hs, code/Language/Drasil/Chunk/NamedIdea.hs, code/Language/Drasil/Chunk/PhysSystDesc.hs, code/Language/Drasil/Chunk/ReqChunk.hs, code/Language/Drasil/Chunk/Theory.hs, code/Language/Drasil/ChunkDB.hs, code/Language/Drasil/Classes.hs, code/Language/Drasil/Code/Imperative/Import.hs, code/Language/Drasil/Expr.hs, code/Language/Drasil/Printing/Import.hs, code/Language/Drasil/Reference.hs, code/Language/Drasil/UID.hs, code/drasil.cabal
This pull request makes progress towards Issue #562, specifically the first bullet point outlined by @JacquesCarette in [comment 6](https://github.com/JacquesCarette/Drasil/issues/562#issuecomment-393544664).
=> Change instances of String to UID.

code/Example/Drasil/Sections/SolutionCharacterSpec.hs, code/Language/Drasil.hs, code/Language/Drasil/Chunk/AssumpChunk.hs, code/Language/Drasil/Chunk/Change.hs, code/Language/Drasil/Chunk/Citation.hs, code/Language/Drasil/Chunk/Code.hs, code/Language/Drasil/Chunk/CommonIdea.hs, code/Language/Drasil/Chunk/Concept.hs, code/Language/Drasil/Chunk/Concept/Core.hs, code/Language/Drasil/Chunk/Goal.hs, code/Language/Drasil/Chunk/NamedIdea.hs, code/Language/Drasil/Chunk/PhysSystDesc.hs, code/Language/Drasil/Chunk/ReqChunk.hs, code/Language/Drasil/Chunk/Theory.hs, code/Language/Drasil/Chunk/UnitaryConcept.hs, code/Language/Drasil/ChunkDB.hs, code/Language/Drasil/Classes.hs, code/Language/Drasil/Code/Imperative/Import.hs, code/Language/Drasil/Expr.hs, code/Language/Drasil/Printing/Import.hs, code/Language/Drasil/Reference.hs, code/Language/Drasil/UID.hs, code/drasil.cabal
This PR builds on #571. It aims to address bullet point 2 on [comment 6](https://github.com/JacquesCarette/Drasil/issues/562#issuecomment-393544664) of #562. There is one comment I added to [commit 6b73704](https://github.com/JacquesCarette/Drasil/commit/6b737048cf59fa194ed4e175e6ac7c00168ea438#r29259141) about a change uncertainty that should be addressed before merging.
=> Removing Recursion in DefAndDomain

code/Example/Drasil/SWHS/DataDefs.hs
=> Improved imports in SWHS/DataDefs.hs

code/Example/Drasil/SWHS/GenDefs.hs
=> Improved imports in SWHS/GenDefs.hs

code/Example/Drasil/Sections/Introduction.hs
=> Improved imports for Sections/Intorduction.hs

code/Example/Drasil/GamePhysics/Body.hs
=> Import game phys

code/Example/Drasil/SSP/Requirements.hs, code/Example/Drasil/SSP/TMods.hs, code/Example/Drasil/SSP/Unitals.hs
=> Improved imports in SSP/Requirements.hs, TMods.hs, and Unitals.hs

code/Example/Drasil/SSP/IMods.hs, code/Example/Drasil/SSP/Main.hs, code/Example/Drasil/SSP/References.hs
=> Improved imports in SPP/IMods.hs, Main.hs, and References.hs

code/Example/Drasil/Sections/GeneralSystDesc.hs
=> Improved import Sections/GeneralSystDesc

code/Example/Drasil/SSP/GenDefs.hs, code/Example/Drasil/SSP/Goals.hs
=> Improved imports in SSP/GenDefs.hs and Goals.hs

code/Example/Drasil/Sections/AuxiliaryConstants.hs
=> Improved imports in Sections/AuxilaryConstants

code/Example/Drasil/SSP/DataDefs.hs, code/Example/Drasil/SSP/Defs.hs
=> Improved imports in SSP/DataDefs.hs and Defs.hs

code/Example/Drasil/SSP/Assumptions.hs, code/Example/Drasil/SSP/BasicExprs.hs, code/Example/Drasil/SSP/Body.hs
#569 -> alphabetize and specify
=> Improved imports in SSP/Assumptions.hs, BasicExprs.hs, and Body.hs

code/Example/Drasil/GlassBR/Units.hs
=> Improved imports in Units.hs

code/Example/Drasil/GlassBR/Main.hs, code/Example/Drasil/GlassBR/TMods.hs, code/Example/Drasil/GlassBR/Unitals.hs
=> Improved imports in GlassBR/Main.hs, TMods.hs, and Unitals.hs

code/Example/Drasil/NoPCM/Unitals.hs
=> Improved imports in NoPCM/Unitals

code/Example/Drasil/SWHS/IMods.hs
=> Improved imports in SWHS/IMods.hs

code/Example/Drasil/GlassBR/Assumptions.hs
=> Improved imports in GlassBR/Assumptions.hs

code/Example/Drasil/GlassBR/ModuleDefs.hs, code/Example/Drasil/GlassBR/References.hs, code/Example/Drasil/GlassBR/Symbols.hs
=> Improved imports in GlassBR/ModuleDefs.hs, References.hs, and Symbols.hs

code/Example/Drasil/GlassBR/Concepts.hs, code/Example/Drasil/GlassBR/DataDefs.hs, code/Example/Drasil/GlassBR/IMods.hs
=> Improved imports in GlassBR/Concepts.hs, DataDefs.hs, and IMods.hs

code/Example/Drasil/NoPCM/Body.hs
=> Imporved imports in NoPCM/Body.hs

code/Example/Drasil/GlassBR/Body.hs
Specified, as per #569, and alphabetized for ease of use later.
=> Improved imports in GlassBR/Body.hs

code/Example/Drasil/Sections/Requirements.hs
=> Improved imports in Sections/Requirements

code/Example/Drasil/Sections/ScopeOfTheProject.hs
=> Improved imports in Sections/ScopeOfTheProject

code/Example/Drasil/Sections/SolutionCharacterSpec.hs
=> Improved imports Sections/SolutionCharacterSpec

code/Example/Drasil/Sections/GeneralSystDesc.hs, code/stable/glassbr/GlassBR_SRS.html, code/stable/glassbr/GlassBR_SRS.tex, code/stable/nopcm/NoPCM_SRS.html, code/stable/nopcm/NoPCM_SRS.tex, code/stable/ssp/SSP_SRS.html, code/stable/ssp/SSP_SRS.tex, code/stable/swhs/SWHS_SRS.html, code/stable/swhs/SWHS_SRS.tex
As mentioned in smiths/caseStudies#91, the first sentence under the general system description section needed to be updated to be more accurate.
This change was quite easy to make.
Working on updating stable to reflect the appropriate changes so that the logs are not non-empty.
=> General System Description Intro Update

code/Example/Drasil/Sections/SpecificSystemDescription.hs
=> Improved imports in Sections/SpecificSystemDescription

code/Example/Drasil/Sections/Stakeholders.hs
=> Improved imports in Sections/Stakeholders

code/Example/Drasil/Sections/TableOfAbbAndAcronyms.hs
=> Improved imports in Sections/TableOfAbbAndScronyms

code/Example/Drasil/HGHC/HGHC.hs, code/Example/Drasil/HGHC/Main.hs
=> Improved imports in HGHC/HGHC.hs and Main.hs

code/Language/Drasil/Chunk/Concept/Core.hs, code/Language/Drasil/Chunk/Constrained.hs, code/Language/Drasil/Chunk/DefinedQuantity.hs, code/Language/Drasil/Chunk/GenDefn.hs, code/Language/Drasil/Chunk/InstanceModel.hs, code/Language/Drasil/Chunk/Relation.hs, code/Language/Drasil/Chunk/Theory.hs, code/Language/Drasil/Chunk/UncertainQuantity.hs, code/Language/Drasil/Chunk/Unital.hs, code/Language/Drasil/Chunk/UnitaryConcept.hs, code/Language/Drasil/Unit.hs
Addresses [this comment](https://github.com/JacquesCarette/Drasil/pull/610#commitcomment-29303401) from #610.
=> Updated formatting where instance of ConceptDomain are defined.

code/Example/Drasil/Sections/TableOfUnits.hs
=> Improved imports in Sections/TableOfUnits.hs

code/Example/Drasil/Sections/SolutionCharacterSpec.hs, code/stable/gamephys/Chipmunk_SRS.html, code/stable/gamephys/Chipmunk_SRS.tex
Is a continuation of the work done in #606. This case study was not updated with the rest because duplication of the introduction went undetected earlier.
=> Update GamePhysics' GSD Intro

code/Example/Drasil/Sections/TraceabilityMandGs.hs
=> Improved imports in Sections/TraceabilityMandGs.hs

code/Example/Drasil/GamePhysics/Concepts.hs
=> Improved imports in GamePhysics/Concepts.hs

code/Example/Drasil/GamePhysics/DataDefs.hs, code/Example/Drasil/GamePhysics/GDef.hs
#569 -> Alphabetized and specified
=> Improved imports in GamePhysics/DataDefs.hs and GDefs.hs

code/Example/Drasil/GamePhysics/IMods.hs, code/Example/Drasil/GamePhysics/Main.hs, code/Example/Drasil/GamePhysics/References.hs
#569 -> alpabetized and specified
=> Improved imports in GamePhysics/IMods.hs, Main.hs, and References.hs

code/Example/Drasil/GamePhysics/TMods.hs, code/Example/Drasil/GamePhysics/Unitals.hs
=> Improved imports in GamePhysics/TMods.hs and Unitals.hs

code/Example/Drasil/DocumentLanguage/RefHelpers.hs, code/Example/Drasil/DocumentLanguage/TraceabilityMatrix.hs
=> Improved imports in DocumentLanguage/RefHelpers.hs and TraceabilityMatrix.hs

code/Example/Drasil/DocumentLanguage.hs
=> Improved imports in DocumentLanguage.hs

code/Example/Drasil/SRS.hs
=> Improved imports in SRS.hs

code/Data/Drasil/Units/Chemistry.hs, code/Data/Drasil/Units/PhysicalProperties.hs, code/Data/Drasil/Units/Physics.hs, code/Data/Drasil/Units/SolidMechanics.hs, code/Data/Drasil/Units/Thermodynamics.hs
=> Improved imports in Data.Units files

code/Example/Drasil/NoPCM/Body.hs, code/stable/nopcm/NoPCM_SRS.html
As per issue https://github.com/smiths/caseStudies/issues/59#issuecomment-396358608, I just want to get this reviewed before I change stable as required.
=> Adjusted NoPCM to match manual

code/Data/Drasil/Quantities/Math.hs, code/Data/Drasil/Quantities/PhysicalProperties.hs
=> Improved imports in Quantities/Math.hs and PhysicalProperties.hs

code/Data/Drasil/Quantities/Physics.hs
=> Improved imports in Quantities/Physics.hs

code/Data/Drasil/Quantities/SolidMechanics.hs, code/Data/Drasil/Quantities/Thermodynamics.hs
=> Improved imports in Quantities/SolidMechanics.hs and Thermodynamics.hs

code/Data/Drasil/Concepts/PhysicalProperties.hs, code/Data/Drasil/Concepts/SolidMechanics.hs
=> Improved imports in Concepts/PhysicalProperties.hs and SolidMechanics.hs

code/Data/Drasil/Citations.hs, code/Data/Drasil/People.hs, code/Data/Drasil/Software/Products.hs, code/Data/Drasil/Utils.hs
#569 -> Alphabetized and specified
=> Improved imports in Data.Drasil.Software.Products, Data.Drasil.Citations, People, and Utils

code/Language/Drasil/ChunkDB.hs, code/Language/Drasil/Classes.hs
=> Improved imports in ChunkDB and Classes

code/Language/Drasil/Document.hs, code/Language/Drasil/Expr.hs
#569 -> Alphabetized and specified
=> Improve imports in Document and Expr

code/Language/Drasil/Chunk/InstanceModel.hs, code/Language/Drasil/Expr/Extract.hs, code/Language/Drasil/Expr/Math.hs, code/Language/Drasil/Expr/Precedence.hs
=> Improve imports in Expr Subfolder

code/Language/Drasil/Misc.hs, code/Language/Drasil/NounPhrase.hs
#569 -> Alphabetized and Specified
=> Improved imports in Misc and NounPhrase

code/Language/Drasil/Reference.hs
#569 -> Alphabetized and specified
=> Improved imports in Reference

code/Language/Drasil/Spec.hs, code/Language/Drasil/Symbol.hs
=> Improved imports in Spec and Symbol

code/Language/Drasil/SystemInformation.hs
=> Improved imports in SystemInformation

code/Example/Drasil/GlassBR/Body.hs, code/stable/glassbr/GlassBR_SRS.html, code/stable/glassbr/GlassBR_SRS.tex
As per #675, GlassBR was updated in stable and generated to reflect changes in smiths/caseStudies@65cc95b.
=> Updated GlassBR SRS

code/Example/Drasil/GlassBR/Body.hs, code/Language/Drasil/Chunk/Eq.hs, code/Language/Drasil/Chunk/UncertainQuantity.hs, code/Language/Drasil/Chunk/Unital.hs, code/Language/Drasil/Chunk/Unitary.hs, code/Language/Drasil/Chunk/UnitaryConcept.hs, code/Language/Drasil/Chunk/VarChunk.hs, code/stable/glassbr/GlassBR_SRS.html, code/stable/glassbr/GlassBR_SRS.tex
=> Improve remaining files in chunk folder

code/Example/Drasil/GamePhysics/Concepts.hs, code/Example/Drasil/GlassBR/Concepts.hs, code/Example/Drasil/NoPCM/Body.hs, code/Example/Drasil/NoPCM/Definitions.hs, code/Example/Drasil/SSP/Defs.hs, code/Example/Drasil/SWHS/Body.hs, code/stable/gamephys/Chipmunk_SRS.html, code/stable/gamephys/Chipmunk_SRS.tex, code/stable/glassbr/GlassBR_SRS.html, code/stable/glassbr/GlassBR_SRS.tex, code/stable/nopcm/NoPCM_SRS.html, code/stable/nopcm/NoPCM_SRS.tex, code/stable/ssp/SSP_SRS.html, code/stable/ssp/SSP_SRS.tex, code/stable/swhs/SWHS_SRS.html, code/stable/swhs/SWHS_SRS.tex
Fixed issue in the comments of smiths/caseStudies#100, and updated stable in all examples.
=> Add UC to Tables of Acronyms and Abbreviations

code/Example/Drasil/GlassBR/Body.hs, code/stable/glassbr/GlassBR_SRS.html, code/stable/glassbr/GlassBR_SRS.tex
Barring changes made in 1b90f8c on the unlikelyGlassBR branch, section names were made more specific as per #708 - note - this might need revisiting once unlikelyGlassBR is merged
=> Made Section Names More Specific in GlassBR

code/Example/Drasil/NoPCM/Body.hs, code/Example/Drasil/SWHS/Body.hs, code/Example/Drasil/SWHS/DataDefs.hs, code/Example/Drasil/SWHS/IMods.hs, code/Example/Drasil/SWHS/Requirements.hs, code/Example/Drasil/SWHS/TMods.hs
This is the completed continuation of #709
=> Replaced Section Names in SWHS with improvements

code/Example/Drasil/NoPCM/Body.hs, code/Example/Drasil/NoPCM/GenDefs.hs
This is the complete renaming of the section names in the NoPCM example
=> Improved section names in NoPCM

code/Language/Drasil/Classes.hs, code/Language/Drasil/Document.hs, code/Language/Drasil/Label.hs, code/Language/Drasil/Label/Core.hs
#719. This needs to be merged in for more progress to be made in #695.
=> HasRefAddress and its lens' implementation

code/Example/Drasil/GlassBR/README.md
As per #730 - some files have since been deleted, so I removed them from the README. Feel free to double check that my descriptions are correct.
=> Updated GlassBR README

code/Makefile, code/log_check.sh
=> Renamed log.log to Tiny_log.log

code/Language/Drasil/Chunk/Concept.hs, code/Language/Drasil/Chunk/Concept/Core.hs, code/Language/Drasil/Reference.hs
1. Implements `ConceptInstance`
2. Updates locations which previously took `ConceptChunk` to instead take `ConceptInstance`.
3. Remove `ShortName` from `ConceptChunk` (Should unblock a part of #695)
=> Implement ConceptInstance. (#562)

code/Language/Drasil/Chunk/DataDefinition.hs, code/drasil.cabal
=> Create DataDefinition data type and file

code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GlassBR/Assumptions.hs, code/drasil-example/Drasil/HGHC/HGHC.hs, code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/SSP/Assumptions.hs, code/drasil-example/Drasil/SWHS/Assumptions.hs, code/drasil-lang/Language/Drasil/Reference.hs
=> Expose ConceptMap input in RDB constructor.

code/drasil-code/Language/Drasil/Generate.hs
=> Improved imports in Generate.hs

code/drasil-lang/Language/Drasil/Development/Unit.hs
=> Improved imports in Unit.hs

code/drasil-code/Language/Drasil/Code.hs
=> Improved imports in Code.hs

code/drasil-code/Language/Drasil/Code/DataDesc.hs
=> Improved imports in DataDesc.hs

code/drasil-code/Language/Drasil/Code/Imperative/Helpers.hs
=> Improved imports in Imperative/Helpers.hs

code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs
=> Improved imports in CppRenderer.hs

code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs
=> Improved imports in CShareRenderer.hs

code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/GOOLRenderer.hs
=> Improved improts in GOOLRenderer.hs

code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs
=> Improved imports in JavaRenderer.hs

code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/ObjectiveCRenderer.hs
=> Improved imports in ObjectiveCRenderer.hs

code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/LuaRenderer.hs
=> Improved imports in LuaRenderer.hs

code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs
=> Improved import in PythonRenderer.hs

code/drasil-code/Language/Drasil/Code/Imperative/Parsers/ConfigParser.hs
=> Improved imports in ConfigParser.hs

code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Chunk/Concept.hs
=> Added constructor for ConceptInstance

code/drasil-lang/Language/Drasil/HTML/Helpers.hs
=> Improved imports in HTML/Helpers.hs

code/drasil-lang/Language/Drasil/HTML/Monad.hs
=> Improved imports in HTML/Monad.hs

code/drasil-lang/Language/Drasil/HTML/Print.hs
=> Improved imports in HTML/Print.hs

code/drasil-lang/Language/Drasil/Make/Helpers.hs
=> Improved import in Make/Helpers.hs

code/drasil-lang/Language/Drasil/Make/Import.hs
=> Improved imports in Make/Import.hs

code/drasil-lang/Language/Drasil/Make/Print.hs
=> Improved imports in Make/Print.hs

code/drasil-lang/Language/Drasil/Printing/AST.hs
=> Improved imports in Printing/AST.hs

code/drasil-lang/Language/Drasil/Printing/Helpers.hs
=> Improved imports in Printing/Helpers.hs

code/drasil-lang/Language/Drasil/Printing/Import.hs
=> Improved imports in Printing/Import.hs

code/drasil-lang/Language/Drasil/TeX/Helpers.hs
=> Improved imports in TeX/Helpers.hs

code/drasil-lang/Language/Drasil/Printing/LayoutObj.hs
=> Improved imports in Printing/LayoutObj.hs

code/drasil-lang/Language/Drasil/TeX/Monad.hs
=> Improved imports in TeX/Monad.hs

code/drasil-lang/Language/Drasil/TeX/Preamble.hs
=> Improved imports in TeX/Preamble.hs

code/drasil-lang/Language/Drasil/TeX/Print.hs
=> Improved imports in TeX/Print.hs

code/drasil-data/Data/Drasil/SI_Units.hs
=> Improved imports in SI_Units.hs

code/drasil-lang/Language/Drasil/Chunk/DataDefinition.hs
=> Updated scope definition for DD

code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/SWHS/Body.hs
=> Bringing back uncommented import lists

code/drasil-docLang/Drasil/DocLang.hs, code/drasil-docLang/Drasil/DocLang/SRS.hs, code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-docLang/Drasil/Sections/GeneralSystDesc.hs, code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
=> Added more section description languages

code/drasil-example/Drasil/GlassBR/DataDefs.hs, code/drasil-example/Drasil/GlassBR/Unitals.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html
=> Fixed duplication error in ToS of GlassBR

code/drasil-example/Drasil/HGHC/HGHC.hs, code/drasil-example/Drasil/HGHC/HeatTransfer.hs
=> Propagated the use of DataDefinition into HGHC (tiny)

code/drasil-data/Data/Drasil/Citations.hs, code/drasil-docLang/Drasil/DocumentLanguage/Definitions.hs, code/drasil-example/Drasil/GlassBR/DataDefs.hs, code/drasil-example/Drasil/GlassBR/References.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
=> Reintroduced source fields into Data Definitions

code/drasil-example/Drasil/GlassBR/Unitals.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
As per issue #948 
closes #948
=> Data constraints update in GlassBR

code/drasil-example/Drasil/NoPCM/Body.hs, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
As per https://github.com/smiths/caseStudies/issues/100
=> No pcm unlikely chngs

code/drasil-docLang/Drasil/DocumentLanguage/Definitions.hs, code/drasil-example/Drasil/GlassBR/Concepts.hs, code/drasil-example/Drasil/GlassBR/DataDefs.hs, code/drasil-example/Drasil/GlassBR/IMods.hs, code/drasil-lang/Language/Drasil/Chunk/InstanceModel.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
This is for adding a missing reference in the source field of an instance model (Probability of Glass Breakage) and other changes mentioned in issue #939 
closes #939
=> Added source fields to IMs according to issue #939

code/drasil-lang/Language/Drasil/Reference.hs
=> Make ConceptInstance Referable.

code/Makefile, code/drasil-example/drasil-example.cabal, code/stable/tiny/SRS/Tiny_SRS.tex, code/stable/tiny/Website/Tiny_SRS.html
As discussed in yesterday's meeting, I updated stable for Tiny and changed the Makefile to compile Tiny, then GlassBR.
=> Made Discussed Fixes to Tiny

code/drasil-example/Drasil/GlassBR/DataDefs.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html
This is a missed change from issue #948.
=> Removing conversion factor

code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/GlassBR/TMods.hs, code/drasil-example/Drasil/GlassBR/Unitals.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html
=> [Small PR] Improved GlassBR Code

code/drasil-example/Drasil/GamePhysics/DataDefs.hs, code/drasil-example/Drasil/GlassBR/DataDefs.hs, code/drasil-example/Drasil/GlassBR/Unitals.hs, code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SWHS/DataDefs.hs, code/drasil-example/Drasil/SWHS/Unitals.hs, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Chunk/DataDefinition.hs
To better represent what it does. Closes #926
=> [Small PR] Renamed 'mkDataDef' to 'mkQuantDef'

code/drasil-example/drasil-example.cabal, code/drasil-gen/Language/Drasil/Generate.hs, code/drasil-gen/drasil-gen.cabal, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Chunk/Attribute.hs, code/drasil-lang/Language/Drasil/Chunk/ShortName.hs, code/drasil-lang/Language/Drasil/Label.hs, code/drasil-lang/Language/Drasil/RefTypes.hs, code/drasil-lang/Language/Drasil/Reference.hs, code/drasil-printers/Language/Drasil/HTML/Print.hs, code/drasil-printers/Language/Drasil/Printing/Import.hs, code/drasil-printers/Language/Drasil/TeX/Helpers.hs, code/drasil-printers/Language/Drasil/TeX/Print.hs, code/drasil-printers/drasil-printers.cabal, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html
This PR is the last associated with #562, and relevant to #985. This PR depends on #992.
This pull request adds the infrastructure for deferred `ShortName`s and uses them for adding prefixes to `ConceptInstance`.
=> Add prefixes to ConceptInstances

code/drasil-docLang/Drasil/DocLang.hs, code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-docLang/drasil-docLang.cabal, code/drasil-example/Drasil/GlassBR/Assumptions.hs, code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/GlassBR/Changes.hs, code/drasil-example/Drasil/GlassBR/Requirements.hs, code/drasil-example/drasil-example.cabal, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html
This PR converts ALUR in GlassBR to instead use `ConceptInstance`. Like the others, assumption `ConceptInstance`s are present but not yet plugged-in.
For tracking, this PR is part of #985 and improves the appearance of #1001, although does not necessarily encode the lists better.
=> GlassBR ConceptInstance

code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GamePhysics/Changes.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html
This PR is part of #985 and switches GamePhys to `ConceptInstance`. 
Like the rest of the examples, assumptions have `ConceptInstance` variants which are not used yet.
=> Use ConceptInstance in GamePhys.

code/drasil-example/Drasil/SSP/Body.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
Update SSP case to adopt the correct enumeration for Physical System Section.
As mentioned in #698 .
=> Update SSP case to adopt the correct enumeration for Physical System

code/drasil-example/Drasil/GlassBR/Assumptions.hs, code/drasil-example/Drasil/GlassBR/DataDefs.hs, code/drasil-example/Drasil/GlassBR/IMods.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html
This PR did the same thing as PR #1032, but for glassBR case.
=> Move referencing relations in assumptions to each chunk and remove them from Assumptions

code/drasil-example/Drasil/GlassBR/Assumptions.hs, code/drasil-example/Drasil/GlassBR/DataDefs.hs, code/drasil-example/Drasil/GlassBR/IMods.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html
Add assumption references explicitly to chunks in Note field for GlassBR case.
=> Move assumption references to each chunk

code/drasil-example/Drasil/GamePhysics/DataDefs.hs, code/drasil-example/Drasil/GamePhysics/IMods.hs, code/drasil-example/Drasil/GlassBR/IMods.hs, code/drasil-example/Drasil/SSP/IMods.hs, code/drasil-example/Drasil/SWHS/DataDefs.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
In this PR,
some missing `DataDefinitions` were added back.
=> Add more references of DataDefinitions for all cases

code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Sentence.hs, code/drasil-lang/Language/Drasil/Sentence/Extract.hs, code/drasil-printers/Language/Drasil/HTML/Print.hs, code/drasil-printers/Language/Drasil/Printing/AST.hs, code/drasil-printers/Language/Drasil/Printing/Import.hs, code/drasil-printers/Language/Drasil/TeX/Print.hs
that will eventually replace Ref. Right now, nothing uses it.
=> implement a new Ref2 in Sentence (and Printing.AST)

code/drasil-data/Data/Drasil/People.hs, code/drasil-example/Drasil/SSP/Assumptions.hs, code/drasil-example/Drasil/SSP/BasicExprs.hs, code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SSP/IMods.hs, code/drasil-example/Drasil/SSP/Labels.hs, code/drasil-example/Drasil/SSP/References.hs, code/drasil-example/Drasil/SSP/Unitals.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
IM1 and its derivation were updated to match the manual version. As part of this, a new assumption and two new data definitions were added, as they are used in the derivation.
=> SSP IM1 Revision

.travis.yml, code/Makefile, code/log_check.sh
This PR exposes a new make flag/variable (`NOISY`) which is used to print any example diffs to stdout. Moreover it sets this flag to `yes` when building on Travis.
=> Printout diff logs on Travis (#1101)

code/drasil-example/Drasil/GamePhysics/Assumptions.hs, code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GamePhysics/DataDefs.hs, code/drasil-example/Drasil/GamePhysics/Unitals.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html
Added new Data Definition "Torque"
I think I need a new symbol r?
r : is a position vector of the point where the force is applied, measured from the axis of rotation. I used another symbol "r_OB" for now.
=> Gamephy srs

code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SSP/GenDefs.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This pull request adds the effective normal force GD to the SSP example.
=> SSP Effective Normal Force GD

code/Makefile
This PR finishes refactoring makefile targets. In the process this PR addresses #1088.
=> More Makefile Refactoring

code/drasil-example/drasil-example.cabal, code/drasil-printers/Language/Drasil/TeX/Helpers.hs, code/drasil-printers/Language/Drasil/TeX/Print.hs, code/drasil-printers/drasil-printers.cabal, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/tiny/SRS/Tiny_SRS.tex
This PR is small and makes the necessary changes to enable compilation of TeX code generated by Drasil.
=> Building TeX

code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SSP/Unitals.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This PR changes the case of explicit grouping discussed in #1120 by de-inlining, to match how we've handled explicit grouping previously. I made the new fixme DDs in a similar style to the previous ones so that it is very clear that they are all related to the same issue (explicit grouping).
=> SSP Explicit Grouping

code/drasil-example/Drasil/SSP/Body.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This small PR updates the User Characteristics section of SSP to match manual.
=> SSP User Characteristics

code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-docLang/Drasil/TraceTable.hs, code/drasil-example/Drasil/GamePhysics/DataDefs.hs, code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SSP/Defs.hs
This PR cleans up some build warnings. It is "designed" to compliment #1148.
=> Cleanup Warnings

code/drasil-data/Data/Drasil/Concepts/Physics.hs, code/drasil-data/Data/Drasil/Concepts/SolidMechanics.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SSP/DataDesc.hs, code/drasil-example/Drasil/SSP/Defs.hs, code/drasil-example/Drasil/SSP/GenDefs.hs, code/drasil-example/Drasil/SSP/IMods.hs, code/drasil-example/Drasil/SSP/TMods.hs, code/drasil-example/Drasil/SSP/Unitals.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This updates the Terminology and Definitions section of SSP to match manual.
=> SSP Terminology and Definitions

.travis.yml, code/.hlint.yaml, code/drasil-code/Language/Drasil/CodeSpec.hs, code/drasil-data/Data/Drasil/SentenceStructures.hs, code/drasil-example/Drasil/GamePhysics/DesignDec/Vector.hs, code/drasil-example/Drasil/GamePhysics/GDef.hs, code/drasil-lang/Language/Drasil/SystemInformation.hs
This PR enables HLint on Travis builds. 
If the lint fails, the build fails. 
I also updated the version of HLint I'm using locally (to match the one on Travis which will always pull the latest release) and fixed new lints as the result of the `Parse Error` false positives being fixed.
=> HLint on Travis Builds

code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SSP/Defs.hs, code/drasil-example/Drasil/SSP/Goals.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This updates the Goal Statements section of SSP to match manual.
=> SSP Goal Statements

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-example/Drasil/SSP/Assumptions.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SSP/Unitals.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This updates the Assumptions section of SSP to match manual.
=> SSP Assumptions

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-data/Data/Drasil/Units/Physics.hs, code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SSP/GenDefs.hs, code/drasil-example/Drasil/SSP/TMods.hs, code/drasil-example/Drasil/SSP/Unitals.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This PR updates the Theoretical Models section of SSP to match manual.
=> SSP Theoretical Models

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-docLang/Drasil/Sections/SpecificSystemDescription.hs, code/drasil-example/Drasil/SSP/Assumptions.hs, code/drasil-example/Drasil/SSP/BasicExprs.hs, code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SSP/GenDefs.hs, code/drasil-example/Drasil/SSP/Unitals.hs, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
This PR updates the General Definitions section  of SSP to match manual, with the possible exception of the issue discussed in #1199. Depending on the resolution of that issue, I can update this PR or create a new one or do nothing.
=> SSP General Definitions

code/drasil-example/Drasil/SSP/Changes.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This PR updates the Likely and Unlikely changes of SSP to match manual.
=> SSP Changes

code/drasil-lang/Language/Drasil/Chunk/README.md, notes/DrasilPotentialTasks.txt
Minor PR with updates to documentation for #700 and #918.
Also, I like that `master` is a protected branch now 😁 - makes it a bit of a headache for small changes but a LOT less of a headache for big ones!
=> Documentation Update

code/drasil-data/Data/Drasil/Concepts/Documentation.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SSP/Goals.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This PR makes `ConceptInstance`s out of the goal statements for SSP, so that the goal statements are `Referable`, which is needed for #1205.
=> SSP Referable Goals

code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SSP/Defs.hs, code/drasil-example/Drasil/SSP/GenDefs.hs, code/drasil-example/Drasil/SSP/IMods.hs, code/drasil-example/Drasil/SSP/Unitals.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
With my changes to SSP just about done, this PR does various minor fixes or clean-up tasks that slipped through during my first pass or didn't fit into any previous PR.
=> SSP Cleanup

code/drasil-data/Data/Drasil/Concepts/Documentation.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SSP/Goals.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/drasil-example/Drasil/SWHS/Goals.hs, code/drasil-example/Drasil/SWHS/IMods.hs, code/drasil-example/drasil-example.cabal, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
This PR adds the additional intro paragraph to SWHS to match manual (see #1205). It also makes the goal statements `ConceptInstance`s since they needed to be referred to in this paragraph.
=> SWHS Instance Models Intro Paragraph

code/drasil-example/Drasil/SSP/Unitals.hs
=> [Small PR] Removed Unused Helper Strings in SSP Unitals

code/drasil-example/Drasil/GlassBR/DataDefs.hs, code/drasil-example/Drasil/GlassBR/Unitals.hs, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Chunk/CommonIdea.hs, code/drasil-lang/drasil-lang.cabal
=> Removed glassTypeAbbrs

code/README.md, code/drasil-data/Data/Drasil/Concepts/Computation.hs, code/drasil-data/Data/Drasil/Concepts/Physics.hs, code/drasil-data/Data/Drasil/Concepts/Software.hs, code/drasil-data/Data/Drasil/Concepts/Thermodynamics.hs, code/drasil-data/Data/Drasil/Quantities/Thermodynamics.hs, code/drasil-data/Data/Drasil/SI_Units.hs, code/drasil-data/Data/Drasil/Units/Thermodynamics.hs, code/drasil-example/Drasil/HGHC/HGHC.hs, code/drasil-example/Drasil/NoPCM/Assumptions.hs, code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/NoPCM/GenDefs.hs, code/drasil-example/Drasil/NoPCM/IMods.hs, code/drasil-example/Drasil/SSP/Unitals.hs, code/drasil-example/Drasil/SWHS/Assumptions.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/drasil-example/Drasil/SWHS/GenDefs.hs, code/drasil-example/Drasil/SWHS/IMods.hs, code/drasil-example/Drasil/SWHS/TMods.hs, code/drasil-example/Drasil/SWHS/Unitals.hs
So far I have only changed 1 item.
Am I correct in assuming each item with refactor should be its own commit?
Also, should I be working on this branch and pushing commits to this branch as I work on the Camel Case linting? As I push, the commits would be added to the request.
How often should I be making PRs and how should I be working on the tasks that are in a PR?
=> hlint Camel Case

code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/SSP/Requirements.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/drasil-example/Drasil/SWHS/Requirements.hs, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
Since the issues were so related, I worked on them in the same branch. 
The following changes were made:
- Added placeholder "Properties of Correct Solution" section to NoPCM
- Referenced "Properties of Correct Solution" in SWHS and NoPCM
- Switched to new NFR format in SWHS and NoPCM
- Removed unused code that was used for requirements
=> Requirements in SWHS and NoPCM

code/drasil-example/Drasil/SSP/Requirements.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This PR replaces a subset of the functional requirements for SSP with a single functional requirement, since the old requirements were too much like an algorithm.
=> SSP Functional Requirements Fix

code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SSP/Requirements.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
Added placeholder Properties of Correct Solution for SSP example with reference from the `Correct` NFR.
=> SSP Properties of Correct Solution

code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GamePhysics/Goals.hs, code/drasil-example/Drasil/GamePhysics/IMods.hs, code/drasil-example/drasil-example.cabal, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html
This PR adds the paragraph to the Instance Model section mapping goal statements to IMs, contributing to #1205 and #1215.
=> GamePhysics Instance Models Intro

code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/GlassBR/Requirements.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html
Added NFRs in new format, with reference to placeholder "Properties of Correct Solution" section, to GlassBR, as per #1229 and #1276.
=> [Small PR] GlassBR Nonfunctional Requirements

code/drasil-example/Drasil/GamePhysics/TMods.hs, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Chunk/Theory.hs
As per #947, the Source field is now improved for TMs (the relevant example was GamePhysics).
=> [Small PR] Updated Referencing in TMs

code/pr_label_update.sh
This PR addresses #1313. I'm going to manually tag this PR with a label or two and ensure they're removed.
=> Drasil-bot Label Fix

code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/GlassBR/Goals.hs, code/drasil-example/Drasil/GlassBR/IMods.hs, code/drasil-example/drasil-example.cabal, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html
This PR adds the instance model intro sentence mapping goal statements to instance models to GlassBR. This should be the last step for #1205 and #1215.
=> GlassBR Instance Models Intro

.gitignore, code/Makefile, code/log_check.sh
Minor additions to  Makefile, log_check.sh, and .gitignore.
Not sure if we want this, but I think it makes things cleaner. Especially when you want to see all of the logs at once.
Tested with make clean, make with differences, no differences, pre-existing files.
Will close #1318.
=> PR - Logs to separate folder.

code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/NoPCM/Requirements.hs, code/drasil-example/Drasil/SWHS/Requirements.hs, code/drasil-example/Drasil/SWHS/Unitals.hs, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
=> [Small PR] Added pi to area of circle formulas in SWHS and NoPCM FR2

code/drasil-docLang/Drasil/TraceTable.hs, code/drasil-example/Drasil/GamePhysics/IMods.hs, code/drasil-example/Drasil/GlassBR/IMods.hs, code/drasil-example/Drasil/NoPCM/IMods.hs, code/drasil-example/Drasil/SSP/IMods.hs, code/drasil-example/Drasil/SWHS/IMods.hs, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Chunk/InstanceModel.hs
As per #947, the Source field is now improved for IMs (the relevant example was GamePhysics).
=> Updated Referencing in IMs

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/CodeSpec.hs, code/drasil-database/Database/Drasil/ChunkDB.hs, code/drasil-docLang/Drasil/ExtractDocDesc.hs, code/drasil-docLang/Drasil/TraceTable.hs, code/drasil-example/Drasil/GamePhysics/DataDefs.hs, code/drasil-example/Drasil/GlassBR/DataDefs.hs, code/drasil-example/Drasil/HGHC/HeatTransfer.hs, code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SWHS/DataDefs.hs, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Chunk/DataDefinition.hs, code/drasil-lang/Language/Drasil/Chunk/Theory.hs, code/drasil-printers/Language/Drasil/Printing/Import.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
As per #947, the Source field is now improved for DDs (the relevant example was SSP).
=> Updated Referencing in DDs

code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/NoPCM/Requirements.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/drasil-example/Drasil/SWHS/Requirements.hs, code/drasil-example/Drasil/SWHS/Tables.hs, code/drasil-example/Drasil/SWHS/Unitals.hs, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/nopcm/src/cpp/InputFormat.cpp, code/stable/nopcm/src/cpp/InputFormat.hpp, code/stable/nopcm/src/csharp/InputFormat.cs, code/stable/nopcm/src/java/SWHS/InputFormat.java, code/stable/nopcm/src/python/InputFormat.py, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
As per #1307. This branch can be deleted after merge (I named it poorly and will complete the issue in another branch).
=> Added Tolerance Values to SWHS

code/drasil-example/Drasil/GlassBR/Body.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html
This minor PR fixes some typos from how the sentences were built (bullet points split, missing punctuation, etc.) and reduces hardcoding by using defined concepts in Drasil.
=> [Small PR] Fixed Sentence Construction in GlassBR System Context Section

code/drasil-example/Drasil/SSP/Assumptions.hs, code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SSP/GenDefs.hs, code/drasil-example/Drasil/SSP/Unitals.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
This PR adds the derivation to the base hydrostatic force in SSP in a similar style to how it was done for the surface hydrostatic force in #1286. This contributes to #1332.
=> SSP Base Hydrostatic Force Derivation

code/drasil-example/Drasil/GlassBR/Requirements.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html
Sorted FR Input Table in GlassBR by symbol. Just a small change I'd make to improve consistency between the other tables.
=> [Small PR] Sorted FR Input Table in GlassBR

code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-docLang/Drasil/DocumentLanguage/Definitions.hs, code/drasil-docLang/Drasil/ExtractDocDesc.hs, code/drasil-docLang/Drasil/Sections/AuxiliaryConstants.hs, code/drasil-docLang/Drasil/Sections/Introduction.hs, code/drasil-docLang/Drasil/Sections/Requirements.hs, code/drasil-docLang/Drasil/Sections/SolutionCharacterSpec.hs, code/drasil-docLang/Drasil/Sections/SpecificSystemDescription.hs, code/drasil-docLang/Drasil/Sections/Stakeholders.hs, code/drasil-docLang/Drasil/Sections/TableOfAbbAndAcronyms.hs, code/drasil-docLang/Drasil/Sections/TableOfUnits.hs, code/drasil-docLang/Drasil/Sections/TraceabilityMandGs.hs, code/drasil-docLang/Drasil/TraceTable.hs
=> [Small PR] Removed redundant brackets in docLang

code/drasil-code/Language/Drasil/Code/Imperative/AST.hs, code/drasil-code/Language/Drasil/Code/Imperative/Build/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Helpers.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/LuaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/ObjectiveCRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/Parsers/ConfigParser.hs
=> [Small PR] Removed redundant brackets in code

code/stable/projectile/Website/Projectile_SRS.html
Newest commit in master had failed as Projectile had not been updated based on new wrapping implementation.
Quick Fix.
=> PR - Updating Projectile stable based on new wrapping

code/Makefile, code/drasil-example/Drasil/Projectile/README.md, code/drasil-example/Drasil/README.md, code/drasil-example/Drasil/Template/Body.hs, code/drasil-example/Drasil/Template/Main.hs, code/drasil-example/Drasil/Template/README.md, code/drasil-example/drasil-example.cabal, code/stable/template/SRS/Makefile, code/stable/template/SRS/Projectile_SRS.tex, code/stable/template/Website/Projectile_SRS.css, code/stable/template/Website/Projectile_SRS.html
As mentioned in #1391, I've created the Template example that generates a blank document that can be used for future example-building.
_Closes #1401_
=> Created Template Example

code/drasil-example/Drasil/GlassBR/Assumptions.hs, code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/GlassBR/Concepts.hs, code/drasil-example/Drasil/GlassBR/DataDefs.hs, code/drasil-example/Drasil/GlassBR/IMods.hs, code/drasil-example/Drasil/GlassBR/Main.hs, code/drasil-example/Drasil/GlassBR/ModuleDefs.hs, code/drasil-example/Drasil/GlassBR/References.hs, code/drasil-example/Drasil/GlassBR/Requirements.hs, code/drasil-example/Drasil/GlassBR/Symbols.hs, code/drasil-example/Drasil/GlassBR/TMods.hs, code/drasil-example/Drasil/GlassBR/Unitals.hs
Based on #1267. Removing prefixes in GlassBR to make naming more generic.
=> PR - Remove prefixes from GlassBR

code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/drasil-example/Drasil/SWHS/Concepts.hs, code/drasil-example/Drasil/SWHS/DataDefs.hs, code/drasil-example/Drasil/SWHS/DataDesc.hs, code/drasil-example/Drasil/SWHS/GenDefs.hs, code/drasil-example/Drasil/SWHS/Generate.hs, code/drasil-example/Drasil/SWHS/Goals.hs, code/drasil-example/Drasil/SWHS/IMods.hs, code/drasil-example/Drasil/SWHS/References.hs, code/drasil-example/Drasil/SWHS/Requirements.hs, code/drasil-example/Drasil/SWHS/TMods.hs, code/drasil-example/Drasil/SWHS/Unitals.hs
Based on #1267. Removing prefixes in SWHS to make naming more generic.
=> PR - Remove prefixes from SWHS

code/Makefile
=> Copy GlassBR .txt Files During General Build

code/drasil-printers/Language/Drasil/HTML/Helpers.hs, code/drasil-printers/Language/Drasil/HTML/Print.hs, code/drasil-printers/Language/Drasil/Printing/Import.hs, code/drasil-printers/Language/Drasil/TeX/Helpers.hs, code/drasil-printers/Language/Drasil/TeX/Monad.hs, code/drasil-printers/Language/Drasil/TeX/Preamble.hs, code/drasil-printers/Language/Drasil/TeX/Print.hs
=> [Small PR] Removed Redundant Brackets in drasil-printers

code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/GlassBR/DataDefs.hs, code/drasil-example/Drasil/GlassBR/Figures.hs, code/drasil-example/drasil-example.cabal, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html
Added references to figures in GlassBR; closes #1410.
=> Figures in GlassBR

code/drasil-lang/Language/Drasil/Chunk/Citation.hs, code/drasil-lang/Language/Drasil/Chunk/UnitDefn.hs, code/drasil-lang/Language/Drasil/Expr/Extract.hs, code/drasil-lang/Language/Drasil/Sentence/Extract.hs, code/drasil-lang/Language/Drasil/Symbol.hs
=> [Small PR] Removed Redundant Brackets in drasil-lang

.travis.yml, code/scripts/deploy.bash
This PR introduces the infrastructure for the website. More a test of the Travis deploy infrastructure than a fully-fledged deploy.
I need you to do some things out-of-band of this PR.
* Setup `gh-pages` as the web branch: https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages
* Ensure @drasil-bot has `public-repo` permission (and can commit to the repo; specifically the `gh-pages` branch. 
Remember to message me when you merge this.
=> Deployment Infrastructure

code/scripts/deploy.bash
Makes corrections based on merged failure.
=> Deploy Script Round 2

code/drasil-data/Data/Drasil/Concepts/Computation.hs, code/drasil-data/Data/Drasil/Concepts/Documentation.hs, code/drasil-data/Data/Drasil/Concepts/Education.hs, code/drasil-data/Data/Drasil/Concepts/Math.hs, code/drasil-data/Data/Drasil/Concepts/PhysicalProperties.hs, code/drasil-data/Data/Drasil/README.md, code/drasil-data/Data/Drasil/Software/Products.hs, code/drasil-data/drasil-data.cabal, code/drasil-docLang/Drasil/DocLang/SRS.hs, code/drasil-docLang/Drasil/Sections/Stakeholders.hs, code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/GlassBR/Concepts.hs, code/drasil-example/Drasil/GlassBR/Figures.hs, code/drasil-example/Drasil/GlassBR/Unitals.hs, code/drasil-example/Drasil/HGHC/HGHC.hs, code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/Projectile/Body.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SSP/Defs.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/drasil-example/Drasil/SWHS/Concepts.hs, code/drasil-example/Drasil/SWHS/Unitals.hs, code/drasil-example/Drasil/Template/Body.hs, code/drasil-example/drasil-example.cabal, code/drasil-utils/Utils/Drasil.hs, code/drasil-utils/Utils/Drasil/Phrase.hs, code/drasil-utils/Utils/Drasil/README.md, code/drasil-utils/drasil-utils.cabal
=> Moved Phrase to utils

code/drasil-data/Data/Drasil/Concepts/Physics.hs, code/drasil-data/Data/Drasil/Quantities/Physics.hs, code/drasil-example/Drasil/GamePhysics/DataDefs.hs, code/drasil-example/Drasil/GamePhysics/Unitals.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html
Added new data definition to Datadef.hs
Files updated:
=> New module Potential Energy in datadefs.hs

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/CodeSpec.hs, code/stable/glassbr/src/cpp/Control.cpp, code/stable/glassbr/src/python/Control.py, code/stable/nopcm/src/cpp/Control.cpp, code/stable/nopcm/src/python/Control.py
This PR de-hardcodes parts of the code generator related to the write_output function and OutputFormat module.
=> Improvements to write_output code generation

README.md
Adding a link to our CI site in the README file.
References #1527
=> PR - Adding link for continuous deploy site

.travis.yml, code/scripts/ci_functions.bash
Introduce a new more flexible retry function for CI to attempt to catch more instances of intermittent network issues during CI builds.
=> Add better CI retry function.

code/scripts/deploy_stage.sh
Adding cross reference link to #1578.
=> Disable Docs for CD.

code/drasil-example/Drasil/GamePhysics/Body.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html
Files updated:
Updated typo in #1568 
Updated scope to match manual version
=> typo fix, updated scope in body.hs of gamephy

code/drasil-code/Language/Drasil/Code/Code.hs, code/drasil-code/Language/Drasil/Code/Imperative/Helpers.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/Symantics.hs, code/drasil-code/Test/HelloWorld.hs
This PR is a first step toward #496 by having types in GOOL carry type information, which is already enough for some nice cleanup.
=> GOOL types carry type information

code/drasil-example/Drasil/HGHC/HeatTransfer.hs, code/drasil-example/Drasil/SWHS/DataDefs.hs, code/drasil-lang/Language/Drasil/Chunk/Eq.hs
Apparently, this was a much easier fix than I thought and probably could've been done with the SWHS changes. 😄 
Part of #1580 and the rest is in the `swhsTMs` branch.
=> [Small PR] Fix space hack

code/drasil-docLang/Drasil/DocLang.hs, code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-docLang/Drasil/ExtractDocDesc.hs, code/drasil-docLang/Drasil/Sections/SpecificSystemDescription.hs, code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/SSP/Body.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/drasil-utils/Utils/Drasil.hs, code/drasil-utils/Utils/Drasil/Misc.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
Part of #1432. The Terminology and Definitions section is now automated in all examples except for GlassBR, due to #1244 and discussion in #1432. Sorting is also not done yet, because that will likely need some deeper design.
=> Terminology and Definitions section Automated (almost)

code/drasil-code/Language/Drasil/Code/Code.hs, code/drasil-code/Language/Drasil/Code/Imperative/Helpers.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/Symantics.hs, code/drasil-code/Test/Helper.hs
This PR adds functions to GOOL for generating functions based on their inputs and outputs,  and for generating calls to these functions, which allows for a generated function to return multiple outputs, which is needed for fixing #1453.
=> GOOL Input/Output functions

code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/Symantics.hs
This small PR expands upon #1616 by adding a function to GOOL for generating calls to external functions, based on their inputs and outputs.
=> GOOL external input/output function call

code/drasil-code/Language/Drasil/Code.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/Symantics.hs, code/drasil-code/Test/HelloWorld.hs, code/drasil-code/Test/Helper.hs, code/drasil-code/Test/Observer.hs
This PR adds functions to GOOL for including block comments above functions, classes, or modules. It's a first step towards #444.
=> Block comments in GOOL

README.md
=> [Small PR] Added Projectile to Drasil README

code/drasil-printers/Language/Drasil/HTML/Print.hs, code/stable/gamephys/Website/Chipmunk_SRS.html, code/stable/glassbr/Website/GlassBR_SRS.html, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/projectile/Website/Projectile_SRS.html, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/Website/SWHS_SRS.html, code/stable/tiny/Website/Tiny_SRS.html
=> [Small PR] Added Refname to HTML

code/drasil-example/Drasil/GamePhysics/Assumptions.hs
Closes #1419.
Renaming some sentences to avoid hardcoding numbers.
=> Minor PR - Renaming sentences in GamePhysics Assumptions

code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-docLang/Drasil/Sections/TableOfSymbols.hs, code/drasil-docLang/Drasil/Sections/TableOfUnits.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/projectile/SRS/Projectile_SRS.tex, code/stable/projectile/Website/Projectile_SRS.html, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html, code/stable/tiny/SRS/Tiny_SRS.tex, code/stable/tiny/Website/Tiny_SRS.html
Referenced the Table of Units and Table of Symbols in their respective sections.
_Closes #1619_
=> Reference Tables in DocLang

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs
#1680 introduced a ParamData type in GOOL for Parameters, eliminating the need for the similar data structure in Import.hs, so this PR removes that.
=> Remove ParamData from Import.hs

code/drasil-data/Data/Drasil/People.hs, code/drasil-example/Drasil/GamePhysics/Body.hs, code/stable/gamephys/SRS/Chipmunk_SRS.tex, code/stable/gamephys/Website/Chipmunk_SRS.html
@smiths, let me know if you are still good with this opening statement for the goal statement section(its the new update I made)
=> GameGS: Modified GS opening statement.

code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/NoPCM/References.hs, code/drasil-example/drasil-example.cabal
Closes #1730.
Created a separate file for NoPCM references, improves abstraction.
=> PR - NoPCM References

code/drasil-example/Drasil/SSP/IMods.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
I noticed a small mistake in SSP with a case expression, which this PR fixes.
=> Fixed incorrect case in SSP

code/datafiles/GlassBR/input.txt
Small PR to fix the mistake in GlassBR's input file pointed out here: https://github.com/JacquesCarette/Drasil/issues/1716#issuecomment-514386577.
=> Fixed units in glass input file comments

People/DanScime/Website/ExistingSurveryNotes.md
Adds Web Survey content to the People/DanScime folder.
=> PR - Web survey [DanScime]

People/DanScime/Notes/Moose Installation.txt
Adds initial notes for Moose to People/DanScime folder.
=> PR - Moose Initial [DanScime]

code/drasil-data/Data/Drasil/Concepts/Documentation.hs, code/drasil-docLang/Drasil/DocLang.hs, code/drasil-docLang/Drasil/DocLang/SRS.hs, code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-docLang/Drasil/DocumentLanguage/Core.hs, code/drasil-docLang/Drasil/Sections/TableOfUnits.hs
=> Added Ability to Change Appearance of Table of Units

notes/VariabilitiesForProjectile.txt
Added the variabilities for Projectile to the notes folder.
_Closes #1739_
=> [Small PR] Added Variabilities for Projectile to Notes

code/drasil-code/Language/Drasil/Code.hs, code/drasil-code/Language/Drasil/Code/Imperative/Build/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Data.hs, code/drasil-code/Language/Drasil/Code/Imperative/Doxygen/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/Symantics.hs, code/drasil-code/Test/FileTests.hs, code/drasil-code/Test/HelloWorld.hs, code/drasil-code/Test/Main.hs, code/drasil-code/Test/PatternTest.hs
This PR closes #1770 by adding functions to GOOL for generating a Makefile as part of a `Package`. 
#1802 should be merged first.
=> Generate Makefiles in GOOL

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/Symantics.hs, code/drasil-code/Language/Drasil/CodeSpec.hs, code/drasil-code/Test/Helper.hs, code/drasil-example/Drasil/GlassBR/ModuleDefs.hs, code/stable/glassbr/src/cpp/Calculations.hpp, code/stable/glassbr/src/cpp/Control.cpp, code/stable/glassbr/src/cpp/Interpolation.hpp, code/stable/glassbr/src/csharp/Calculations.cs, code/stable/glassbr/src/csharp/Interpolation.cs, code/stable/glassbr/src/java/GlassBR/Calculations.java, code/stable/glassbr/src/java/GlassBR/Interpolation.java, code/stable/glassbr/src/python/Calculations.py, code/stable/glassbr/src/python/Interpolation.py, code/stable/nopcm/src/cpp/Control.cpp, code/stable/nopcm/src/java/SWHS/InputParameters.java, code/stable/nopcm/src/python/InputParameters.py, code/stable/projectile/src/cpp/Calculations.hpp, code/stable/projectile/src/cpp/Control.cpp, code/stable/projectile/src/csharp/Calculations.cs, code/stable/projectile/src/java/Projectile/Calculations.java, code/stable/projectile/src/python/Calculations.py
This PR closes #1784 by documenting function return values in Doxygen comments for the generated code.
#1807 should be merged first.
=> Add return values to Doxygen documentation

code/drasil-data/Data/Drasil/Constraints.hs, code/drasil-example/Drasil/GlassBR/TMods.hs, code/drasil-example/Drasil/GlassBR/Unitals.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html, code/stable/glassbr/src/cpp/Calculations.hpp, code/stable/glassbr/src/cpp/InputConstraints.cpp, code/stable/glassbr/src/cpp/OutputFormat.hpp, code/stable/glassbr/src/csharp/Calculations.cs, code/stable/glassbr/src/csharp/InputConstraints.cs, code/stable/glassbr/src/csharp/OutputFormat.cs, code/stable/glassbr/src/java/GlassBR/Calculations.java, code/stable/glassbr/src/java/GlassBR/InputConstraints.java, code/stable/glassbr/src/java/GlassBR/OutputFormat.java, code/stable/glassbr/src/python/Calculations.py, code/stable/glassbr/src/python/InputConstraints.py, code/stable/glassbr/src/python/OutputFormat.py
- Renamed GlassBR safety requirements (migrated from the `swhsTMs` branch)
- Updated TM Notes
- Fixed constraints on probabilities
_Closes #1586 and closes #1587_
=> [GlassBR] Minor TM Touch Ups

code/drasil-example/Drasil/NoPCM/Body.hs, code/drasil-example/Drasil/NoPCM/DataDefs.hs, code/drasil-example/Drasil/NoPCM/GenDefs.hs, code/drasil-example/Drasil/NoPCM/IMods.hs, code/drasil-example/Drasil/SWHS/Body.hs, code/drasil-example/Drasil/SWHS/DataDefs.hs, code/drasil-example/Drasil/SWHS/GenDefs.hs, code/drasil-example/Drasil/SWHS/IMods.hs, code/drasil-example/Drasil/SWHS/TMods.hs, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
Fixed Newton's Law of Cooling from the `swhsTMs` branch.
_Closes #1479_
=> [SWHS] Fixed Newton's Law of Cooling

.gitattributes, .travis.yml, code/Makefile, code/drasil-docLang/Drasil/ExtractDocDesc.hs, code/scripts/ci_functions.bash, code/scripts/maybe_test_deploy.sh
This PR includes a bunch of miscellaneous corrections of things I noticed while writing the draft of my report.
=> Misc Corrections

Papers/GOOL/GOOL.tex
Closes #1865. I used the "ContentsOfSS.tex" paper in the Papers directory as a template for this one, just emptied out most of the text.
=> Added template file for GOOL paper

code/drasil-docLang/Drasil/Sections/TableOfAbbAndAcronyms.hs, code/drasil-docLang/Drasil/Sections/TableOfSymbols.hs, code/drasil-docLang/Drasil/Sections/TableOfUnits.hs, code/stable/gamephysics/SRS/GamePhysics_SRS.tex, code/stable/gamephysics/Website/GamePhysics_SRS.html, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html, code/stable/hghc/SRS/HGHC_SRS.tex, code/stable/hghc/Website/HGHC_SRS.html, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/projectile/SRS/Projectile_SRS.tex, code/stable/projectile/Website/Projectile_SRS.html, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
This PR turns on the table captions for Table of Units, Table of Symbols, and Table of Abbreviations and Acronyms.
Closes #1889.
=> Turn on table captions

code/drasil-example/Drasil/GamePhysics/Body.hs, code/stable/gamephysics/SRS/GamePhysics_SRS.tex, code/stable/gamephysics/Website/GamePhysics_SRS.html
Update FIXMEREF text in User Responsibilities section.
Replaced the FIXMEREF text with reference to Assumption section
=> FIXMEREF text in User Responsibilities section updated

code/drasil-gool/GOOL/Drasil/Data.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs
Quick improvement to GOOL, closes #1881.
=> Store VarData in ParamData

code/drasil-example/Drasil/GamePhysics/Body.hs, code/stable/gamephysics/SRS/GamePhysics_SRS.tex, code/stable/gamephysics/Website/GamePhysics_SRS.html
Fixed Goal statement sentence in issue #1894
=> Fixed goal statement sentence

code/drasil-data/Data/Drasil/Quantities/Physics.hs, code/stable/gamephysics/SRS/GamePhysics_SRS.tex, code/stable/gamephysics/Website/GamePhysics_SRS.html, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
Torque has been updated to vector
=> Updated torque to vector

code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs
Small PR adding an `InternalVariable` type class to GOOL so `varFromData` does not get exported.
=> InternalVariable type class

code/drasil-gool/GOOL/Drasil/Symantics.hs
Small PR that cleans up the constraints on GOOL classes, mostly by removing those that were redundant due to transitivity.
=> Cleaned up GOOL class constraints

code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs, code/drasil-gool/Test/Observer.hs, code/drasil-gool/Test/PatternTest.hs
This PR improves the coding style for the PatternTest and Observer GOOL tests so we can use them for examples in the paper.
=> PatternTest style

code/drasil-code/Language/Drasil/Code/Imperative/Comments.hs, code/drasil-code/Language/Drasil/Code/Imperative/Descriptions.hs, code/drasil-code/Language/Drasil/Code/Imperative/FunctionCalls.hs, code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Language/Drasil/Code/Imperative/Generator.hs, code/drasil-code/Language/Drasil/Code/Imperative/Helpers.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Logging.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-code/Language/Drasil/Code/Imperative/Parameters.hs, code/drasil-code/Language/Drasil/Code/Imperative/State.hs, code/drasil-gool/GOOL/Drasil.hs, code/drasil-gool/GOOL/Drasil/Data.hs, code/drasil-gool/GOOL/Drasil/Helpers.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/State.hs, code/drasil-gool/GOOL/Drasil/Symantics.hs, code/drasil-gool/Test/FileTests.hs, code/drasil-gool/Test/HelloWorld.hs, code/drasil-gool/Test/Helper.hs, code/drasil-gool/Test/Main.hs, code/drasil-gool/Test/Observer.hs, code/drasil-gool/Test/PatternTest.hs
This branch is finally possible to merge, in that it compiles and matches stable. I know there are still some outstanding issues, namely:
1. Adding more meaningful names for the various lift functions
2. Looking into using zoom for local state
But since this PR is already massive, I thought you may want to get it merged in at this point, @JacquesCarette. If so, I'll do the other improvements on different branches/PRs.
=> Improving State monad implementation in GOOL

code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil.hs, code/drasil-gool/GOOL/Drasil/Helpers.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs
This PR just renames all of the "lift" helper functions in GOOL to more meaningful names that make it clear whether it is lifting into the code monad or the state monad.
=> Rename lifting functions

code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs
Some HLint violations got through to master. This fixes them.
On a related note, anyone know why Travis has stopped reporting build statuses here?
=> Fix for HLint errors in master

code/drasil-code/Language/Drasil/Code/Imperative/FunctionCalls.hs, code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs
This small PR makes a few improvements to the generator for small formatting/redundant things I noticed while going over the code for my thesis, as well as adding documentation for some functions.
=> Small Generator improvements

code/drasil-gool/GOOL/Drasil/ClassInterface.hs
Tiny PR that explains some of GOOL's operators in comments.
=> Add comments for some operators

code/drasil-code/Language/Drasil/Code/Imperative/FunctionCalls.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-gool/GOOL/Drasil/ClassInterface.hs, code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/Test/HelloWorld.hs, code/drasil-gool/Test/Helper.hs, code/drasil-gool/Test/PatternTest.hs
Missed these two functions in my previous "renaming" PR.
=> Rename valState and returnState

code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/Macros.hs
This small PR just commits the small improvements I made during today's GOOL code review meeting. More organized PRs for the different kinds of improvements discussed today coming soon.
=> Quick improvements made during meeting

code/drasil-gool/GOOL/Drasil/AST.hs, code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CLike.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CommonPseudoOO.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/Macros.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/RendererClasses.hs, code/drasil-gool/GOOL/Drasil/State.hs
This PR does a bunch of small things we talked about in the April 29th GOOL code review meeting.
#209 should be merged first. 4c91b1c is the first new commit.
=> Small miscellaneous improvements to GOOL

code/drasil-code/Language/Drasil/Code/Imperative/Generator.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-gool/GOOL/Drasil.hs
This PR does some small readability improvements in the generator.
=> Generator Readability improvements

code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs
This PR adds documentation to many functions in the generator and does some minor refactors to make some functions simpler and/or more readable.
=> Generator simplifications and documentation

code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs
This PR does some small cleanup of functions in the generator related to generating input constraints, and adds documentation.
=> Generator improvements related to input constraints

code/drasil-code/Language/Drasil/Code/Imperative/Descriptions.hs, code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Language/Drasil/Code/Imperative/Generator.hs, code/stable/projectile/Projectile_C_P_NoL_B_U_V_D/src/cpp/InputParameters.hpp, code/stable/projectile/Projectile_C_P_NoL_B_U_V_D/src/csharp/InputParameters.cs, code/stable/projectile/Projectile_C_P_NoL_B_U_V_D/src/java/Projectile/InputParameters.java, code/stable/projectile/Projectile_C_P_NoL_B_U_V_D/src/python/InputParameters.py, code/stable/projectile/Projectile_S_L_NoL_U_U_V_F/src/cpp/InputConstraints.hpp, code/stable/projectile/Projectile_S_L_NoL_U_U_V_F/src/csharp/InputConstraints.cs, code/stable/projectile/Projectile_S_L_NoL_U_U_V_F/src/java/Projectile/InputConstraints.java, code/stable/projectile/Projectile_S_L_NoL_U_U_V_F/src/python/InputConstraints.py, code/stable/projectile/Projectile_U_P_L_B_B_C_D/src/cpp/Projectile.hpp, code/stable/projectile/Projectile_U_P_L_B_B_C_D/src/csharp/Projectile.cs, code/stable/projectile/Projectile_U_P_L_B_B_C_D/src/java/Projectile/Projectile.java, code/stable/projectile/Projectile_U_P_L_B_B_C_D/src/python/Projectile.py, code/stable/projectile/Projectile_U_P_L_B_WI_V_F/src/cpp/Projectile.hpp, code/stable/projectile/Projectile_U_P_L_B_WI_V_F/src/csharp/Projectile.cs, code/stable/projectile/Projectile_U_P_L_B_WI_V_F/src/java/Projectile/Projectile.java, code/stable/projectile/Projectile_U_P_L_B_WI_V_F/src/python/Projectile.py, code/stable/projectile/Projectile_U_P_NoL_U_WI_V_D/src/cpp/Projectile.hpp, code/stable/projectile/Projectile_U_P_NoL_U_WI_V_D/src/csharp/Projectile.cs, code/stable/projectile/Projectile_U_P_NoL_U_WI_V_D/src/java/Projectile/Projectile.java, code/stable/projectile/Projectile_U_P_NoL_U_WI_V_D/src/python/Projectile.py
This PR does a series of small fixes related to the generation of Doxygen comments, as well as adds documentation to the Descriptions.hs module. 
The changes to stable are (in my opinion) good, and a result of the fixes I made.
=> Cleanup, documentation, and fixes related to Doxygen comment generation

code/drasil-example/Drasil/GamePhysics/README.md, code/drasil-example/Drasil/GamePhysics/Requirements.hs, code/drasil-printers/drasil-printers.cabal, code/stable/gamephysics/SRS/GamePhysics_SRS.tex, code/stable/gamephysics/Website/GamePhysics_SRS.html
This pull request has been updated to include the changes to the following documents:
- Requirements.hs (Haskell File)
- GamePhysics_SRS.tex (LaTeX File; stable)
- GamePhysics_SRS.html (HTML File; stable)
=> Issue#1433

code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-example/Drasil/SSP/Unitals.hs, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html
- contains all changed files related to updating the Stress Data Definition to NormStress + creating new symbol F_n for SSP
- changed files: DataDefs.hs, Unitals.hs, SSP_SRS.tex, SSP_SRS.html
- contributes to #2156 (addresses Issue Item 2)
=> Update Stress to NormStress + Create New Symbol F_n

code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Test/Observer.hs, code/drasil-gool/GOOL/Drasil/ClassInterface.hs, code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CommonPseudoOO.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/GOOL/Drasil/State.hs
=> Issue 2143

code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-gool/GOOL/Drasil/ClassInterface.hs, code/drasil-gool/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/stable/glassbr/src/cpp/InputParameters.hpp, code/stable/gooltest/cpp/PatternTest/Observer.hpp, code/stable/nopcm/src/cpp/Constants.hpp, code/stable/projectile/Projectile_U_P_L_B_B_C_D/src/cpp/Projectile.hpp
=> Issue 2145

code/drasil-docLang/Drasil/Sections/TableOfSymbols.hs, code/drasil-docLang/drasil-docLang.cabal
=> Preventing duplicate symbols

code/drasil-example/Drasil/GlassBR/Unitals.hs, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html, code/stable/glassbr/src/cpp/Calculations.cpp, code/stable/glassbr/src/csharp/Calculations.cs, code/stable/glassbr/src/java/GlassBR/Calculations.java, code/stable/glassbr/src/python/Calculations.py, code/stable/glassbr/src/swift/Calculations.swift
=> making lsf a constant dbl 1.0

code/drasil-example/Drasil/DblPendulum/Body.hs, code/drasil-example/Drasil/DblPendulum/Goals.hs, code/stable/dblpendulum/SRS/DblPendulum_SRS.tex, code/stable/dblpendulum/Website/DblPendulum_SRS.html
Trying to see how I can add all the sections (empty) to the SRS. I was able to pull in some of the sections without dependencies, using Body.hs with some imports. The rest of the sections have dependencies and I want to see how I can create those in the SRS as well.
=> Adding sections to SRS template

code/drasil-data/Data/Drasil/Concepts/Physics.hs, code/drasil-data/Data/Drasil/Quantities/Physics.hs, code/drasil-example/Drasil/DblPendulum/Body.hs, code/drasil-example/Drasil/DblPendulum/DataDefs.hs, code/drasil-example/Drasil/DblPendulum/GenDefs.hs, code/drasil-example/Drasil/DblPendulum/IMods.hs, code/drasil-example/Drasil/DblPendulum/Requirements.hs, code/drasil-example/Drasil/DblPendulum/TMods.hs, code/drasil-example/Drasil/DblPendulum/Unitals.hs, code/drasil-example/Drasil/GamePhysics/DataDefs.hs, code/drasil-example/Drasil/GamePhysics/IMods.hs, code/stable/dblpendulum/SRS/DblPendulum_SRS.tex, code/stable/dblpendulum/Website/DblPendulum_SRS.html
=> Pendulum example- Added GDs and IMs and derivations

code/drasil-code/Language/Drasil/CodeSpec.hs, code/drasil-data/Data/Drasil/Theories/Physics.hs, code/drasil-docLang/Drasil/DocumentLanguage/Definitions.hs, code/drasil-docLang/Drasil/ExtractDocDesc.hs, code/drasil-example/Drasil/DblPendulum/GenDefs.hs, code/drasil-example/Drasil/DblPendulum/IMods.hs, code/drasil-example/Drasil/GamePhysics/GenDefs.hs, code/drasil-example/Drasil/GamePhysics/IMods.hs, code/drasil-example/Drasil/GlassBR/IMods.hs, code/drasil-example/Drasil/NoPCM/GenDefs.hs, code/drasil-example/Drasil/NoPCM/IMods.hs, code/drasil-example/Drasil/PDController/GenDefs.hs, code/drasil-example/Drasil/PDController/IModel.hs, code/drasil-example/Drasil/Projectile/Body.hs, code/drasil-example/Drasil/Projectile/GenDefs.hs, code/drasil-example/Drasil/Projectile/IMods.hs, code/drasil-example/Drasil/SSP/GenDefs.hs, code/drasil-example/Drasil/SSP/IMods.hs, code/drasil-example/Drasil/SWHS/GenDefs.hs, code/drasil-example/Drasil/SWHS/IMods.hs, code/drasil-lang/Language/Drasil/Chunk/Eq.hs, code/drasil-lang/Language/Drasil/Chunk/Relation.hs, code/drasil-lang/Language/Drasil/Classes.hs, code/drasil-theory/Theory/Drasil.hs, code/drasil-theory/Theory/Drasil/GenDefn.hs, code/drasil-theory/Theory/Drasil/InstanceModel.hs, code/drasil-theory/Theory/Drasil/ModelKinds.hs, code/drasil-theory/drasil-theory.cabal
Split up my branch larger branch so that it doesn't break anything, just imports ModelKinds a bunch.
=> import ModelKinds, make IMs and GDs use ModelKinds instead of strictly RelationConcepts

code/drasil-code/drasil-code.cabal, code/drasil-code/package.yaml, code/drasil-code/stack.yaml, code/drasil-data/stack.yaml, code/drasil-database/stack.yaml, code/drasil-docLang/stack.yaml, code/drasil-example/stack.yaml, code/drasil-gen/stack.yaml, code/drasil-gool/stack.yaml, code/drasil-metadata/stack.yaml, code/drasil-printers/stack.yaml, code/drasil-theory/stack.yaml
~~(something small to also test the GitHub Actions)~~
EDIT: ^ I had to make a small change to get the workflow to run. I don't think we can run the workflow file on this branch without pulling rebasing it on master after the PR #2318 gets merged.
=> Adding drasil-metadata to each stack.yaml

code/drasil-code/drasil-code.cabal, code/drasil-code/package.yaml, code/drasil-data/drasil-data.cabal, code/drasil-data/package.yaml, code/drasil-database/drasil-database.cabal, code/drasil-database/package.yaml, code/drasil-docLang/drasil-docLang.cabal, code/drasil-docLang/package.yaml, code/drasil-gen/drasil-gen.cabal, code/drasil-gen/package.yaml, code/drasil-gool/drasil-gool.cabal, code/drasil-gool/package.yaml, code/drasil-lang/drasil-lang.cabal, code/drasil-lang/package.yaml, code/drasil-theory/drasil-theory.cabal, code/drasil-theory/package.yaml, code/drasil-utils/drasil-utils.cabal, code/drasil-utils/package.yaml
Removing MissingH dependency from projects that don't actually depend on it.
=> Removing unneeded MissingH dependencies

.github/workflows/Drasil.yaml
=> Github Actions : stop building on commit/push

.vscode/settings.json, code/drasil-example/Drasil/PDController/Concepts.hs
closes issue #2343
lined up the code in PDcontroller. what was previously lines 19-32.
=> lining up Cls in PDcontroller  (Closes Issue #2343)

code/README.md
=> Correct directory beside new link

README.md, code/drasil-example/Drasil/PDController/References.hs
adding pdController missing rows 
closes Issue #2376
=> Adding pdController missing rows

code/drasil-example/Drasil/GlassBR/TMods.hs
=> #2369 : convert TMods' lrIsSafe into a QDefinition

code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GamePhysics/GenDefs.hs, code/stable/gamephysics/SRS/GamePhysics_SRS.tex, code/stable/gamephysics/Website/GamePhysics_SRS.html
Two minor changes to grammar in `GamePhysics`.
Closes #2257 and #2263
=> Small changes in grammar for GamePhysics

code/drasil-example/Drasil/DblPendulum/GenDefs.hs
=> Convert DblPendulum's accelerationIY GD into an EquationalModel

code/drasil-code/Data/Drasil/ExternalLibraries/ODELibraries.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Development.hs, code/drasil-lang/Language/Drasil/Expr.hs, code/drasil-lang/Language/Drasil/Expr/Extract.hs, code/drasil-lang/Language/Drasil/Expr/Precedence.hs, code/drasil-printers/Language/Drasil/Printing/Import.hs
=> Move arithmetic binary operations out of BinOp

code/drasil-example/Drasil/PDController/Assumptions.hs, code/drasil-example/Drasil/PDController/Body.hs, code/drasil-example/Drasil/PDController/Concepts.hs, code/drasil-example/Drasil/PDController/IntroSection.hs, code/drasil-example/Drasil/PDController/Unitals.hs, code/stable/pdController/SRS/PDController_SRS.tex, code/stable/pdController/Website/PDController_SRS.html, code/stable/pdController/src/python/designLog.txt
=> Spell check on PDController example

code/drasil-example/Drasil/DblPendulum/Body.hs, code/drasil-example/Drasil/DblPendulum/GenDefs.hs, code/drasil-example/Drasil/DblPendulum/IMods.hs, code/drasil-example/Drasil/GamePhysics/Changes.hs, code/drasil-example/Drasil/GamePhysics/GenDefs.hs, code/drasil-example/Drasil/GamePhysics/Requirements.hs, code/drasil-example/Drasil/GamePhysics/TMods.hs, code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/PDController/DataDefs.hs, code/drasil-example/Drasil/PDController/GenDefs.hs, code/drasil-example/Drasil/PDController/GenSysDesc.hs, code/drasil-example/Drasil/PDController/IModel.hs, code/drasil-example/Drasil/PDController/IntroSection.hs, code/drasil-example/Drasil/PDController/TModel.hs, code/drasil-example/Drasil/Projectile/Assumptions.hs, code/drasil-example/Drasil/SSP/DataDefs.hs, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Sentence.hs
Operator is `!.`. Did not change all instances of `."` as some were used as Strings or had other underlying meanings.
Contributes to issue #2399
=> Implemented new period operator

code/drasil-data/Data/Drasil/Concepts/Math.hs, code/drasil-data/Data/Drasil/Quantities/Math.hs, code/drasil-lang/Language/Drasil/ShortHands.hs
=> Adding Negative & Positive Infinities to math concepts

code/drasil-example/Drasil/DblPendulum/DataDefs.hs, code/stable/dblpendulum/SRS/DblPendulum_SRS.tex, code/stable/dblpendulum/Website/DblPendulum_SRS.html
=> #2451 : Fix equation of angFrequencyDD

code/drasil-data/Data/Drasil/Concepts/Physics.hs
=> adding physics concepts to drasil-data

code/drasil-database/Database/Drasil/ChunkDB.hs
Small PR, documented the `ChunkDB` type with a little bit more detail. Closes #2411 for now. I will probably take a look at the entire folder once I am more familiar with the functions/chunk system.
=> Small change to ChunkDB

code/drasil-data/Data/Drasil/Concepts/Computation.hs
=> Adding computation concepts to data-drasil

code/drasil-example/Drasil/DblPendulum/Concepts.hs, code/drasil-example/Drasil/DblPendulum/GenDefs.hs, code/drasil-example/Drasil/DblPendulum/IMods.hs, code/stable/dblpendulum/SRS/DblPendulum_SRS.tex, code/stable/dblpendulum/Website/DblPendulum_SRS.html
Incorporates 3rd list of words for abstraction which were previously defined but unused in dblpendulum.
Contributes #2424
=> More Abstracted Words

code/drasil-data/Data/Drasil/Concepts/Math.hs
closes Issue #2396 
some issues occured with the merge so i started again with the updated master branch and copied in the file.
=> adding laplace transform conceopt to math

code/drasil-data/Data/Drasil/Concepts/Math.hs, code/drasil-example/Drasil/DblPendulum/Assumptions.hs, code/drasil-example/Drasil/DblPendulum/GenDefs.hs
Adds list four of abstract words contributing to issue #2424. I'm not too sure if the definitions are good (notably the direction definition).
=> More abstract words for dblPendulum

code/drasil-example/Drasil/DblPendulum/GenDefs.hs, code/drasil-example/Drasil/DblPendulum/IMods.hs, code/drasil-example/Drasil/SSP/Assumptions.hs, code/drasil-example/Drasil/SWHS/TMods.hs, code/drasil-utils/Utils/Drasil/Sentence.hs, code/stable/dblpendulum/SRS/DblPendulum_SRS.tex, code/stable/dblpendulum/Website/DblPendulum_SRS.html
Added list 5 of abstracted words and implemented some of them.
Closes #2424
=> Abstracted Words Part 5

code/drasil-example/Drasil/PDController/Concepts.hs
=> adding derivative and proportional control to PDController concepts.hs

code/drasil-example/Drasil/Projectile/GenDefs.hs, code/stable/projectile/SRS/Projectile_SRS.tex, code/stable/projectile/Website/Projectile_SRS.html
Re-orders references again due to #2468
=> Convert Projectile's rectPosQD into an equational model

code/drasil-utils/Utils/Drasil/Concepts.hs, code/drasil-utils/Utils/Drasil/Contents.hs, code/drasil-utils/Utils/Drasil/Document.hs, code/drasil-utils/Utils/Drasil/English.hs, code/drasil-utils/Utils/Drasil/Fold.hs, code/drasil-utils/Utils/Drasil/Misc.hs, code/drasil-utils/Utils/Drasil/Phrase.hs, code/drasil-utils/Utils/Drasil/Sentence.hs
While making a summary of the combinators, I found some things I didn't like from my last changes to the Utils documentation, so these should remedy that. Tried to add more detail and keep comments to one style.
=> Review Utils Documentation

code/drasil-lang/Language/Drasil/Classes/Citations.hs, code/drasil-lang/Language/Drasil/Classes/Core.hs, code/drasil-lang/Language/Drasil/Classes/Document.hs, code/drasil-lang/Language/Drasil/Data/Citation.hs, code/drasil-lang/Language/Drasil/Data/Date.hs, code/drasil-lang/Language/Drasil/Development/Sentence.hs, code/drasil-lang/Language/Drasil/Document/Core.hs, code/drasil-lang/Language/Drasil/Expr/Extract.hs, code/drasil-lang/Language/Drasil/Expr/Math.hs, code/drasil-lang/Language/Drasil/Expr/Precedence.hs, code/drasil-lang/Language/Drasil/Label/Type.hs, code/drasil-lang/Language/Drasil/NounPhrase/Core.hs, code/drasil-lang/Language/Drasil/Sentence/Extract.hs, code/drasil-lang/Language/Drasil/Symbol/Helpers.hs, code/drasil-lang/Language/Drasil/URI/AST.hs, code/drasil-lang/Language/Drasil/Uncertainty/Core.hs
Part 2 of reviewing lang (not docLang, ignore the commit message), done all subfolders. Mostly just style changes.
=> More detailed Lang documentation

code/drasil-example/Drasil/DblPendulum/Body.hs, code/drasil-example/Drasil/DblPendulum/Figures.hs, code/drasil-example/Drasil/DblPendulum/GenDefs.hs, code/drasil-example/Drasil/DblPendulum/Goals.hs, code/drasil-example/Drasil/DblPendulum/IMods.hs, code/drasil-example/Drasil/DblPendulum/Unitals.hs, code/stable/dblpendulum/SRS/DblPendulum_SRS.tex, code/stable/dblpendulum/Website/DblPendulum_SRS.html
Implemented more combinators into pendulum example and fixed some grammar mistakes as a result.
=> Used more concept combinators in dblPendulum

code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GamePhysics/DataDefs.hs, code/drasil-example/Drasil/GamePhysics/IMods.hs, code/drasil-example/Drasil/GamePhysics/Requirements.hs, code/drasil-utils/Utils/Drasil/Concepts.hs, code/stable/gamephysics/SRS/GamePhysics_SRS.tex, code/stable/gamephysics/Website/GamePhysics_SRS.html
Also added and used some new combinators, fixed small grammar errors I saw while passing through the code.
=> Added some concept-level combinators to GamePhysics example

code/drasil-example/Drasil/PDController/Concepts.hs, code/drasil-example/Drasil/PDController/Unitals.hs, code/stable/pdController/SRS/PDController_SRS.tex, code/stable/pdController/Website/PDController_SRS.html
reuse of phrases & error fixes
contributes to Issue #2397.
=>  Reuse of phrases with "in the frequency domain"

code/drasil-lang/Language/Drasil/Chunk/Constrained.hs, code/drasil-lang/Language/Drasil/Chunk/DefinedQuantity.hs, code/drasil-lang/Language/Drasil/Chunk/Eq.hs, code/drasil-lang/Language/Drasil/Chunk/NamedArgument.hs, code/drasil-lang/Language/Drasil/Chunk/Quantity.hs, code/drasil-lang/Language/Drasil/Chunk/UncertainQuantity.hs, code/drasil-lang/Language/Drasil/Chunk/Unital.hs, code/drasil-lang/Language/Drasil/Chunk/Unitary.hs, code/drasil-lang/Language/Drasil/Chunk/UnitaryConcept.hs, code/drasil-lang/Language/Drasil/Classes.hs, code/drasil-lang/Language/Drasil/Classes/Citations.hs, code/drasil-lang/Language/Drasil/Classes/Core.hs, code/drasil-lang/Language/Drasil/Classes/Document.hs, code/drasil-lang/Language/Drasil/Constraint.hs, code/drasil-lang/Language/Drasil/Data/Citation.hs, code/drasil-lang/Language/Drasil/Derivation.hs, code/drasil-lang/Language/Drasil/Document.hs, code/drasil-lang/Language/Drasil/Document/Core.hs, code/drasil-lang/Language/Drasil/Expr.hs, code/drasil-lang/Language/Drasil/Expr/Extract.hs, code/drasil-lang/Language/Drasil/Expr/Math.hs, code/drasil-lang/Language/Drasil/Misc.hs, code/drasil-lang/Language/Drasil/NounPhrase.hs, code/drasil-lang/Language/Drasil/NounPhrase/Core.hs, code/drasil-lang/Language/Drasil/People.hs
Part 3 of documenting `drasil-lang`. Going through all files before README.
=> Lang documentation review part 3

code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/NounPhrase.hs, code/drasil-lang/Language/Drasil/RefProg.hs, code/drasil-lang/Language/Drasil/Reference.hs, code/drasil-lang/Language/Drasil/Sentence.hs, code/drasil-lang/Language/Drasil/ShortHands.hs, code/drasil-lang/Language/Drasil/ShortName.hs, code/drasil-lang/Language/Drasil/Space.hs, code/drasil-lang/Language/Drasil/Stages.hs, code/drasil-lang/Language/Drasil/Symbol.hs, code/drasil-lang/Language/Drasil/UID.hs, code/drasil-lang/Language/Drasil/Uncertainty.hs, code/drasil-lang/Language/Drasil/Uncertainty/Core.hs, code/drasil-lang/Language/Drasil/Unicode.hs, code/drasil-lang/Language/Drasil/UnitLang.hs
Finishes adding detailed documentation to rest of the files in the `drasil-lang` folder.
=> Documentation for Lang part 4

code/drasil-example/Drasil/PDController/Assumptions.hs, code/drasil-example/Drasil/PDController/Body.hs, code/drasil-example/Drasil/PDController/Changes.hs, code/drasil-example/Drasil/PDController/Concepts.hs, code/drasil-example/Drasil/PDController/DataDefs.hs, code/drasil-example/Drasil/PDController/GenDefs.hs, code/drasil-example/Drasil/PDController/GenSysDesc.hs, code/drasil-example/Drasil/PDController/IModel.hs, code/drasil-example/Drasil/PDController/IntroSection.hs, code/drasil-example/Drasil/PDController/Requirements.hs, code/drasil-example/Drasil/PDController/SpSysDesc.hs, code/drasil-example/Drasil/PDController/TModel.hs, code/stable/pdController/SRS/PDController_SRS.tex, code/stable/pdController/Website/PDController_SRS.html
Also fixed some grammar issues as a result. Removed periods from some labels. I'm not sure if the symbol fix was right, but what was previously there seemed to be the same thing (without the fancier symbol).
=> Added more concept-level combinators to PDController

code/drasil-example/Drasil/PDController/Concepts.hs, code/stable/pdController/SRS/PDController_SRS.tex, code/stable/pdController/Website/PDController_SRS.html
=> Adding `ccTimeDomain` to PDController concepts

code/drasil-data/Data/Drasil/Equations/Defining/Physics.hs, code/drasil-data/Data/Drasil/Theories/Physics.hs
=> Convert hsPressureGD into an EquationalModel

code/Makefile, code/scripts/make_docs.sh
Closes #2531 
Slightly reroutes the `docs` folder passing
=> Add `docs` folder to cleaning list of `make clean`

code/drasil-docLang/Drasil/DocumentLanguage/Definitions.hs, code/drasil-docLang/Drasil/DocumentLanguage/RefHelpers.hs, code/drasil-docLang/Drasil/DocumentLanguage/TraceabilityMatrix.hs, code/drasil-docLang/Drasil/DocumentLanguage/Units.hs, code/drasil-docLang/Drasil/Sections/AuxiliaryConstants.hs, code/drasil-docLang/Drasil/Sections/GeneralSystDesc.hs, code/drasil-docLang/Drasil/Sections/Introduction.hs, code/drasil-docLang/Drasil/Sections/ReferenceMaterial.hs, code/drasil-docLang/Drasil/Sections/Requirements.hs, code/drasil-docLang/Drasil/Sections/SpecificSystemDescription.hs, code/drasil-docLang/Drasil/Sections/Stakeholders.hs, code/drasil-docLang/Drasil/Sections/TableOfAbbAndAcronyms.hs, code/drasil-docLang/Drasil/Sections/TableOfSymbols.hs, code/drasil-docLang/Drasil/Sections/TableOfUnits.hs, code/drasil-docLang/Drasil/Sections/TraceabilityMandGs.hs
Finished subfolders for docLang documentation.
=> Adding more documentation to docLang

code/drasil-data/Data/Drasil/Equations/Defining/Physics.hs, code/drasil-data/Data/Drasil/Theories/Physics.hs, code/drasil-example/Drasil/DblPendulum/Body.hs, code/drasil-example/Drasil/DblPendulum/Concepts.hs, code/drasil-example/Drasil/DblPendulum/IMods.hs, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Development/Sentence.hs, code/drasil-theory/Theory/Drasil.hs, code/drasil-theory/Theory/Drasil/Theory.hs
Contributes to #2371 
Depends on #2539
=> Convert AccelerationTM into an EquationalModel

code/drasil-data/Data/Drasil/Theories/Physics.hs, code/drasil-example/Drasil/DblPendulum/Body.hs, code/drasil-example/Drasil/DblPendulum/Concepts.hs, code/drasil-example/Drasil/DblPendulum/IMods.hs, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Development/Sentence.hs, code/drasil-theory/Theory/Drasil.hs, code/drasil-theory/Theory/Drasil/Theory.hs
=> Convert Newton's SLRM TM into an EquationalModel

code/drasil-data/Data/Drasil/Equations/Defining/Physics.hs, code/drasil-data/Data/Drasil/Theories/Physics.hs, code/drasil-example/Drasil/DblPendulum/Body.hs, code/drasil-example/Drasil/DblPendulum/Concepts.hs, code/drasil-example/Drasil/DblPendulum/IMods.hs, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Development/Sentence.hs, code/drasil-theory/Theory/Drasil.hs, code/drasil-theory/Theory/Drasil/Theory.hs
Contributes to #2371 
Depends on #2547 & #2547
=> Convert velocityTM into an EquationalModel

code/drasil-docLang/Drasil/DocDecl.hs, code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-docLang/Drasil/ExtractDocDesc.hs, code/drasil-docLang/Drasil/TraceTable.hs
Finish rest of files in doclang folder.
=> DocLang documentation part 3

code/drasil-data/Data/Drasil/Equations/Defining/Physics.hs, code/drasil-data/Data/Drasil/Theories/Physics.hs, code/drasil-example/Drasil/GamePhysics/TMods.hs
Contributes to #2371 
Depends on #2549
=> Convert GP's version of Newton's SLR into EquationalModel

code/drasil-database/Database/Drasil/ChunkDB.hs, code/drasil-database/Database/Drasil/ChunkDB/GetChunk.hs, code/drasil-database/Database/Drasil/SystemInformation.hs
=> Reviewed database documentation

code/drasil-theory/Data/Drasil/TheoryConcepts.hs, code/drasil-theory/Theory/Drasil/Classes.hs, code/drasil-theory/Theory/Drasil/DataDefinition.hs, code/drasil-theory/Theory/Drasil/GenDefn.hs, code/drasil-theory/Theory/Drasil/InstanceModel.hs, code/drasil-theory/Theory/Drasil/ModelKinds.hs, code/drasil-theory/Theory/Drasil/Theory.hs
=> Documentation for drasil-theory

code/drasil-example/Drasil/SSP/TMods.hs
=> Convert mcShrStrgth into EquationalModel

code/drasil-example/Drasil/DblPendulum/GenDefs.hs, code/drasil-theory/Theory/Drasil.hs, code/drasil-theory/Theory/Drasil/GenDefn.hs
Depends on #2560 which adds customizable UIDs to GenDefns
=> Convert periodPendGD into EquationalModel

code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/GlassBR/IMods.hs, code/drasil-theory/Theory/Drasil.hs, code/drasil-theory/Theory/Drasil/InstanceModel.hs
=> Convert pbIsSafe IM into EquationalModel

code/drasil-example/Drasil/GlassBR/Body.hs, code/drasil-example/Drasil/GlassBR/IMods.hs
=> Converting GlassBR's lrIsSafe IMod into an EquationalModel

code/drasil-example/Drasil/Projectile/Body.hs, code/drasil-example/Drasil/Projectile/IMods.hs, code/stable/projectile/SRS/Projectile_SRS.tex, code/stable/projectile/Website/Projectile_SRS.html
=> Converting timeIM into EquationalModel

code/drasil-example/Drasil/Projectile/Body.hs, code/drasil-example/Drasil/Projectile/IMods.hs, code/stable/projectile/SRS/Projectile_SRS.tex, code/stable/projectile/Website/Projectile_SRS.html
=> Converting  projectile offset IM to equational model

code/drasil-example/Drasil/Projectile/Body.hs, code/drasil-example/Drasil/Projectile/IMods.hs, code/stable/projectile/SRS/Projectile_SRS.tex, code/stable/projectile/Website/Projectile_SRS.html
=> Converting projectile's landposIM to EquationalModel

code/drasil-example/Drasil/Projectile/Body.hs, code/drasil-example/Drasil/Projectile/IMods.hs
=> converting projectile messageIM to EquationalModel

code/drasil-example/Drasil/DblPendulum/GenDefs.hs
Depends on #2590 and changes their UIDs slightly
=> Convert DblPen's GD vForceOnPendulum into EquationalRealm

code/drasil-code/Language/Drasil/Code.hs, code/drasil-code/Language/Drasil/CodeSpec.hs
=> Deleting relToQD and convertRel

code/drasil-build/Build/Drasil/Make/AST.hs, code/drasil-build/Build/Drasil/Make/Helpers.hs, code/drasil-build/Build/Drasil/Make/Import.hs, code/drasil-build/Build/Drasil/Make/MakeString.hs, code/drasil-build/Build/Drasil/Make/Print.hs
=> Adding Docs to drasil-build

code/drasil-build/Build/Drasil/Make/MakeString.hs, code/drasil-code/Language/Drasil/Chunk/Code.hs, code/drasil-code/Language/Drasil/Chunk/CodeDefinition.hs, code/drasil-code/Language/Drasil/Chunk/Parameter.hs, code/drasil-code/Language/Drasil/Code/Imperative/Build/AST.hs, code/drasil-code/Language/Drasil/Code/Imperative/Build/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Comments.hs, code/drasil-code/Language/Drasil/Code/Imperative/ConceptMatch.hs, code/drasil-code/Language/Drasil/Code/Imperative/Descriptions.hs, code/drasil-code/Language/Drasil/Code/Imperative/Doxygen/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/ClassInterface.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/Data.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/CSharpRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/CppRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/JavaRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/LanguagePolymorphic.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/PythonRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/SwiftRenderer.hs, code/drasil-code/Language/Drasil/Code/Imperative/Parsers/ConfigParser.hs
Also changed a type name spelling error. It was only used in the one file where it was defined, so it shouldn't change anything.
=> `drasil-code` documentation 1

code/drasil-code/Language/Drasil/Code/Imperative/Comments.hs, code/drasil-code/Language/Drasil/Code/Imperative/ConceptMatch.hs, code/drasil-code/Language/Drasil/Code/Imperative/Descriptions.hs, code/drasil-code/Language/Drasil/Code/Imperative/DrasilState.hs, code/drasil-code/Language/Drasil/Code/Imperative/FunctionCalls.hs, code/drasil-code/Language/Drasil/Code/Imperative/GenODE.hs, code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs, code/drasil-code/Language/Drasil/Code/Imperative/Generator.hs, code/drasil-code/Language/Drasil/Code/Imperative/Helpers.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Logging.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-code/Language/Drasil/Code/Imperative/Parameters.hs, code/drasil-code/Language/Drasil/Code/Imperative/ReadInput.hs, code/drasil-code/Language/Drasil/Code/Imperative/SpaceMatch.hs, code/drasil-code/Language/Drasil/Code/Imperative/WriteInput.hs, code/drasil-code/Language/Drasil/Code/Imperative/WriteReadMe.hs
Adding comments to rest of Imperative files
=> `drasil-code` documentation 2

code/drasil-lang/Language/Drasil/Chunk/Citation.hs, code/drasil-lang/Language/Drasil/Chunk/CommonIdea.hs, code/drasil-lang/Language/Drasil/Chunk/Concept.hs, code/drasil-lang/Language/Drasil/Chunk/Concept/Core.hs, code/drasil-lang/Language/Drasil/Chunk/Constrained.hs, code/drasil-lang/Language/Drasil/Chunk/DefinedQuantity.hs, code/drasil-lang/Language/Drasil/Chunk/Eq.hs, code/drasil-lang/Language/Drasil/Chunk/NamedArgument.hs, code/drasil-lang/Language/Drasil/Chunk/NamedIdea.hs, code/drasil-lang/Language/Drasil/Chunk/Quantity.hs, code/drasil-lang/Language/Drasil/Chunk/UncertainQuantity.hs, code/drasil-lang/Language/Drasil/Chunk/UnitDefn.hs, code/drasil-lang/Language/Drasil/Chunk/Unital.hs, code/drasil-lang/Language/Drasil/Chunk/Unitary.hs, code/drasil-lang/Language/Drasil/Chunk/UnitaryConcept.hs, code/drasil-lang/Language/Drasil/DisplayClasses.hs, code/drasil-lang/Language/Drasil/DisplayExpr.hs, code/drasil-lang/Language/Drasil/Document.hs, code/drasil-lang/Language/Drasil/Document/Core.hs, code/drasil-lang/Language/Drasil/Expr/Extract.hs, code/drasil-lang/Language/Drasil/Label/Type.hs, code/drasil-lang/Language/Drasil/Reference.hs, code/drasil-lang/Language/Drasil/Symbol/Helpers.hs, code/drasil-lang/Language/Drasil/Uncertainty.hs
Made haddock comments more uniform for instance declarations. Fixed some wrong comments from before (for ListType). Added comments for some new functions.
Closes #2609
=> Refresh Lang Documentation

code/scripts/SourceCodeReaderTypes.hs
Switching a lot of code from using pattern matching to map or filter. I'm still not really sure how to make `isDataRec` and `useConstructFormRec` use a fold, but I think it is possible. Is there a premade function that does the same thing as `filterNewline`? I couldn't really find anything (`map2` is close but it doesn't allow elements to be put back into the list when calling the function again.
Also fixed the DLPlate record that wasn't showing up properly.
Contributes #2623
=> Cleaning Autogen Source File

.github/workflows/Build.yaml, code/drasil-website/stack.yaml, code/scripts/deploy_stage.sh, code/scripts/mock_deploy.sh
Related to discussion on: https://github.com/JacquesCarette/Drasil/pull/2638
Related run: https://github.com/balacij/Drasil/runs/2945710491
Website: https://balacij.github.io/Drasil/
=> Make website before deploying, so we can get the new website

code/scripts/DataTableGen.hs, code/scripts/DirectoryController.hs, code/scripts/SourceCodeReader.hs, code/scripts/SourceCodeReaderTypes.hs, code/scripts/TypeGraphGen.hs, code/scripts/deploy.bash, code/scripts/deploy_stage.sh, code/scripts/deploy_wrapper.bash, code/scripts/log_check.sh, code/scripts/make_docs.sh, code/scripts/mock_deploy.sh, code/scripts/tex_build.sh
Contributes #2642 
Only done for the scripts I'm really familiar with.
=> Some intro documentation for script files

code/drasil-code-base/Language/Drasil/Code/Expr/Convert.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-code/Language/Drasil/CodeSpec.hs, code/drasil-example/Drasil/GlassBR/Unitals.hs, code/drasil-lang/Language/Drasil.hs, code/drasil-lang/Language/Drasil/Constraint.hs, code/drasil-lang/Language/Drasil/Expr.hs, code/drasil-utils/Utils/Drasil/Fold.hs
As per discussion https://github.com/JacquesCarette/Drasil/issues/2646#issuecomment-873109412
=> Remove EnumeratedX from Constraints

code/drasil-lang/Language/Drasil/Document.hs
Contributes to Issue #1019 .
I read the notes szymczdm left in commit [47bd13d](https://github.com/JacquesCarette/Drasil/commit/47bd13d1eb7a938a59eb9fc174d57de3d833c4f7)
I created a new branch which has what he described what should be added, but i definitely don't think this is all that has to be done.
=> Adding More Partitions

code/drasil-code-base/Language/Drasil/Code/Expr.hs, code/drasil-code-base/Language/Drasil/Code/Expr/Convert.hs, code/drasil-code-base/Language/Drasil/Code/Expr/Extract.hs, code/drasil-code-base/Language/Drasil/Code/Expr/Precedence.hs, code/drasil-code/Data/Drasil/ExternalLibraries/ODELibraries.hs, code/drasil-code/Language/Drasil/Code/Imperative/Import.hs, code/drasil-printers/Language/Drasil/Printing/Import/CodeExpr.hs
=> Remove Deriv from CodeExpr

code/drasil-example/Drasil/GamePhysics/Body.hs, code/drasil-example/Drasil/GamePhysics/Expressions.hs, code/drasil-example/Drasil/GamePhysics/IMods.hs, code/drasil-example/Drasil/GamePhysics/Unitals.hs, code/stable/gamephysics/SRS/GamePhysics_SRS.tex, code/stable/gamephysics/TraceyGraph/allvsall.dot, code/stable/gamephysics/TraceyGraph/allvsr.dot, code/stable/gamephysics/TraceyGraph/avsall.dot, code/stable/gamephysics/TraceyGraph/refvsref.dot, code/stable/gamephysics/Website/GamePhysics_SRS.html
=> Convert GP's rotMot IM into an EquationalModel

code/drasil-data/Data/Drasil/Theories/Physics.hs, code/drasil-example/Drasil/DblPendulum/GenDefs.hs, code/drasil-example/Drasil/DblPendulum/IMods.hs, code/drasil-example/Drasil/GamePhysics/GenDefs.hs, code/drasil-example/Drasil/GamePhysics/IMods.hs, code/drasil-example/Drasil/GamePhysics/TMods.hs, code/drasil-example/Drasil/GlassBR/IMods.hs, code/drasil-example/Drasil/GlassBR/TMods.hs, code/drasil-example/Drasil/NoPCM/GenDefs.hs, code/drasil-example/Drasil/NoPCM/IMods.hs, code/drasil-example/Drasil/PDController/GenDefs.hs, code/drasil-example/Drasil/PDController/IModel.hs, code/drasil-example/Drasil/PDController/TModel.hs, code/drasil-example/Drasil/Projectile/GenDefs.hs, code/drasil-example/Drasil/Projectile/IMods.hs, code/drasil-example/Drasil/SSP/GenDefs.hs, code/drasil-example/Drasil/SSP/IMods.hs, code/drasil-example/Drasil/SSP/TMods.hs, code/drasil-example/Drasil/SWHS/GenDefs.hs, code/drasil-example/Drasil/SWHS/IMods.hs, code/drasil-example/Drasil/SWHS/TMods.hs, code/drasil-theory/Theory/Drasil.hs, code/drasil-theory/Theory/Drasil/GenDefn.hs, code/drasil-theory/Theory/Drasil/InstanceModel.hs, code/drasil-theory/Theory/Drasil/ModelKinds.hs, code/drasil-theory/Theory/Drasil/Theory.hs, code/stable/ssp/TraceyGraph/allvsall.dot, code/stable/ssp/TraceyGraph/allvsr.dot, code/stable/ssp/TraceyGraph/avsall.dot, code/stable/ssp/TraceyGraph/refvsref.dot
Contributes to #2371 
Builds on #2672
=> Convert SSP's crtSlpId into an EquationalModel

code/drasil-metadata/Data/Drasil/Domains.hs
=> Brief Documentation for drasil-metadata

code/drasil-gen/Language/Drasil/Generate.hs, code/drasil-gen/Language/Drasil/Output/Formats.hs
=> Brief Documentation for drasil-gen

code/drasil-website/Drasil/Website/CaseStudy.hs, code/drasil-website/Drasil/Website/Example.hs, code/drasil-website/Drasil/Website/Graphs.hs
=> Website links fix

code/drasil-docLang/Drasil/DocLang.hs, code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-docLang/Drasil/Sections/SpecificSystemDescription.hs, code/drasil-docLang/Drasil/Sections/TableOfContents.hs, code/drasil-docLang/Drasil/Sections/TableOfSymbols.hs, code/drasil-docLang/Drasil/Sections/TableOfUnits.hs
=> Moving some functions from DocumentLanguage.hs

code/drasil-example/Drasil/GlassBR/Unitals.hs, code/drasil-example/Drasil/PDController/Unitals.hs, code/drasil-example/Drasil/Projectile/Unitals.hs
=> Switching calls for `dqd` to `ucs'`

code/drasil-example/Drasil/SSP/Unitals.hs
contrubutes to issue #2704 
contributes to issue #2677
=> Switching dqd'

code/drasil-example/Drasil/GamePhysics/IMods.hs, code/stable/gamephysics/TraceyGraph/allvsall.dot, code/stable/gamephysics/TraceyGraph/allvsr.dot, code/stable/gamephysics/TraceyGraph/avsall.dot, code/stable/gamephysics/TraceyGraph/refvsref.dot
=> Convert GP's col2D into a functional EquationalModel

code/drasil-example/Drasil/GamePhysics/IMods.hs, code/drasil-example/Drasil/SWHS/IMods.hs, code/stable/gamephysics/TraceyGraph/allvsall.dot, code/stable/gamephysics/TraceyGraph/allvsr.dot, code/stable/gamephysics/TraceyGraph/avsall.dot, code/stable/gamephysics/TraceyGraph/refvsref.dot, code/stable/nopcm/TraceyGraph/allvsall.dot, code/stable/nopcm/TraceyGraph/allvsr.dot, code/stable/nopcm/TraceyGraph/avsall.dot, code/stable/nopcm/TraceyGraph/refvsref.dot, code/stable/swhs/TraceyGraph/allvsall.dot, code/stable/swhs/TraceyGraph/allvsr.dot, code/stable/swhs/TraceyGraph/avsall.dot, code/stable/swhs/TraceyGraph/refvsref.dot
=> Convert SWHS's heatEInWtr IM into a functional EquationalModel

code/drasil-example/Drasil/GamePhysics/IMods.hs, code/drasil-example/Drasil/SWHS/IMods.hs, code/drasil-example/Drasil/SWHS/TMods.hs, code/stable/gamephysics/TraceyGraph/allvsall.dot, code/stable/gamephysics/TraceyGraph/allvsr.dot, code/stable/gamephysics/TraceyGraph/avsall.dot, code/stable/gamephysics/TraceyGraph/refvsref.dot, code/stable/nopcm/TraceyGraph/allvsall.dot, code/stable/nopcm/TraceyGraph/allvsr.dot, code/stable/nopcm/TraceyGraph/avsall.dot, code/stable/nopcm/TraceyGraph/refvsref.dot, code/stable/swhs/TraceyGraph/allvsall.dot, code/stable/swhs/TraceyGraph/allvsr.dot, code/stable/swhs/TraceyGraph/avsall.dot, code/stable/swhs/TraceyGraph/refvsref.dot
=> Convert SWHS's latentHtE TM into a functional EquationalModel

code/drasil-example/Drasil/GamePhysics/IMods.hs, code/drasil-example/Drasil/SWHS/IMods.hs, code/drasil-example/Drasil/SWHS/TMods.hs, code/stable/gamephysics/TraceyGraph/allvsall.dot, code/stable/gamephysics/TraceyGraph/allvsr.dot, code/stable/gamephysics/TraceyGraph/avsall.dot, code/stable/gamephysics/TraceyGraph/refvsref.dot, code/stable/nopcm/TraceyGraph/allvsall.dot, code/stable/nopcm/TraceyGraph/allvsr.dot, code/stable/nopcm/TraceyGraph/avsall.dot, code/stable/nopcm/TraceyGraph/refvsref.dot, code/stable/swhs/TraceyGraph/allvsall.dot, code/stable/swhs/TraceyGraph/allvsr.dot, code/stable/swhs/TraceyGraph/avsall.dot, code/stable/swhs/TraceyGraph/refvsref.dot
Builds on #2710, #2712, #2713 
=>  Convert SWHS's nwtnCoolingTM into a functional EquationalModel

code/drasil-example/Drasil/DblPendulum/Body.hs
- There is no code change in this PR. I reordered some parts to match the order of the SRS.
- Comments for each section were added.
close #2705
=> Double Pendulum: Reorganize code and comments

code/stable/sglpendulum/SRS/SglPendulum_SRS.tex, code/stable/sglpendulum/Website/SglPendulum_SRS.html
=> Stabilizing Sglpendulum

code/drasil-docLang/Drasil/Sections/SpecificSystemDescription.hs, code/stable/dblpendulum/SRS/DblPendulum_SRS.tex, code/stable/dblpendulum/Website/DblPendulum_SRS.html, code/stable/glassbr/SRS/GlassBR_SRS.tex, code/stable/glassbr/Website/GlassBR_SRS.html, code/stable/nopcm/SRS/NoPCM_SRS.tex, code/stable/nopcm/Website/NoPCM_SRS.html, code/stable/pdcontroller/SRS/PDController_SRS.tex, code/stable/pdcontroller/Website/PDController_SRS.html, code/stable/projectile/SRS/Projectile_SRS.tex, code/stable/projectile/Website/Projectile_SRS.html, code/stable/sglpendulum/SRS/SglPendulum_SRS.tex, code/stable/sglpendulum/Website/SglPendulum_SRS.html, code/stable/ssp/SRS/SSP_SRS.tex, code/stable/ssp/Website/SSP_SRS.html, code/stable/swhs/SRS/SWHS_SRS.tex, code/stable/swhs/Website/SWHS_SRS.html
=> Remove Positioning Words from Figure

code/drasil-database/Database/Drasil.hs, code/drasil-database/Database/Drasil/SystemInformation.hs, code/drasil-docLang/Drasil/DocumentLanguage.hs, code/drasil-example/dblpendulum/lib/Drasil/DblPendulum/Body.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Body.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/Body.hs, code/drasil-example/hghc/lib/Drasil/HGHC/Body.hs, code/drasil-example/nopcm/lib/Drasil/NoPCM/Body.hs, code/drasil-example/pdcontroller/lib/Drasil/PDController/Body.hs, code/drasil-example/projectile/lib/Drasil/Projectile/Body.hs, code/drasil-example/sglpendulum/lib/Drasil/SglPendulum/Body.hs, code/drasil-example/ssp/lib/Drasil/SSP/Body.hs, code/drasil-example/swhs/lib/Drasil/SWHS/Body.hs, code/drasil-example/template/lib/Drasil/Template/Body.hs, code/drasil-website/Drasil/Website/Body.hs
=> Getting rid of `_folderPath` constructor

code/drasil-code-base/Language/Drasil/Code/Expr.hs, code/drasil-code-base/Language/Drasil/Code/Expr/Convert.hs, code/drasil-code-base/Language/Drasil/CodeExpr.hs, code/drasil-code/Data/Drasil/ExternalLibraries/ODELibraries.hs, code/drasil-code/Language/Drasil/Code.hs, code/drasil-code/Language/Drasil/Mod.hs, code/drasil-code/Test/FileTests.hs, code/drasil-code/Test/HelloWorld.hs, code/drasil-code/Test/Helper.hs, code/drasil-code/Test/Main.hs, code/drasil-code/Test/Observer.hs, code/drasil-code/Test/PatternTest.hs
=> Documentation for `drasil-code` and `drasil-code-base`

.github/workflows/Build.yaml, .github/workflows/Test.yaml, code/Makefile
=> Fixing CI code step

code/drasil-example/dblpendulum/lib/Drasil/DblPendulum/Requirements.hs, code/drasil-example/sglpendulum/lib/Drasil/SglPendulum/Requirements.hs, code/stable/dblpendulum/SRS/HTML/DblPendulum_SRS.html, code/stable/dblpendulum/SRS/PDF/DblPendulum_SRS.tex, code/stable/sglpendulum/SRS/HTML/SglPendulum_SRS.html, code/stable/sglpendulum/SRS/PDF/SglPendulum_SRS.tex
=> Fixing requirements section for pendulum examples

code/scripts/DataPrinters/Dot.hs, code/scripts/SourceCodeReaderT.hs, code/scripts/TypeDepGen.hs
=> Cleaning Up Type Dependency Graph Script

code/drasil-data/Data/Drasil/Citations.hs, code/drasil-data/Data/Drasil/Concepts/Computation.hs, code/drasil-data/Data/Drasil/Concepts/Documentation.hs, code/drasil-data/Data/Drasil/Concepts/Education.hs, code/drasil-data/Data/Drasil/Concepts/Math.hs, code/drasil-data/Data/Drasil/Concepts/PhysicalProperties.hs, code/drasil-data/Data/Drasil/Concepts/Physics.hs, code/drasil-data/Data/Drasil/Concepts/Software.hs, code/drasil-data/Data/Drasil/Concepts/SolidMechanics.hs, code/drasil-data/Data/Drasil/Concepts/Thermodynamics.hs, code/drasil-data/Data/Drasil/Constraints.hs, code/drasil-data/Data/Drasil/Equations/Defining/Physics.hs, code/drasil-data/Data/Drasil/People.hs, code/drasil-data/Data/Drasil/Quantities/Math.hs, code/drasil-data/Data/Drasil/Quantities/PhysicalProperties.hs, code/drasil-data/Data/Drasil/Quantities/Physics.hs, code/drasil-data/Data/Drasil/Quantities/SolidMechanics.hs, code/drasil-data/Data/Drasil/Quantities/Thermodynamics.hs, code/drasil-data/Data/Drasil/README.md, code/drasil-data/Data/Drasil/SI_Units.hs, code/drasil-data/Data/Drasil/Software/Products.hs, code/drasil-data/Data/Drasil/Theories/Physics.hs, code/drasil-data/Data/Drasil/Units/PhysicalProperties.hs, code/drasil-data/Data/Drasil/Units/Physics.hs, code/drasil-data/Data/Drasil/Units/SolidMechanics.hs, code/drasil-data/Data/Drasil/Units/Thermodynamics.hs, code/drasil-metadata/Data/Drasil/Domains.hs
=> Adding headers to data and metadata

CITATION.cff
=> Adding myself as an author in CITATION.cff

README.md, code/Drasil.md, code/README.md, code/drasil-build/README.md, code/drasil-code-base/README.md, code/drasil-code/Language/Drasil/README.md, code/drasil-code/README.md, code/drasil-data/README.md, code/drasil-database/Database/README.md, code/drasil-database/README.md, code/drasil-docLang/README.md, code/drasil-example/README.md, code/drasil-gen/Language/Drasil/README.md, code/drasil-gen/README.md, code/drasil-lang/README.md, code/drasil-printers/Language/Drasil/DOT/README.md, code/drasil-printers/Language/Drasil/HTML/README.md, code/drasil-printers/Language/Drasil/README.md, code/drasil-printers/README.md, code/drasil-theory/README.md, code/stable/README.md
=> Updating Readmes

CITATION.cff
Contributes #2798
Builds on #2806 to prevent merge conflicts
=> Adding myself to citations page

CITATION.cff
Contributes #2798
Builds on #2806 and #2809
=> Adding myself in CITATION.cff

CITATION.cff
Builds on #2806, #2809, and #2810
=> Added Sam Crawford to the citations page

CITATION.cff
Contributes #2798
Builds on #2806 to prevent merge conflicts
=> Add my author name in the list

code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-theory/Theory/Drasil/ModelKinds.hs, code/drasil-website/lib/Drasil/Website/Example.hs, code/scripts/ClassInstDepGen.hs
=> Fix HLint errors; just eta reductions in where blocks

CITATION.cff
=> Add Brooks as author to CITATION file

code/Makefile
Related to #2789 
It looks like much of the time in the `analysis` step is spent converting dot graphs into svgs and circo svgs.
=> Add more logging to `analysis` Makefile target

CITATION.cff
=> Updating Citation file to include Dan Scime.

CITATION.cff
=> Update CITATION.cff file with niazim3 info (#2798)

code/drasil-code-base/lib/Language/Drasil/Code/Expr.hs, code/drasil-lang/lib/Language/Drasil/Expr/Lang.hs, code/drasil-lang/lib/Language/Drasil/ModelExpr/Lang.hs
=> Basic comments for the 3 *Expr languages.

code/scripts/ClassInstDepGen.hs
=> Replace '.'s with '_'s in dot ID names

code/drasil-code/lib/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/PythonRenderer.hs, code/stable/dblpendulum/src/python/Makefile, code/stable/glassbr/src/python/Makefile, code/stable/nopcm/src/python/Makefile, code/stable/pdcontroller/src/python/Makefile, code/stable/projectile/projectile_c_p_nol_b_u_v_d/src/python/Makefile, code/stable/projectile/projectile_u_p_l_b_b_c_d/src/python/Makefile, code/stable/projectile/projectile_u_p_l_b_wi_v_f/src/python/Makefile, code/stable/projectile/projectile_u_p_nol_u_wi_v_d/src/python/Makefile
=> Change python to python3 in makefile

code/drasil-printers/lib/Language/Drasil/Printing/Import/ModelExpr.hs
=> Fix Address AddRe issue in Code

code/drasil-website/lib/Drasil/Website/Example.hs
=> Add double pendulum generated code on the website

code/drasil-lang/lib/Language/Drasil/Chunk/DifferentialModel.hs
Fixing a comment I made in the DifferentialModel. No code change.
=> Correct the documentation in DifferentialModel

code/drasil-code/lib/Language/Drasil/Code/Imperative/DrasilState.hs, code/drasil-data/lib/Data/Drasil/Theories/Physics.hs, code/drasil-docLang/lib/Drasil/DocumentLanguage/TraceabilityGraph.hs, code/drasil-example/dblpendulum/lib/Drasil/DblPendulum/GenDefs.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/TMods.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/Unitals.hs, code/drasil-example/nopcm/lib/Drasil/NoPCM/Body.hs, code/drasil-example/pdcontroller/lib/Drasil/PDController/Body.hs, code/drasil-example/projectile/lib/Drasil/Projectile/Lesson/Analysis.hs, code/drasil-example/sglpendulum/lib/Drasil/SglPendulum/Unitals.hs, code/drasil-gool/lib/GOOL/Drasil/State.hs, code/drasil-lang/lib/Language/Drasil/Document/Combinators.hs, code/drasil-website/lib/Drasil/Website/Analysis.hs, code/drasil-website/lib/Drasil/Website/CaseStudy.hs, code/drasil-website/lib/Drasil/Website/Example.hs
=> Follow HLint suggestions

code/Makefile
=> added packagedeps to graphs

code/drasil-data/lib/Data/Drasil/Concepts/Software.hs
removing redundant `correctness` found while working on #3072
=> removed redundant ConceptChunk

code/drasil-example/glassbr/lib/Drasil/GlassBR/Unitals.hs
Related to: https://github.com/JacquesCarette/Drasil/pull/3093#discussion_r1025093615
=> Typing: Fix probBr's type: should be a Real

README.md
Closes #2798 
If you'd like to preview it, you can using the branch view on GH: https://github.com/JacquesCarette/Drasil/tree/citationNotice
=> Add citation notice to README

code/drasil-data/lib/Data/Drasil/Quantities/Physics.hs
Closes #3113 
Acceleration and Velocity should be vectors.
=> Fixes #3113

code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Unitals.hs
fixes #3114
This might introduce new type errors, but they can be fixed in later PRs.
=> Some things should have been Vectors all along

code/drasil-example/glassbr/lib/Drasil/GlassBR/Unitals.hs, code/stable/glassbr/src/cpp/InputParameters.hpp, code/stable/glassbr/src/cpp/designLog.txt, code/stable/glassbr/src/csharp/InputParameters.cs, code/stable/glassbr/src/csharp/designLog.txt, code/stable/glassbr/src/java/GlassBR/InputParameters.java, code/stable/glassbr/src/java/designLog.txt, code/stable/glassbr/src/python/designLog.txt, code/stable/glassbr/src/swift/Calculations.swift, code/stable/glassbr/src/swift/InputParameters.swift, code/stable/glassbr/src/swift/designLog.txt
=> GTF should have been an Integer all along

code/drasil-lang/lib/Language/Drasil/Expr/Lang.hs
@balacij you might need to backport this to your type rules too?
=> Independently fix typechecker

code/drasil-example/glassbr/lib/Drasil/GlassBR/Unitals.hs
Fixes #3119 
Fixes #3118 
Fixes #3116 
Fixes #3115 .
=> Give proper types to interpY and interpZ.

code/drasil-example/ssp/lib/Drasil/SSP/DataDefs.hs, code/drasil-example/ssp/lib/Drasil/SSP/Unitals.hs, code/drasil-lang/lib/Language/Drasil/Expr/Lang.hs, code/stable/ssp/SRS/HTML/SSP_SRS.html, code/stable/ssp/SRS/PDF/SSP_SRS.tex
This can (and should be) integrated as it is 'better', but it does not fully fix any open Issue. Fixing more requires changes to Drasil itself.
=> Progress on making SSP typecheck

code/drasil-code/lib/Language/Drasil/Code/Code.hs, code/drasil-code/lib/Language/Drasil/Code/Imperative/ReadInput.hs, code/drasil-data/lib/Data/Drasil/Quantities/Math.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/DesignDec/Vector.hs, code/drasil-example/projectile/lib/Drasil/Projectile/Choices.hs, code/drasil-lang/lib/Language/Drasil/Space.hs, code/drasil-printers/lib/Language/Drasil/Printing/Import/Space.hs
Closes #3136 
It doesn't appear to have caused any type-checking errors with the few things I changed to `Real`s.
=> Remove 'Radians' from 'Space' enumeration (type universe)

code/drasil-code-base/lib/Language/Drasil/Code/Expr.hs, code/drasil-lang/lib/Language/Drasil/Expr/Class.hs, code/drasil-lang/lib/Language/Drasil/Expr/Lang.hs, code/drasil-utils/lib/Utils/Drasil.hs, code/drasil-utils/lib/Utils/Drasil/Lists.hs
Depends on #3151 
Closes #3112
=> Remove `toColumn` from Expr TTF encodings

code/drasil-lang/lib/Language/Drasil/Chunk/DifferentialModel.hs
Related to #3104 
I might as well commit it, I'm not entirely sure if it's right yet, but I think it makes more sense.
=> Change type-checking expectation for DifferentialModel

code/drasil-example/ssp/lib/Drasil/SSP/IMods.hs, code/drasil-example/ssp/lib/Drasil/SSP/Unitals.hs, code/drasil-lang/lib/Language/Drasil/Expr/Lang.hs, code/stable/ssp/SRS/HTML/SSP_SRS.html, code/stable/ssp/SRS/PDF/SSP_SRS.tex
But there are many more left!  Also, remove some awful hacks, but leave in place at least one hack.
Fixes #3106 , #3107 , #3105 .
=> Fix a bug in typechecker and some types in SSP

.github/workflows/Build.yaml
let's see if this helps with the timeouts.
=> Upgrade various things in Build.yaml

.github/workflows/Build.yaml, code/Makefile
Looks like there's something weird going on with lualatex on ubuntu-latest. So best to revert to 20.04 for now while this is being debugged.
=> Fix GI again

code/drasil-example/dblpendulum/lib/Drasil/DblPendulum/IMods.hs, code/stable/dblpendulum/SRS/HTML/DblPendulum_SRS.html, code/stable/dblpendulum/SRS/PDF/DblPendulum_SRS.tex
Fixes #3174 . Sort-of depends on the (later) PR #3180 , which should be merged first.
=> Typo. Fixes #3174

People/Jason/thesis/README.md, People/Jason/thesis/assets/code/original/expr.tex, People/Jason/thesis/chapters/07_topic_typing.tex, People/Jason/thesis/front/acknowledgements.tex, People/Jason/thesis/front/descriptive_note.tex, People/Jason/thesis/front/reading_notes.tex, People/Jason/thesis/manifest.tex
I didn't want to push to `master` without a PR, so I'm just adding this as a minor follow-up to #3190.
=> Minor touch-ups before posting thesis to MacSphere

.github/workflows/Build.yaml
=> Update GH Actions cache version

code/drasil-data/lib/Data/Drasil/Concepts/Documentation.hs, code/drasil-database/lib/Database/Drasil/ChunkDB.hs, code/drasil-docLang/lib/Drasil/DocDecl.hs, code/drasil-docLang/lib/Drasil/DocLang/SRS.hs, code/drasil-example/template/lib/Drasil/Template/Body.hs, code/drasil-sysinfo/lib/SysInfo/Drasil/SystemInformation.hs
for https://github.com/JacquesCarette/Drasil/discussions/3194#discussioncomment-4602804
=> adding comments to remind devs to update the wiki

.github/workflows/Build.yaml
=> Update GH Actions dependencies

CITATION.cff
Closes #3229 
Re-ordered as per https://github.com/JacquesCarette/Drasil/graphs/contributors
```bib
@software{Carette_Drasil_2021,
author = {Carette, Jacques and Smith, Spencer and Szymczak, Dan and Balaci, Jason and MacLachlan, Brooks and Niazi, Maryyam and Crawford, Samuel and Scime, Dan and Chen, Dong and Hunt, Anthony and Wu, Ting-Yu},
license = {BSD-2-Clause},
month = {2},
title = {{Drasil}},
url = {https://github.com/JacquesCarette/Drasil/tree/v0.1-alpha},
version = {v0.1-alpha},
year = {2021}
}
```
=> Update CITATION.cff file

code/drasil-lang/lib/Language/Drasil/Development/Sentence.hs
=> Remove HasUID from short, phrase, and plural

code/drasil-example/projectile/lib/Drasil/Projectile/Body.hs, code/stable/projectile/SRS/HTML/Projectile_SRS.html, code/stable/projectile/SRS/JSON/Projectile_SRS.ipynb, code/stable/projectile/SRS/PDF/Projectile_SRS.tex
Fixes the Projectile Problem Statement as outlined in #3207. Changes have been made to stable code and the body of the Projectile example.
=> 3207 fix projectile problem description

code/drasil-code/test/HelloWorld.hs, code/drasil-gool/lib/GOOL/Drasil/ClassInterface.hs, code/drasil-gool/lib/GOOL/Drasil/CodeInfo.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/CppRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs, code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/SwiftRenderer.hs
=> Change 'const' to 'constant' in gool

code/drasil-data/lib/Data/Drasil/Concepts/Math.hs, code/drasil-example/swhs/lib/Drasil/SWHS/IMods.hs, code/stable/ssp/SRS/HTML/SSP_SRS.html, code/stable/ssp/SRS/JSON/SSP_SRS.ipynb, code/stable/ssp/SRS/PDF/SSP_SRS.tex, code/stable/swhs/SRS/HTML/SWHS_SRS.html, code/stable/swhs/SRS/JSON/SWHS_SRS.ipynb, code/stable/swhs/SRS/PDF/SWHS_SRS.tex
Building on #3379, resolves #3380
=> Expand the abbreviation "RHS" on first use in SWHS SRS

code/drasil-example/swhs/lib/Drasil/SWHS/IMods.hs, code/stable/swhs/SRS/HTML/SWHS_SRS.html, code/stable/swhs/SRS/JSON/SWHS_SRS.ipynb, code/stable/swhs/SRS/PDF/SWHS_SRS.tex
=> Fix typo in SWHS SRS

code/drasil-docLang/lib/Drasil/DocumentLanguage.hs, code/drasil-docLang/lib/Drasil/Sections/SpecificSystemDescription.hs, code/stable/dblpendulum/SRS/HTML/DblPendulum_SRS.html, code/stable/dblpendulum/SRS/JSON/DblPendulum_SRS.ipynb, code/stable/dblpendulum/SRS/PDF/DblPendulum_SRS.tex, code/stable/glassbr/SRS/HTML/GlassBR_SRS.html, code/stable/glassbr/SRS/JSON/GlassBR_SRS.ipynb, code/stable/glassbr/SRS/PDF/GlassBR_SRS.tex, code/stable/pdcontroller/SRS/HTML/PDController_SRS.html, code/stable/pdcontroller/SRS/JSON/PDController_SRS.ipynb, code/stable/pdcontroller/SRS/PDF/PDController_SRS.tex, code/stable/projectile/SRS/HTML/Projectile_SRS.html, code/stable/projectile/SRS/JSON/Projectile_SRS.ipynb, code/stable/projectile/SRS/PDF/Projectile_SRS.tex, code/stable/sglpendulum/SRS/HTML/SglPendulum_SRS.html, code/stable/sglpendulum/SRS/JSON/SglPendulum_SRS.ipynb, code/stable/sglpendulum/SRS/PDF/SglPendulum_SRS.tex
=> Changed goal statements to reflect number of goals

code/drasil-docLang/lib/Drasil/DocumentLanguage.hs, code/drasil-docLang/lib/Drasil/DocumentLanguage/TraceabilityGraph.hs, code/drasil-docLang/lib/Drasil/DocumentLanguage/TraceabilityMatrix.hs
=> removed 'error' statement thrown when generating empty traceability matrix

code/Makefile, code/drasil-code/package.yaml, code/hie.yaml
=> Fix `make codegenTest_gen`

code/drasil-example/projectile/lib/Drasil/Projectile/Body.hs, code/stable/projectile/SRS/HTML/Projectile_SRS.html, code/stable/projectile/SRS/JSON/Projectile_SRS.ipynb, code/stable/projectile/SRS/PDF/Projectile_SRS.tex
=> update goal statement

code/countCommand.txt, code/scripts/count_words.sh
`countCommand.txt` is better off as a bash script.
=> Move countCommand.txt contents into a bash script

code/drasil-code/test/NameGenTest.hs
I previously introduced a compile error in the generated code via #3502 😅. This PR fixes it.
=> Fix compile errors in GOOL example generated code

code/drasil-code/lib/Language/Drasil/Choices.hs, code/stable/dblpendulum/src/cpp/designLog.txt, code/stable/dblpendulum/src/csharp/designLog.txt, code/stable/dblpendulum/src/java/designLog.txt, code/stable/dblpendulum/src/python/designLog.txt, code/stable/nopcm/src/cpp/designLog.txt, code/stable/nopcm/src/csharp/designLog.txt, code/stable/nopcm/src/java/designLog.txt, code/stable/nopcm/src/python/designLog.txt, code/stable/pdcontroller/src/cpp/designLog.txt, code/stable/pdcontroller/src/csharp/designLog.txt, code/stable/pdcontroller/src/java/designLog.txt, code/stable/pdcontroller/src/python/designLog.txt, code/stable/projectile/projectile_c_p_nol_b_u_v_d/src/cpp/designLog.txt, code/stable/projectile/projectile_c_p_nol_b_u_v_d/src/csharp/designLog.txt, code/stable/projectile/projectile_c_p_nol_b_u_v_d/src/java/designLog.txt, code/stable/projectile/projectile_c_p_nol_b_u_v_d/src/python/designLog.txt, code/stable/projectile/projectile_c_p_nol_b_u_v_d/src/swift/designLog.txt, code/stable/projectile/projectile_s_l_nol_u_u_v_f/src/cpp/designLog.txt, code/stable/projectile/projectile_s_l_nol_u_u_v_f/src/csharp/designLog.txt, code/stable/projectile/projectile_s_l_nol_u_u_v_f/src/java/designLog.txt, code/stable/projectile/projectile_s_l_nol_u_u_v_f/src/python/designLog.txt, code/stable/projectile/projectile_s_l_nol_u_u_v_f/src/swift/designLog.txt, code/stable/projectile/projectile_u_p_nol_u_wi_v_d/src/cpp/designLog.txt, code/stable/projectile/projectile_u_p_nol_u_wi_v_d/src/csharp/designLog.txt, code/stable/projectile/projectile_u_p_nol_u_wi_v_d/src/java/designLog.txt, code/stable/projectile/projectile_u_p_nol_u_wi_v_d/src/python/designLog.txt, code/stable/projectile/projectile_u_p_nol_u_wi_v_d/src/swift/designLog.txt
=> Generate `None`s for `designLog.txt`

code/drasil-code/lib/Data/Drasil/ExternalLibraries/ODELibraries.hs, code/drasil-code/lib/Language/Drasil/Chunk/Code.hs, code/drasil-code/lib/Language/Drasil/Chunk/CodeDefinition.hs, code/drasil-code/lib/Language/Drasil/Chunk/NamedArgument.hs, code/drasil-code/lib/Language/Drasil/Chunk/Parameter.hs, code/drasil-code/lib/Language/Drasil/Code/ExtLibImport.hs, code/drasil-code/lib/Language/Drasil/Code/ExternalLibrary.hs, code/drasil-code/lib/Language/Drasil/Code/Imperative/Import.hs, code/drasil-code/lib/Language/Drasil/Code/Imperative/ReadInput.hs, code/drasil-example/swhs/lib/Drasil/SWHS/TMods.hs, code/drasil-gen/lib/Language/Drasil/TypeCheck.hs, code/drasil-lang/lib/Language/Drasil/Chunk/CodeVar.hs, code/drasil-lang/lib/Language/Drasil/Chunk/Constrained.hs, code/drasil-lang/lib/Language/Drasil/Chunk/DefinedQuantity.hs, code/drasil-lang/lib/Language/Drasil/Chunk/DifferentialModel.hs, code/drasil-lang/lib/Language/Drasil/Chunk/Eq.hs, code/drasil-lang/lib/Language/Drasil/Chunk/Quantity.hs, code/drasil-lang/lib/Language/Drasil/Chunk/UncertainQuantity.hs, code/drasil-lang/lib/Language/Drasil/Chunk/Unital.hs, code/drasil-lang/lib/Language/Drasil/Chunk/Unitary.hs, code/drasil-lang/lib/Language/Drasil/CodeExpr/Class.hs, code/drasil-lang/lib/Language/Drasil/Space.hs, code/drasil-theory/lib/Theory/Drasil/DataDefinition.hs, code/drasil-theory/lib/Theory/Drasil/InstanceModel.hs, code/drasil-theory/lib/Theory/Drasil/ModelKinds.hs, code/drasil-theory/lib/Theory/Drasil/MultiDefn.hs
=> Use `Getter` for `HasSpace`

code/drasil-lang/lib/Language/Drasil/Chunk/Eq.hs, code/drasil-theory/lib/Theory/Drasil/DataDefinition.hs
=> Implement `HasOutput` for `DataDefinition`

code/drasil-example/glassbr/lib/Drasil/GlassBR/DataDefs.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/Unitals.hs, code/drasil-lang/lib/Language/Drasil.hs, code/drasil-lang/lib/Language/Drasil/Chunk/CommonIdea.hs
Closes #3623. Changes made to `drasil-lang` and `drasil-example`.
=> Replace getAccStr with abrv

code/drasil-printers/lib/Language/Drasil/TeX/Helpers.hs, code/stable/dblpend/SRS/PDF/DblPend_SRS.tex, code/stable/gamephysics/SRS/PDF/GamePhysics_SRS.tex, code/stable/glassbr/SRS/PDF/GlassBR_SRS.tex, code/stable/hghc/SRS/PDF/HGHC_SRS.tex, code/stable/pdcontroller/SRS/PDF/PDController_SRS.tex, code/stable/projectile/SRS/PDF/Projectile_SRS.tex, code/stable/sglpend/SRS/PDF/SglPend_SRS.tex, code/stable/ssp/SRS/PDF/SSP_SRS.tex, code/stable/swhs/SRS/PDF/SWHS_SRS.tex, code/stable/swhsnopcm/SRS/PDF/SWHSNoPCM_SRS.tex
=> Replace `\vskip` with `\medskip` in model tables

code/drasil-example/glassbr/lib/Drasil/GlassBR/IMods.hs, code/drasil-theory/lib/Theory/Drasil/DataDefinition.hs
=> Remove instance of `Quantity` for `DataDefinition`

code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Body.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/IMods.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/Symbols.hs, code/drasil-example/sglpend/lib/Drasil/SglPend/Body.hs, code/drasil-example/ssp/lib/Drasil/SSP/Body.hs, code/drasil-example/swhs/lib/Drasil/SWHS/Body.hs, code/drasil-theory/lib/Theory/Drasil/InstanceModel.hs
=> Remove instance of `Quantity` for `InstanceModel`

code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Body.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/IMods.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/Symbols.hs, code/drasil-example/sglpend/lib/Drasil/SglPend/Body.hs, code/drasil-example/ssp/lib/Drasil/SSP/Body.hs, code/drasil-example/swhs/lib/Drasil/SWHS/Body.hs, code/drasil-theory/lib/Theory/Drasil/InstanceModel.hs
Closes #3632. Builds on #3635.
=> Remove instance of `HasSpace` for `InstanceModel`

code/drasil-code/lib/Language/Drasil/Code/Imperative/Comments.hs, code/drasil-code/lib/Language/Drasil/Code/Imperative/Descriptions.hs, code/drasil-code/lib/Language/Drasil/Code/Imperative/Generator.hs, code/drasil-code/lib/Language/Drasil/Code/Imperative/Modules.hs, code/drasil-code/lib/Language/Drasil/Code/Imperative/WriteInput.hs, code/drasil-printers/lib/Language/Drasil/Debug/Print.hs, code/drasil-printers/lib/Language/Drasil/Plain/Print.hs, code/drasil-printers/lib/Language/Drasil/Printers.hs
@JacquesCarette Here is my part 1 code solution. As discussed before, part 1 is the code and part 2 is the documentation.
Part 1 works well, while I did not have any explicit changes with part 2. I guess when I change the code, their corresponding documentations are working well.
There is something I forget to mention: all code updates are following your given guidances.
If there is something missing, please inform me ASAP.
#3449 This is the corresponding issue.
=> #3449 Improve documentation for Linearity (Part 1 Code)

.github/workflows/Build.yaml
Contributes to #3548 
Testing here for 'no build' while testing 'build' in balacij/Drasil#72 (success, despite the CI failing)
From CI here:
From CI in my fork:
=> Restrict TeX builds in CI to those strictly necessary

code/drasil-lang/lib/Language/Drasil/Document/Combinators.hs, code/drasil-lang/lib/Language/Drasil/Symbol.hs
Porting from JacquesCarette/Drasil#3695
=> Update a few comments for symbol-related functions.

code/drasil-example/glassbr/lib/Drasil/GlassBR/Body.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/Unitals.hs, code/stable/glassbr/SRS/HTML/GlassBR_SRS.html, code/stable/glassbr/SRS/JSON/GlassBR_SRS.ipynb, code/stable/glassbr/SRS/PDF/GlassBR_SRS.tex
Closes #2299 
>The GlassBR SRS introduction reads poorly, so it would be nice to clean it up to read like a proper introduction. It assumes the reader already knows what the system is supposed to do / why it is there.
I made some improvements to the glassbr introduction from #2299
=> Updated Glassbr Introduction #2299

wiki/Benefits-of-Drasil.md, wiki/Power-of-Drasil.md, wiki/_Sidebar.md
Created a wiki page for the benefits of Drasil to list examples that showcase the power of generative programming within Drasil.
Closes #3778
=> Wiki: Add page for Benefits of Drasil

wiki/Converting-GOOL-Classes-into-Struct-Libraries-for-Procedural-Languages.md, wiki/_Sidebar.md
Also added the page to the sidebar.
=> Updated the wiki page for converting GOOL to procedural languages

.github/workflows/Wiki.yaml
=> Wiki Workflow: less verbose error message for manual wiki edit check

wiki/Benefits-of-Drasil.md
Fixed typo and added new example (#3881). 
Closes #3884
=> Add new example in benefits-of-drasil wiki

code/drasil-example/dblpend/lib/Drasil/DblPend/Assumptions.hs, code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs, code/drasil-example/dblpend/lib/Drasil/DblPend/Derivations.hs, code/drasil-example/dblpend/lib/Drasil/DblPend/Expressions.hs, code/drasil-example/dblpend/lib/Drasil/DblPend/GenDefs.hs, code/drasil-example/dblpend/lib/Drasil/DblPend/Requirements.hs, code/stack.yaml
1. Fix some minor grammar and clarity typos.
@JacquesCarette @samm82 The official solution of issue #3252 comes tonight, this is to improve the quality of contributions.
=> #3252 Preparation Works

wiki/GOOL-GProc Overview.md
Currently it goes over the file structure and tries to give an explanation for how things are roughly organized.  I'll hopefully add to it as I have time to do so.
=> Created a GOOL overview for the Wiki

code/drasil-gool/lib/Drasil/GOOL/AST.hs, code/drasil-gool/lib/Drasil/GOOL/InterfaceCommon.hs, code/drasil-gool/lib/Drasil/GOOL/InterfaceGOOL.hs, code/drasil-gool/lib/Drasil/GOOL/InterfaceProc.hs, code/drasil-gool/lib/Drasil/GOOL/RendererClassesCommon.hs, code/drasil-gool/lib/Drasil/GOOL/RendererClassesOO.hs
I updated a few comments to reflect changes, and added some more comments explaining the parameters of some GOOL functions.
=> Added/Updated Comments in `drasil-gool`

code/drasil-gool/lib/Drasil/GOOL/LanguageRenderer/CommonPseudoOO.hs, code/drasil-gool/lib/Drasil/GOOL/LanguageRenderer/JuliaRenderer.hs
=> Updated Julia to render `Set`s as Sets, not Arrays

code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Body.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Changes.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/DataDefs.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/GDefs.hs
Update some sentence re-works in the Gamephysics example.
@JacquesCarette @balacij @samm82 Because the GamePhysics examples still have lots of sentences, I am going to submit another PR by the end of today.
=> #3252 Sentence Reworking (for the GamePhysics Example, Part 1)

code/drasil-example/gamephysics/lib/Drasil/GamePhysics/GDefs.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/GenDefs.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/IMods.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Requirements.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/TMods.hs, code/stack.yaml
Re-work some existing sentences by inserting defined concepts inside.
Continue with #3953
=> #3252 Sentence Reworking (for the GamePhysics Example, Part 2)

code/README.md
#2857 Part 1 Update (Many update parts coming)
Update the root folder's README.md.
@balacij @JacquesCarette I just split all modifications and put them on small-size PRs.
=> #2857 out-of-date README.md Update 1

code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs, code/drasil-example/dblpend/lib/Drasil/DblPend/IMods.hs, code/stable/dblpend/SRS/HTML/DblPend_SRS.html, code/stable/dblpend/SRS/Jupyter/DblPend_SRS.ipynb, code/stable/dblpend/SRS/PDF/DblPend_SRS.tex, code/stable/dblpend/SRS/mdBook/src/SecIMs.md
Re-work some existing sentences by inserting defined concepts inside.
@JacquesCarette Now all requirements satisfy requirements.
Also, I found one mistake inside the sentence body.
=> #3252 Sentence Reworking (for the Dblpend Example, Satisfied requirement)

code/drasil-example/projectile/lib/Drasil/Projectile/Lesson/CaseProb.hs, code/drasil-example/projectile/lib/Drasil/Projectile/Lesson/Example.hs
Re-work some existing sentences by inserting defined concepts inside.
@JacquesCarette @balacij This update on the `projectile` example only includes two files' changes, because there are lots of sentences waiting to be re-worked.
=> #3252 Sentence Reworking (for the Projectile Example, Part 1)

code/drasil-example/projectile/lib/Drasil/Projectile/Body.hs, code/drasil-example/projectile/lib/Drasil/Projectile/Lesson/Review.hs, code/drasil-example/projectile/lib/Drasil/Projectile/Requirements.hs
=> #3252 Sentence Reworking (for the Projectile Example, Part 2)

code/drasil-example/swhs/lib/Drasil/SWHS/DataDefs.hs, code/drasil-example/swhs/lib/Drasil/SWHS/GenDefs.hs, code/drasil-example/swhs/lib/Drasil/SWHS/IMods.hs
=> #3252 Sentence Reworking (for the SWHS Example, Part 2)

code/drasil-build/lib/Build/Drasil/Make/README.md, code/drasil-code/lib/README.md, code/drasil-database/lib/Database/Drasil/README.md, code/drasil-docLang/lib/Drasil/DocumentLanguage/README.md, code/drasil-gen/lib/README.md
Update out-of-date README.md files
=> #2857 out-of-date README.md Update 2

wiki/What-If.md
As per the comments on the first PR on this, aka #3978 .
=> take care of all the comments from Jason

code/drasil-docLang/lib/Drasil/SRSDocument.hs, code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Body.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/Body.hs, code/drasil-example/glassbr/lib/Drasil/GlassBR/IMods.hs, code/drasil-example/hghc/lib/Drasil/HGHC/Body.hs, code/drasil-example/pdcontroller/lib/Drasil/PDController/Body.hs, code/drasil-example/projectile/lib/Drasil/Projectile/Body.hs, code/drasil-example/projectile/lib/Drasil/Projectile/Lesson/Body.hs, code/drasil-example/sglpend/lib/Drasil/SglPend/Body.hs, code/drasil-example/ssp/lib/Drasil/SSP/Body.hs, code/drasil-example/swhs/lib/Drasil/SWHS/Body.hs, code/drasil-example/swhsnopcm/lib/Drasil/SWHSNoPCM/Body.hs, code/drasil-example/template/lib/Drasil/Template/Body.hs, code/drasil-gen/lib/Language/Drasil/TypeCheck.hs, code/drasil-sysinfo/lib/SysInfo/Drasil.hs, code/drasil-sysinfo/lib/SysInfo/Drasil/SystemInformation.hs, code/drasil-website/lib/Drasil/Website/Body.hs
In our latest meeting, @szymczdm, @JacquesCarette and @smiths mentioned you found one unused field in the `SystemInformation`. I think this is the one.
=> Remove unused SystemInformation field.

code/drasil-gen/lib/Language/Drasil/Dump.hs
Contributes to #2873 
This PR merely lets us see what chunks added to the ChunkDB are "just" terms.
My suspicion is that a "TermTable" shouldn't exist and that we should instead think of it as a "term cache" until the upgraded chunkdb prototype is merged and we start working on replacing `TypeRep` with something else.
_Why?_ A TermTable contains `IdeaDict`s:
https://github.com/JacquesCarette/Drasil/blob/cd996e49b222deaf25bac195b16d34fd611138b2/code/drasil-lang/lib/Language/Drasil/Chunk/NamedIdea.hs#L46-L56
Realistically, this chunk is just shy of empty. It contains a UID, a noun phrase, and maybe a short name. In some sense, this is great because, long-term, I think we want something like this (not necessarily a chunk) before we create actual meaningful chunks that prescribe meaning to …
=> Add new database dump file: things that are _just_ terms.

code/drasil-code/lib/Language/Drasil/Code/Imperative/Comments.hs, code/drasil-database/lib/Database/Drasil.hs, code/drasil-database/lib/Database/Drasil/ChunkDB.hs, code/drasil-database/lib/Database/Drasil/Dump.hs, code/drasil-printers/lib/Language/Drasil/Debug/Print.hs
=> Rename defTable to conceptChunkTable 

code/drasil-example/glassbr/lib/Drasil/GlassBR/Symbols.hs
=> Remove duplicate symbols caused by iMods in GlassBR SymbolMap

wiki/Contributor's-Guide.md
Closes #3784 
First draft of a section in the [contributor's guide](https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide) discussing best `git` practices in Drasil, feedback would be greatly appreciated!
=> Contributor's Guide: Add git advice

code/drasil-database/lib/Database/Drasil/ChunkDB.hs, code/drasil-docLang/lib/Drasil/DocumentLanguage.hs
Contributes to #4036 by showing us where the duplicate `UID`s are.
=> ChunkDB: Warn on duplicate UID insertion.

wiki/New-Workspace-Setup.md
Closes #4048 
Also adds some information about using Cygwin with VSCode.
=> Cygwin new workspace setup clarification

code/drasil-data/lib/Data/Drasil/Concepts/Education.hs
=> Remove 'physical' duplicate and swap its usage for existing chunk

code/drasil-example/glassbr/lib/Drasil/GlassBR/Body.hs
Contributes to #4131 and #4130
=> Clear up unused import and name shadow warnings.

code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Body.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Unitals.hs
=> Remove all `SymbolMap` duplicates in GamePhysics

code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Body.hs
Latest build on `main` failed: https://github.com/JacquesCarette/Drasil/actions/runs/15544714409/job/43763587954
=> Fix main build.

code/drasil-lang/lib/Language/Drasil/Classes.hs, code/drasil-lang/lib/Language/Drasil/Development/Sentence.hs
Closes #4081 
Adds a bit of documentation explaining the discussion from #4081.
=> Add documentation to explain `short` vs `getA` vs `abrv`

code/drasil-example/projectile/lib/Drasil/Projectile/Body.hs
=> Only add needed concepts to projectile `TermMap`

code/drasil-example/glassbr/lib/Drasil/GlassBR/Body.hs
=> GlassBR: Remove duplicate `UnitDefn`-related Terms

code/drasil-example/sglpend/lib/Drasil/SglPend/Body.hs
=> SglPend: Remove duplicate `UnitDefn`-related Terms

code/drasil-data/lib/Data/Drasil/SI_Units.hs, code/drasil-example/swhs/lib/Drasil/SWHS/Body.hs, code/drasil-example/swhsnopcm/lib/Drasil/SWHSNoPCM/Body.hs
=> SWHS[NoPCM]: Remove duplicate `UnitDefn`-related Terms

code/drasil-example/sglpend/lib/Drasil/SglPend/Body.hs
=> SglPend: Chunks with acronyms do not need to be added twice

code/drasil-example/sglpend/lib/Drasil/SglPend/Unitals.hs
=> SglPend: Remove unital chunk duplicates

code/drasil-example/swhsnopcm/lib/Drasil/SWHSNoPCM/Body.hs
=> SWHSNoPCM: Chunks with acronyms don't need to be added again

code/drasil-code/lib/Data/Drasil/ExternalLibraries/ODELibraries.hs, code/drasil-example/swhsnopcm/lib/Drasil/SWHSNoPCM/Body.hs
=> SWHSNoPCM: Remove all `SymbolMap` duplicates

code/drasil-example/swhs/lib/Drasil/SWHS/Body.hs
=> SWHS: Chunks with acronyms don't need to be added again

code/drasil-example/ssp/lib/Drasil/SSP/Body.hs
=> SSP: Chunks with acronyms don't need to be added again

code/drasil-code/lib/Data/Drasil/ExternalLibraries/ODELibraries.hs, code/drasil-example/pdcontroller/lib/Drasil/PDController/Body.hs, code/drasil-example/swhsnopcm/lib/Drasil/SWHSNoPCM/Body.hs
=> PDController: Only add constants once to `symbolsAll`

code/drasil-example/projectile/lib/Drasil/Projectile/Body.hs
=> Projectile: Remove `inValue` duplicate

code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs
=> DblPend: Remove `inValue` duplicate

code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs
=> DblPend: Remove concept duplicates

code/drasil-example/dblpend/lib/Drasil/DblPend/Unitals.hs
=> DblPend: Remove `gravitationalMagnitude` duplicate

code/drasil-example/dblpend/lib/Drasil/DblPend/Unitals.hs
=> DblPend: iMod outputs are already added, remove duplicates

code/drasil-data/lib/Data/Drasil/Concepts/Computation.hs
=> Remove copies of data structure and data type chunks

code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Unitals.hs
=> GamePhysics: Remove output constraints from ConceptMap, unused

code/drasil-example/swhsnopcm/lib/Drasil/SWHSNoPCM/Body.hs
=> SWHSNoPCM: Split concepts list to populate SymbolMap and ConceptMap with correct chunks

code/drasil-example/swhs/lib/Drasil/SWHS/Unitals.hs
=> SWHS: Make units and unital chunks unique

code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Body.hs
=> GamePhysics: Instance models already added in separate table, remove from concept table

code/drasil-example/projectile/lib/Drasil/Projectile/Body.hs
=> Projectile: Constrained `ConstrConcepts` already added to concept table, uneeded in term table

code/drasil-example/ssp/lib/Drasil/SSP/Body.hs
=> SSP: Instance models already added in separate table

code/drasil-example/swhs/lib/Drasil/SWHS/Body.hs
=> SWHS: Instance models already added in separate chunk table

code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs
=> DblPend: Remove unused physics quantities, only concepts are used

code/drasil-lang/lib/Language/Drasil/Chunk/DefinedQuantity.hs, code/drasil-lang/lib/Language/Drasil/Chunk/Unital.hs
=> Replace `tempdqdWr` with `dqdWr`

code/drasil-example/glassbr/lib/Drasil/GlassBR/Unitals.hs, code/drasil-example/swhs/lib/Drasil/SWHS/Unitals.hs, code/drasil-lang/lib/Language/Drasil.hs, code/drasil-lang/lib/Language/Drasil/Chunk/Unitary.hs
Contributes to #4272 
Added definitions are placeholders and will be updated as I work on this.
=> Replace `unitary` with `uc'`, using DefinedQuantityDicts

code/drasil-example/dblpend/lib/Drasil/DblPend/GenDefs.hs, code/drasil-example/gamephysics/lib/Drasil/GamePhysics/TMods.hs, code/drasil-example/sglpend/lib/Drasil/SglPend/GenDefs.hs, code/drasil-theory/lib/Theory/Drasil/MultiDefn.hs
=> Use DefinedQuantityDicts in MultiDefns instead of QuantityDicts

wiki/Contributor's-Guide.md, wiki/Git2Know-for-Drasil.md
I'm happy to write a bit more, but this should be good enough to get started.
=> Wiki: Explain how to acknowledge co-authors.
